Major refactor, changing the fundamental inner workings.

diff --git a/bin/posix_adapter__cut b/bin/posix_adapter__cut
--- a/bin/posix_adapter__cut
+++ b/bin/posix_adapter__cut
@@ -9,39 +9,46 @@
 # TOOL: CUT
 #==============================================================================
 
-#==============================================================================
-#
-#  posix_adapter__cut --delimiter <delimiter_char> --fields <index_def> [file]
-#  posix_adapter__cut --characters <index_def> [file]
-#
-#------------------------------------------------------------------------------
-# Execution mapping function for the 'cut' command line tool with a uniform
-# interface.
-#------------------------------------------------------------------------------
-# Globals:
-#   None
-# Options:
-#   --delimiter <delimiter_char> - cut compatible delimiter definition
-#   --fields <index_definition> - cut compatible fields definition
-#   --characters <index_definition> - cut compatible characters definition
-# Arguments:
-#   [1] [file] - File that should be processed.
-# STDIN:
-#   Input passed to the mapped command.
-#------------------------------------------------------------------------------
-# Output variables:
-#   None
-# STDOUT:
-#   Mapped command's output.
-# STDERR:
-#   Mapped command's error output. Mapping error output.
-# Status:
-#   0  - Call was successful.
-#   .. - Call failed with it's error status
-#   POSIX_ADAPTER__STATUS__INVALID_PARAMETERS - Invalid parameter configuration.
-#   POSIX_ADAPTER__STATUS__INCOMPATIBLE_CALL - No compatible call style was found.
-#==============================================================================
-posix_adapter__cut() {
+TOOL_NAME='posix_adapter__cut'
+
+_print_help() {
+  >&2 echo '=============================================================================='
+  >&2 echo ''
+  >&2 echo '  posix_adapter__cut --help'
+  >&2 echo '  posix_adapter__cut --delimiter <delimiter_char> --fields <index_def> [file]'
+  >&2 echo '  posix_adapter__cut --characters <index_def> [file]'
+  >&2 echo ''
+  >&2 echo '------------------------------------------------------------------------------'
+  >&2 echo ' Execution mapping function for the "cut" command line tool with a uniform'
+  >&2 echo ' interface.'
+  >&2 echo '------------------------------------------------------------------------------'
+  >&2 echo ' Globals:'
+  >&2 echo '   None'
+  >&2 echo ' Options:'
+  >&2 echo '   --help - Prints out the help message and exits.'
+  >&2 echo '   --delimiter <delimiter_char> - cut compatible delimiter definition'
+  >&2 echo '   --fields <index_definition> - cut compatible fields definition'
+  >&2 echo '   --characters <index_definition> - cut compatible characters definition'
+  >&2 echo ' Arguments:'
+  >&2 echo '   [1] [file] - File that should be processed.'
+  >&2 echo ' STDIN:'
+  >&2 echo '   Input passed to the mapped command.'
+  >&2 echo '------------------------------------------------------------------------------'
+  >&2 echo ' Output variables:'
+  >&2 echo '   None'
+  >&2 echo ' STDOUT:'
+  >&2 echo '   Output of the mapped command.'
+  >&2 echo ' STDERR:'
+  >&2 echo '   Error output of the mapped command.'
+  >&2 echo ' Status:'
+  >&2 echo '   0  - Call was successful.'
+  >&2 echo '   .. - Call failed with its error status.'
+  >&2 echo '   98 - Invalid parameter configuration.'
+  >&2 echo '   99 - No compatible call style was found.'
+  >&2 echo '=============================================================================='
+}
+
+_posix_adapter__cut() {
   posix_adapter__flag__delimiter='0'
   posix_adapter__value__delimiter=''
 
@@ -76,14 +83,12 @@ posix_adapter__cut() {
         shift
         ;;
       --[!-]*)
-        posix_adapter__report_invalid_parameters \
-          'posix_adapter__cut' \
+        _report_invalid_parameter \
           "Unexpected option '${1}'!" \
-          'You can only use (--delimiter --fields) or (--characters).'
+          'You can only use the available options.'
         ;;
       -[!-]*)
-        posix_adapter__report_invalid_parameters \
-          'posix_adapter__cut' \
+        _report_invalid_parameter \
           "Invalid single dashed option '${1}'!" \
           "posix_adapter only uses double dashed options like '--option'."
         ;;
@@ -95,8 +100,7 @@ posix_adapter__cut() {
           posix_adapter__value__file="$1"
           shift
         else
-          posix_adapter__report_invalid_parameters \
-            'posix_adapter__cut' \
+          _report_invalid_parameter \
             'Unexpected parameter!' \
             "Parameter '${1}' is unexpected!"
         fi
@@ -207,10 +211,77 @@ _posix_adapter__cut__common() {
 
       ;;
     *)
-      posix_adapter__report_invalid_parameters \
-        'posix_adapter__cut' \
+      _report_invalid_parameter_combination \
         'Unexpected parameter combination!' \
-        'You can only have (--delimiter --fields) or (--characters).'
+        'You can only use the available options.'
       ;;
   esac
 }
+
+#==============================================================================
+# Invalid parameter error reporting helper function.
+#------------------------------------------------------------------------------
+# Globals:
+#   TOOL_NAME
+# Options:
+#   None
+# Arguments:
+#   [1] reason - Reason of the error.
+#   [2] details - More details about the error.
+# STDIN:
+#   None
+#------------------------------------------------------------------------------
+# Output variables:
+#   None
+# STDOUT:
+#   None
+# STDERR:
+#   Reported error.
+# Status:
+#   98  - The function will terminate the execution.
+#==============================================================================
+_report_invalid_parameter() {
+  reason="$1"
+  details="$2"
+  >&2 echo "ERROR | ${TOOL_NAME} | reason  | ${reason}"
+  >&2 echo "ERROR | ${TOOL_NAME} | details | ${details}"
+  _print_help
+  exit 98
+}
+
+#==============================================================================
+# Invalid parameter combination error reporting helper function.
+#------------------------------------------------------------------------------
+# Globals:
+#   TOOL_NAME
+# Options:
+#   None
+# Arguments:
+#   [1] reason - Reason of the error.
+#   [2] details - More details about the error.
+# STDIN:
+#   None
+#------------------------------------------------------------------------------
+# Output variables:
+#   None
+# STDOUT:
+#   None
+# STDERR:
+#   Reported error.
+# Status:
+#   99  - The function will terminate the execution.
+#==============================================================================
+_report_invalid_parameter_combination() {
+  reason="$1"
+  details="$2"
+  >&2 echo "ERROR | ${TOOL_NAME} | reason  | ${reason}"
+  >&2 echo "ERROR | ${TOOL_NAME} | details | ${details}"
+  _print_help
+  exit 99
+}
+
+#==============================================================================
+# ENTRY POINT
+#==============================================================================
+
+_posix_adapter__cut "$@"
diff --git a/bin/posix_adapter__grep b/bin/posix_adapter__grep
--- a/bin/posix_adapter__grep
+++ b/bin/posix_adapter__grep
@@ -8,48 +8,48 @@
 # TOOL: GREP
 #==============================================================================
 
-#==============================================================================
-#
-#  posix_adapter__grep
-#    [--extended]
-#    [--silent]
-#    [--invert-match]
-#    [--count]
-#    [--match-only]
-#    <pattern>
-#    [path]
-#
-#------------------------------------------------------------------------------
-# Execution mapping function for the 'echo' command line tool with a uniform
-# interface.
-#------------------------------------------------------------------------------
-# Globals:
-#   None
-# Options:
-#   --extended - Use extended regular expression.
-#   --silent - Use silent mode.
-#   --invert-match - Use the inverted match feature.
-#   --count - Use count feature.
-#   --match-only - Use the only matching feature.
-# Arguments:
-#   [1] pattern - grep compatible pattern.
-#   [2] [path] - Optional file path in which grep should operate.
-# STDIN:
-#   Input passed to the mapped command.
-#------------------------------------------------------------------------------
-# Output variables:
-#   None
-# STDOUT:
-#   Mapped command's output.
-# STDERR:
-#   Mapped command's error output. Mapping error output.
-# Status:
-#   0  - Call was successful.
-#   .. - Call failed with it's error status
-#   POSIX_ADAPTER__STATUS__INVALID_PARAMETERS - Invalid parameter configuration.
-#   POSIX_ADAPTER__STATUS__INCOMPATIBLE_CALL - No compatible call style was found.
-#==============================================================================
-posix_adapter__grep() {
+TOOL_NAME='posix_adapter__grep'
+
+_print_help() {
+  >&2 echo '=============================================================================='
+  >&2 echo ''
+  >&2 echo '  posix_adapter__grep --help'
+  >&2 echo '  posix_adapter__grep [--extended] [--silent] [--invert-match] [--count]'
+  >&2 echo '      [--match-only] <pattern> [path]'
+  >&2 echo ''
+  >&2 echo '------------------------------------------------------------------------------'
+  >&2 echo ' Execution mapping function for the "echo" command line tool with a uniform'
+  >&2 echo ' interface.'
+  >&2 echo '------------------------------------------------------------------------------'
+  >&2 echo ' Globals:'
+  >&2 echo '   None'
+  >&2 echo ' Options:'
+  >&2 echo '   --help - Prints out the help message and exits.'
+  >&2 echo '   --extended - Use extended regular expression.'
+  >&2 echo '   --silent - Use silent mode.'
+  >&2 echo '   --invert-match - Use the inverted match feature.'
+  >&2 echo '   --count - Use count feature.'
+  >&2 echo '   --match-only - Use the only matching feature.'
+  >&2 echo ' Arguments:'
+  >&2 echo '   [1] pattern - grep compatible pattern.'
+  >&2 echo '   [2] [path] - Optional file path in which grep should operate.'
+  >&2 echo ' STDIN:'
+  >&2 echo '   Input passed to the mapped command.'
+  >&2 echo '------------------------------------------------------------------------------'
+  >&2 echo ' Output variables:'
+  >&2 echo '   None'
+  >&2 echo ' STDOUT:'
+  >&2 echo '   Output of the mapped command.'
+  >&2 echo ' STDERR:'
+  >&2 echo '   Error output of the mapped command.'
+  >&2 echo ' Status:'
+  >&2 echo '   0  - Call was successful.'
+  >&2 echo '   .. - Call failed with its error status.'
+  >&2 echo '   98 - Invalid parameter configuration.'
+  >&2 echo '   99 - No compatible call style was found.'
+  >&2 echo '=============================================================================='
+}
+_posix_adapter__grep() {
   posix_adapter__flag__extended='0'
   posix_adapter__flag__silent='0'
   posix_adapter__flag__invert_match='0'
@@ -86,14 +86,12 @@ posix_adapter__grep() {
         shift
         ;;
       --[!-]*)
-        posix_adapter__report_invalid_parameters \
-          'posix_adapter__grep' \
+        _report_invalid_parameter \
           "Unexpected option '${1}'!" \
-          'You can only use --extended --silent --invert-match --count --match-only.'
+          'You can only use the available options.'
         ;;
       -[!-]*)
-        posix_adapter__report_invalid_parameters \
-          'posix_adapter__grep' \
+        _report_invalid_parameter \
           "Invalid single dashed option '${1}'!" \
           "posix_adapter only uses double dashed options like '--option'."
         ;;
@@ -110,8 +108,7 @@ posix_adapter__grep() {
             posix_adapter__value__path="$1"
             shift
           else
-            posix_adapter__report_invalid_parameters \
-              'posix_adapter__grep' \
+            _report_invalid_parameter \
               'Unexpected parameter!' \
               "Parameter '${1}' is unexpected!"
           fi
@@ -122,8 +119,7 @@ posix_adapter__grep() {
 
   if [ "$posix_adapter__flag__pattern" -eq '0' ]
   then
-    posix_adapter__report_invalid_parameters \
-      'posix_adapter__grep' \
+    _report_invalid_parameter \
       'Missing <pattern> argument!' \
       'To be able to use grep, you need to specify at least a pattern.'
   fi
@@ -1268,10 +1264,77 @@ _posix_adapter__grep__common() {
 
       ;;
     *)
-      posix_adapter__report_invalid_parameters \
-        'posix_adapter__grep' \
+      _report_invalid_parameter_combination \
         'Unexpected parameter combination!' \
-        'You can only have (--delimiter --fields) or (--characters).'
+        'You can only use the available options.'
       ;;
   esac
 }
+
+#==============================================================================
+# Invalid parameter error reporting helper function.
+#------------------------------------------------------------------------------
+# Globals:
+#   TOOL_NAME
+# Options:
+#   None
+# Arguments:
+#   [1] reason - Reason of the error.
+#   [2] details - More details about the error.
+# STDIN:
+#   None
+#------------------------------------------------------------------------------
+# Output variables:
+#   None
+# STDOUT:
+#   None
+# STDERR:
+#   Reported error.
+# Status:
+#   98  - The function will terminate the execution.
+#==============================================================================
+_report_invalid_parameter() {
+  reason="$1"
+  details="$2"
+  >&2 echo "ERROR | ${TOOL_NAME} | reason  | ${reason}"
+  >&2 echo "ERROR | ${TOOL_NAME} | details | ${details}"
+  _print_help
+  exit 98
+}
+
+#==============================================================================
+# Invalid parameter combination error reporting helper function.
+#------------------------------------------------------------------------------
+# Globals:
+#   TOOL_NAME
+# Options:
+#   None
+# Arguments:
+#   [1] reason - Reason of the error.
+#   [2] details - More details about the error.
+# STDIN:
+#   None
+#------------------------------------------------------------------------------
+# Output variables:
+#   None
+# STDOUT:
+#   None
+# STDERR:
+#   Reported error.
+# Status:
+#   99  - The function will terminate the execution.
+#==============================================================================
+_report_invalid_parameter_combination() {
+  reason="$1"
+  details="$2"
+  >&2 echo "ERROR | ${TOOL_NAME} | reason  | ${reason}"
+  >&2 echo "ERROR | ${TOOL_NAME} | details | ${details}"
+  _print_help
+  exit 99
+}
+
+#==============================================================================
+# ENTRY POINT
+#==============================================================================
+
+_posix_adapter__grep "$@"
diff --git a/bin/posix_adapter__mktemp b/bin/posix_adapter__mktemp
--- a/bin/posix_adapter__mktemp
+++ b/bin/posix_adapter__mktemp
@@ -9,38 +9,45 @@
 # TOOL: MKTEMP
 #==============================================================================
 
-#==============================================================================
-#
-#  posix_adapter__mktemp [--directory] [--tmpdir <path>] <template>
-#
-#------------------------------------------------------------------------------
-# Execution mapping function for the 'mktemp' command line tool with a
-# uniform interface.
-#------------------------------------------------------------------------------
-# Globals:
-#   None
-# Options:
-#   --directory - Flag that indicates that a directory should be made.
-#   --tmpdir <path> - Path prefix where the temp file/directory should be
-#                     created into based on the template.
-# Arguments:
-#   [1] tempate - mktemp compatible template definition.
-# STDIN:
-#   Input passed to the mapped command.
-#------------------------------------------------------------------------------
-# Output variables:
-#   None
-# STDOUT:
-#   Mapped command's output.
-# STDERR:
-#   Mapped command's error output. Mapping error output.
-# Status:
-#   0  - Call was successful.
-#   .. - Call failed with it's error status
-#   POSIX_ADAPTER__STATUS__INVALID_PARAMETERS - Invalid parameter configuration.
-#   POSIX_ADAPTER__STATUS__INCOMPATIBLE_CALL - No compatible call style was found.
-#==============================================================================
-posix_adapter__mktemp() {
+TOOL_NAME='posix_adapter__mktemp'
+
+_print_help() {
+  >&2 echo '=============================================================================='
+  >&2 echo ''
+  >&2 echo '  posix_adapter__mktemp --help'
+  >&2 echo '  posix_adapter__mktemp [--directory] [--tmpdir <path>] <template>'
+  >&2 echo ''
+  >&2 echo '------------------------------------------------------------------------------'
+  >&2 echo ' Execution mapping function for the "mktemp" command line tool with a'
+  >&2 echo ' uniform interface.'
+  >&2 echo '------------------------------------------------------------------------------'
+  >&2 echo ' Globals:'
+  >&2 echo '   None'
+  >&2 echo ' Options:'
+  >&2 echo '   --help - Prints out the help message and exits.'
+  >&2 echo '   --directory - Flag that indicates that a directory should be made.'
+  >&2 echo '   --tmpdir <path> - Path prefix where the temp file/directory should be'
+  >&2 echo '                     created into based on the template.'
+  >&2 echo ' Arguments:'
+  >&2 echo '   [1] tempate - mktemp compatible template definition.'
+  >&2 echo ' STDIN:'
+  >&2 echo '   Input passed to the mapped command.'
+  >&2 echo '------------------------------------------------------------------------------'
+  >&2 echo ' Output variables:'
+  >&2 echo '   None'
+  >&2 echo ' STDOUT:'
+  >&2 echo '   Output of the mapped command.'
+  >&2 echo ' STDERR:'
+  >&2 echo '   Error output of the mapped command.'
+  >&2 echo ' Status:'
+  >&2 echo '   0  - Call was successful.'
+  >&2 echo '   .. - Call failed with its error status.'
+  >&2 echo '   98 - Invalid parameter configuration.'
+  >&2 echo '   99 - No compatible call style was found.'
+  >&2 echo '=============================================================================='
+}
+
+_posix_adapter__mktemp() {
   posix_adapter__flag__directory='0'
 
   posix_adapter__flag__tmpdir='0'
@@ -63,14 +70,12 @@ posix_adapter__mktemp() {
         shift
         ;;
       --[!-]*)
-        posix_adapter__report_invalid_parameters \
-          'posix_adapter__mktemp' \
+        _report_invalid_parameter \
           "Unexpected option '${1}'!" \
-          'You can only use --extended --silent --invert-match --count -- match-only.'
+          'You can only use the available options.'
         ;;
       -[!-]*)
-        posix_adapter__report_invalid_parameters \
-          'posix_adapter__mktemp' \
+        _report_invalid_parameter \
           "Invalid single dashed option '${1}'!" \
           "posix_adapter only uses double dashed options like '--option'."
         ;;
@@ -81,8 +86,7 @@ posix_adapter__mktemp() {
           posix_adapter__value__template="$1"
           shift
         else
-          posix_adapter__report_invalid_parameters \
-            'posix_adapter__mktemp' \
+          _report_invalid_parameter \
             'Unexpected parameter!' \
             "Parameter '${1}' is unexpected!"
         fi
@@ -92,8 +96,7 @@ posix_adapter__mktemp() {
 
   if [ "$posix_adapter__flag__template" -eq '0' ]
   then
-    posix_adapter__report_invalid_parameters \
-      'posix_adapter__mktemp' \
+    _report_invalid_parameter \
       'Missing <template> argument!' \
       'To be able to use grep, you need to specify at least a pattern.'
   fi
@@ -105,16 +108,15 @@ posix_adapter__mktemp() {
   posix_adapter__decision="${posix_adapter__flag__directory}"
   posix_adapter__decision="${posix_adapter__decision}${posix_adapter__flag__tmpdir}"
 
-  case "$POSIX_ADAPTER__RUNTIME__OS" in
-
-    "$POSIX_ADAPTER__CONSTANT__OS__LINUX")
+  case "$(uname -s)" in
+    Linux)
       _posix_adapter__mktemp__linux \
         "$posix_adapter__decision" \
         "$posix_adapter__value__tmpdir" \
         "$posix_adapter__value__template"
       ;;
 
-    "$POSIX_ADAPTER__CONSTANT__OS__MACOS")
+    Darwin)
       _posix_adapter__mktemp__darwin \
         "$posix_adapter__decision" \
         "$posix_adapter__value__tmpdir" \
@@ -122,7 +124,9 @@ posix_adapter__mktemp() {
       ;;
 
     *)
-      posix_adapter__report_incompatible_call 'posix_adapter__mktemp'
+      _report_invalid_parameter_combination \
+        "Unsupported platform '$(uname -s)'!" \
+        'The tool is only implemented for Linux and Darwin so far.'
       ;;
   esac
 }
@@ -194,8 +198,7 @@ _posix_adapter__mktemp__linux() {
 
       ;;
     *)
-      posix_adapter__report_invalid_parameters \
-        'posix_adapter__mktemp' \
+      _report_invalid_parameter_combination \
         'Unexpected parameter combination!' \
         'You can only have --directory --tmpdir.'
       ;;
@@ -265,10 +268,77 @@ _posix_adapter__mktemp__darwin() {
 
       ;;
     *)
-      posix_adapter__report_invalid_parameters \
-        'posix_adapter__mktemp' \
+      _report_invalid_parameter_combination \
         'Unexpected parameter combination!' \
-        'You can only have (--delimiter --fields) or (--characters).'
+        'You can only use the available options.'
       ;;
   esac
 }
+
+#==============================================================================
+# Invalid parameter error reporting helper function.
+#------------------------------------------------------------------------------
+# Globals:
+#   TOOL_NAME
+# Options:
+#   None
+# Arguments:
+#   [1] reason - Reason of the error.
+#   [2] details - More details about the error.
+# STDIN:
+#   None
+#------------------------------------------------------------------------------
+# Output variables:
+#   None
+# STDOUT:
+#   None
+# STDERR:
+#   Reported error.
+# Status:
+#   98  - The function will terminate the execution.
+#==============================================================================
+_report_invalid_parameter() {
+  reason="$1"
+  details="$2"
+  >&2 echo "ERROR | ${TOOL_NAME} | reason  | ${reason}"
+  >&2 echo "ERROR | ${TOOL_NAME} | details | ${details}"
+  _print_help
+  exit 98
+}
+
+#==============================================================================
+# Invalid parameter combination error reporting helper function.
+#------------------------------------------------------------------------------
+# Globals:
+#   TOOL_NAME
+# Options:
+#   None
+# Arguments:
+#   [1] reason - Reason of the error.
+#   [2] details - More details about the error.
+# STDIN:
+#   None
+#------------------------------------------------------------------------------
+# Output variables:
+#   None
+# STDOUT:
+#   None
+# STDERR:
+#   Reported error.
+# Status:
+#   99  - The function will terminate the execution.
+#==============================================================================
+_report_invalid_parameter_combination() {
+  reason="$1"
+  details="$2"
+  >&2 echo "ERROR | ${TOOL_NAME} | reason  | ${reason}"
+  >&2 echo "ERROR | ${TOOL_NAME} | details | ${details}"
+  _print_help
+  exit 99
+}
+
+#==============================================================================
+# ENTRY POINT
+#==============================================================================
+
+_posix_adapter__mktemp "$@"
diff --git a/bin/posix_adapter__readlink b/bin/posix_adapter__readlink
--- a/bin/posix_adapter__readlink
+++ b/bin/posix_adapter__readlink
@@ -9,36 +9,43 @@
 # TOOL: READLINK
 #==============================================================================
 
-#==============================================================================
-#
-#  posix_adapter__readlink [--canonicalize] <path>
-#
-#------------------------------------------------------------------------------
-# Execution mapping function for the 'readlink' command line tool with a
-# uniform interface.
-#------------------------------------------------------------------------------
-# Globals:
-#   None
-# Options:
-#   --canonicalize - readlink compatible flag for the original -f flag.
-# Arguments:
-#   [1] path - Path that should be resolved.
-# STDIN:
-#   Input passed to the mapped command.
-#------------------------------------------------------------------------------
-# Output variables:
-#   None
-# STDOUT:
-#   Mapped command's output.
-# STDERR:
-#   Mapped command's error output. Mapping error output.
-# Status:
-#   0  - Call was successful.
-#   .. - Call failed with it's error status
-#   POSIX_ADAPTER__STATUS__INVALID_PARAMETERS - Invalid parameter configuration.
-#   POSIX_ADAPTER__STATUS__INCOMPATIBLE_CALL - No compatible call style was found.
-#==============================================================================
-posix_adapter__readlink() {
+TOOL_NAME='posix_adapter__readlink'
+
+_print_help() {
+  >&2 echo '=============================================================================='
+  >&2 echo ''
+  >&2 echo '  posix_adapter__readlink --help'
+  >&2 echo '  posix_adapter__readlink [--canonicalize] <path>'
+  >&2 echo ''
+  >&2 echo '------------------------------------------------------------------------------'
+  >&2 echo ' Execution mapping function for the "readlink" command line tool with a'
+  >&2 echo ' uniform interface.'
+  >&2 echo '------------------------------------------------------------------------------'
+  >&2 echo ' Globals:'
+  >&2 echo '   None'
+  >&2 echo ' Options:'
+  >&2 echo '   --help - Prints out the help message and exits.'
+  >&2 echo '   --canonicalize - readlink compatible flag for the original -f flag.'
+  >&2 echo ' Arguments:'
+  >&2 echo '   [1] path - Path that should be resolved.'
+  >&2 echo ' STDIN:'
+  >&2 echo '   Input passed to the mapped command.'
+  >&2 echo '------------------------------------------------------------------------------'
+  >&2 echo ' Output variables:'
+  >&2 echo '   None'
+  >&2 echo ' STDOUT:'
+  >&2 echo '   Output of the mapped command.'
+  >&2 echo ' STDERR:'
+  >&2 echo '   Error output of the mapped command.'
+  >&2 echo ' Status:'
+  >&2 echo '   0  - Call was successful.'
+  >&2 echo '   .. - Call failed with its error status.'
+  >&2 echo '   98 - Invalid parameter configuration.'
+  >&2 echo '   99 - No compatible call style was found.'
+  >&2 echo '=============================================================================='
+}
+
+_posix_adapter__readlink() {
   posix_adapter__flag__canonicalize='0'
 
   posix_adapter__flag__path='0'
@@ -52,14 +59,12 @@ posix_adapter__readlink() {
         shift
         ;;
       --[!-]*)
-        posix_adapter__report_invalid_parameters \
-          'posix_adapter__readlink' \
+        _report_invalid_parameter \
           "Unexpected option '${1}'!" \
-          'You can only use --canonicalize.'
+          'You can only use the available options.'
         ;;
       -[!-]*)
-        posix_adapter__report_invalid_parameters \
-          'posix_adapter__readlink' \
+        _report_invalid_parameter \
           "Invalid single dashed option '${1}'!" \
           "posix_adapter only uses double dashed options like '--option'."
         ;;
@@ -70,8 +75,7 @@ posix_adapter__readlink() {
           posix_adapter__value__path="$1"
           shift
         else
-          posix_adapter__report_invalid_parameters \
-            'posix_adapter__readlink' \
+          _report_invalid_parameter \
             'Unexpected parameter!' \
             "Parameter '${1}' is unexpected!"
         fi
@@ -81,8 +85,7 @@ posix_adapter__readlink() {
 
   if [ "$posix_adapter__flag__path" -eq '0' ]
   then
-    posix_adapter__report_invalid_parameters \
-      'posix_adapter__readlink' \
+    _report_invalid_parameter \
       'Missing <path> argument!' \
       'To be able to use readlink, you need to specify a path to work with.'
   fi
@@ -92,22 +95,23 @@ posix_adapter__readlink() {
   # 0
   posix_adapter__decision="${posix_adapter__flag__canonicalize}"
 
-  case "$POSIX_ADAPTER__RUNTIME__OS" in
-
-    "$POSIX_ADAPTER__CONSTANT__OS__LINUX")
+  case "$(uname -s)" in
+    Linux)
       _posix_adapter__readlink__linux \
         "$posix_adapter__decision" \
         "$posix_adapter__value__path"
       ;;
 
-    "$POSIX_ADAPTER__CONSTANT__OS__MACOS")
+    Darwin)
       _posix_adapter__readlink__darwin \
         "$posix_adapter__decision" \
         "$posix_adapter__value__path"
       ;;
 
     *)
-      posix_adapter__report_incompatible_call 'posix_adapter__mktemp'
+      _report_invalid_parameter_combination \
+        "Unsupported platform '$(uname -s)'!" \
+        'The tool is only implemented for Linux and Darwin so far.'
       ;;
   esac
 }
@@ -155,10 +159,9 @@ _posix_adapter__readlink__linux() {
 
       ;;
     *)
-      posix_adapter__report_invalid_parameters \
-        'posix_adapter__readlink' \
+      _report_invalid_parameter_combination \
         'Unexpected parameter combination!' \
-        'You can only have --canonicalize.'
+        'You can only use the available options.'
       ;;
   esac
 }
@@ -209,10 +212,77 @@ _posix_adapter__readlink__darwin() {
       fi
       ;;
     *)
-      posix_adapter__report_invalid_parameters \
-        'posix_adapter__readlink' \
+      _report_invalid_parameter_combination \
         'Unexpected parameter combination!' \
-        'You can only have --canonicalize.'
+        'You can only use the available options.'
       ;;
   esac
 }
+
+#==============================================================================
+# Invalid parameter error reporting helper function.
+#------------------------------------------------------------------------------
+# Globals:
+#   TOOL_NAME
+# Options:
+#   None
+# Arguments:
+#   [1] reason - Reason of the error.
+#   [2] details - More details about the error.
+# STDIN:
+#   None
+#------------------------------------------------------------------------------
+# Output variables:
+#   None
+# STDOUT:
+#   None
+# STDERR:
+#   Reported error.
+# Status:
+#   98  - The function will terminate the execution.
+#==============================================================================
+_report_invalid_parameter() {
+  reason="$1"
+  details="$2"
+  >&2 echo "ERROR | ${TOOL_NAME} | reason  | ${reason}"
+  >&2 echo "ERROR | ${TOOL_NAME} | details | ${details}"
+  _print_help
+  exit 98
+}
+
+#==============================================================================
+# Invalid parameter combination error reporting helper function.
+#------------------------------------------------------------------------------
+# Globals:
+#   TOOL_NAME
+# Options:
+#   None
+# Arguments:
+#   [1] reason - Reason of the error.
+#   [2] details - More details about the error.
+# STDIN:
+#   None
+#------------------------------------------------------------------------------
+# Output variables:
+#   None
+# STDOUT:
+#   None
+# STDERR:
+#   Reported error.
+# Status:
+#   99  - The function will terminate the execution.
+#==============================================================================
+_report_invalid_parameter_combination() {
+  reason="$1"
+  details="$2"
+  >&2 echo "ERROR | ${TOOL_NAME} | reason  | ${reason}"
+  >&2 echo "ERROR | ${TOOL_NAME} | details | ${details}"
+  _print_help
+  exit 99
+}
+
+#==============================================================================
+# ENTRY POINT
+#==============================================================================
+
+_posix_adapter__readlink "$@"
diff --git a/bin/posix_adapter__realpath b/bin/posix_adapter__realpath
--- a/bin/posix_adapter__realpath
+++ b/bin/posix_adapter__realpath
@@ -9,37 +9,44 @@
 # TOOL: REALPATH
 #==============================================================================
 
-#==============================================================================
-#
-#  posix_adapter__realpath [--no-symlinks] <target_path>
-#  posix_adapter__realpath [--no-symlinks] --relative-to <path> <target_path>
-#
-#------------------------------------------------------------------------------
-# Execution mapping function for the 'realpath' command line tool with a
-# uniform interface.
-#------------------------------------------------------------------------------
-# Globals:
-#   None
-# Options:
-#   --no-symlinks - realpath compatible flag for the -s flag.
-# Arguments:
-#   [1] path - Path that should be resolved.
-# STDIN:
-#   Input passed to the mapped command.
-#------------------------------------------------------------------------------
-# Output variables:
-#   None
-# STDOUT:
-#   Mapped command's output.
-# STDERR:
-#   Mapped command's error output. Mapping error output.
-# Status:
-#   0  - Call was successful.
-#   .. - Call failed with it's error status
-#   POSIX_ADAPTER__STATUS__INVALID_PARAMETERS - Invalid parameter configuration.
-#   POSIX_ADAPTER__STATUS__INCOMPATIBLE_CALL - No compatible call style was found.
-#==============================================================================
-posix_adapter__realpath() {
+TOOL_NAME='posix_adapter__realpath'
+
+_print_help() {
+  >&2 echo '=============================================================================='
+  >&2 echo ''
+  >&2 echo '  posix_adapter__realpath --help'
+  >&2 echo '  posix_adapter__realpath [--no-symlinks] <target_path>'
+  >&2 echo '  posix_adapter__realpath [--no-symlinks] --relative-to <path> <target_path>'
+  >&2 echo ''
+  >&2 echo '------------------------------------------------------------------------------'
+  >&2 echo ' Execution mapping function for the "realpath" command line tool with a'
+  >&2 echo ' uniform interface.'
+  >&2 echo '------------------------------------------------------------------------------'
+  >&2 echo ' Globals:'
+  >&2 echo '   None'
+  >&2 echo ' Options:'
+  >&2 echo '   --help - Prints out the help message and exits.'
+  >&2 echo '   --no-symlinks - realpath compatible flag for the -s flag.'
+  >&2 echo ' Arguments:'
+  >&2 echo '   [1] path - Path that should be resolved.'
+  >&2 echo ' STDIN:'
+  >&2 echo '   Input passed to the mapped command.'
+  >&2 echo '------------------------------------------------------------------------------'
+  >&2 echo ' Output variables:'
+  >&2 echo '   None'
+  >&2 echo ' STDOUT:'
+  >&2 echo '   Output of the mapped command.'
+  >&2 echo ' STDERR:'
+  >&2 echo '   Error output of the mapped command.'
+  >&2 echo ' Status:'
+  >&2 echo '   0  - Call was successful.'
+  >&2 echo '   .. - Call failed with its error status.'
+  >&2 echo '   98 - Invalid parameter configuration.'
+  >&2 echo '   99 - No compatible call style was found.'
+  >&2 echo '=============================================================================='
+}
+
+_posix_adapter__realpath() {
   posix_adapter__flag__no_symlinks='0'
 
   posix_adapter__flag__relative_to='0'
@@ -62,14 +69,12 @@ posix_adapter__realpath() {
         shift
         ;;
       --[!-]*)
-        posix_adapter__report_invalid_parameters \
-          'posix_adapter__realpath' \
+        _report_invalid_parameter \
           "Unexpected option '${1}'!" \
-          'You can only have --no-symlinks or --relative-to.'
+          'You can only use the available options.'
         ;;
       -[!-]*)
-        posix_adapter__report_invalid_parameters \
-          'posix_adapter__realpath' \
+        _report_invalid_parameter \
           "Invalid single dashed option '${1}'!" \
           "posix_adapter only uses double dashed options like '--option'."
         ;;
@@ -80,8 +85,7 @@ posix_adapter__realpath() {
           posix_adapter__value__path="$1"
           shift
         else
-          posix_adapter__report_invalid_parameters \
-            'posix_adapter__realpath' \
+          _report_invalid_parameter \
             'Unexpected parameter!' \
             "Parameter '${1}' is unexpected!"
         fi
@@ -91,8 +95,7 @@ posix_adapter__realpath() {
 
   if [ "$posix_adapter__flag__path" -eq '0' ]
   then
-    posix_adapter__report_invalid_parameters \
-      'posix_adapter__realpath' \
+    _report_invalid_parameter \
       'Missing <path> argument!' \
       'To be able to use realpath, you need to specify a path to work with.'
   fi
@@ -104,16 +107,15 @@ posix_adapter__realpath() {
   posix_adapter__decision="${posix_adapter__flag__no_symlinks}"
   posix_adapter__decision="${posix_adapter__decision}${posix_adapter__flag__relative_to}"
 
-  case "$POSIX_ADAPTER__RUNTIME__OS" in
-
-    "$POSIX_ADAPTER__CONSTANT__OS__LINUX")
+  case "$(uname -s)" in
+    Linux)
       _posix_adapter__realpath__linux \
         "$posix_adapter__decision" \
         "$posix_adapter__value__relative_to" \
         "$posix_adapter__value__path"
       ;;
 
-    "$POSIX_ADAPTER__CONSTANT__OS__MACOS")
+    Darwin)
       _posix_adapter__realpath__darwin \
         "$posix_adapter__decision" \
         "$posix_adapter__value__relative_to" \
@@ -121,7 +123,9 @@ posix_adapter__realpath() {
       ;;
 
     *)
-      posix_adapter__report_incompatible_call 'posix_adapter__mktemp'
+      _report_invalid_parameter_combination \
+        "Unsupported platform '$(uname -s)'!" \
+        'The tool is only implemented for Linux and Darwin so far.'
       ;;
   esac
 }
@@ -193,10 +197,9 @@ _posix_adapter__realpath__linux() {
 
       ;;
     *)
-      posix_adapter__report_invalid_parameters \
-        'posix_adapter__realpath' \
+      _report_invalid_parameter_combination \
         'Unexpected parameter combination!' \
-        'You can only have --no-symlinks or --relative-to.'
+        'You can only use the available options.'
       ;;
   esac
 }
@@ -272,10 +275,77 @@ _posix_adapter__realpath__darwin() {
       fi
       ;;
     *)
-      posix_adapter__report_invalid_parameters \
-        'posix_adapter__realpath' \
+      _report_invalid_parameter_combination \
         'Unexpected parameter combination!' \
-        'You can only have --no-symlinks or --relative-to.'
+        'You can only use the available options.'
       ;;
   esac
 }
+
+#==============================================================================
+# Invalid parameter error reporting helper function.
+#------------------------------------------------------------------------------
+# Globals:
+#   TOOL_NAME
+# Options:
+#   None
+# Arguments:
+#   [1] reason - Reason of the error.
+#   [2] details - More details about the error.
+# STDIN:
+#   None
+#------------------------------------------------------------------------------
+# Output variables:
+#   None
+# STDOUT:
+#   None
+# STDERR:
+#   Reported error.
+# Status:
+#   98  - The function will terminate the execution.
+#==============================================================================
+_report_invalid_parameter() {
+  reason="$1"
+  details="$2"
+  >&2 echo "ERROR | ${TOOL_NAME} | reason  | ${reason}"
+  >&2 echo "ERROR | ${TOOL_NAME} | details | ${details}"
+  _print_help
+  exit 98
+}
+
+#==============================================================================
+# Invalid parameter combination error reporting helper function.
+#------------------------------------------------------------------------------
+# Globals:
+#   TOOL_NAME
+# Options:
+#   None
+# Arguments:
+#   [1] reason - Reason of the error.
+#   [2] details - More details about the error.
+# STDIN:
+#   None
+#------------------------------------------------------------------------------
+# Output variables:
+#   None
+# STDOUT:
+#   None
+# STDERR:
+#   Reported error.
+# Status:
+#   99  - The function will terminate the execution.
+#==============================================================================
+_report_invalid_parameter_combination() {
+  reason="$1"
+  details="$2"
+  >&2 echo "ERROR | ${TOOL_NAME} | reason  | ${reason}"
+  >&2 echo "ERROR | ${TOOL_NAME} | details | ${details}"
+  _print_help
+  exit 99
+}
+
+#==============================================================================
+# ENTRY POINT
+#==============================================================================
+
+_posix_adapter__realpath "$@"
diff --git a/bin/posix_adapter__sed b/bin/posix_adapter__sed
--- a/bin/posix_adapter__sed
+++ b/bin/posix_adapter__sed
@@ -9,42 +9,46 @@
 # TOOL: SED
 #==============================================================================
 
-#==============================================================================
-#
-#  posix_adapter__sed
-#    [--extended]
-#    [--in-place <suffix>]
-#    [--expression <expression>]
-#    [<path>]
-#
-#------------------------------------------------------------------------------
-# Execution mapping function for the 'sed' command line tool with a
-# uniform interface.
-#------------------------------------------------------------------------------
-# Globals:
-#   None
-# Options:
-#   --extended - Use the extended regexp engine.
-#   --in-place <suffix> - In place processing with optional backup with suffix.
-#   --expression <expression> - Expression that should be executed.
-# Arguments:
-#   [1] [path] - Optional file path.
-# STDIN:
-#   Input passed to the mapped command.
-#------------------------------------------------------------------------------
-# Output variables:
-#   None
-# STDOUT:
-#   Mapped command's output.
-# STDERR:
-#   Mapped command's error output. Mapping error output.
-# Status:
-#   0  - Call was successful.
-#   .. - Call failed with it's error status
-#   POSIX_ADAPTER__STATUS__INVALID_PARAMETERS - Invalid parameter configuration.
-#   POSIX_ADAPTER__STATUS__INCOMPATIBLE_CALL - No compatible call style was found.
-#==============================================================================
-posix_adapter__sed() {
+TOOL_NAME='posix_adapter__sed'
+
+_print_help() {
+  >&2 echo '=============================================================================='
+  >&2 echo ''
+  >&2 echo '  posix_adapter__sed --help'
+  >&2 echo '  posix_adapter__sed [--extended] [--in-place <suffix>]'
+  >&2 echo '      [--expression <expression>] [<path>]'
+  >&2 echo ''
+  >&2 echo '------------------------------------------------------------------------------'
+  >&2 echo ' Execution mapping function for the "sed" command line tool with a'
+  >&2 echo ' uniform interface.'
+  >&2 echo '------------------------------------------------------------------------------'
+  >&2 echo ' Globals:'
+  >&2 echo '   None'
+  >&2 echo ' Options:'
+  >&2 echo '   --help - Prints out the help message and exits.'
+  >&2 echo '   --extended - Use the extended regexp engine.'
+  >&2 echo '   --in-place <suffix> - In place processing with optional backup with suffix.'
+  >&2 echo '   --expression <expression> - Expression that should be executed.'
+  >&2 echo ' Arguments:'
+  >&2 echo '   [1] [path] - Optional file path.'
+  >&2 echo ' STDIN:'
+  >&2 echo '   Input passed to the mapped command.'
+  >&2 echo '------------------------------------------------------------------------------'
+  >&2 echo ' Output variables:'
+  >&2 echo '   None'
+  >&2 echo ' STDOUT:'
+  >&2 echo '   Output of the mapped command.'
+  >&2 echo ' STDERR:'
+  >&2 echo '   Error output of the mapped command.'
+  >&2 echo ' Status:'
+  >&2 echo '   0  - Call was successful.'
+  >&2 echo '   .. - Call failed with its error status.'
+  >&2 echo '   98 - Invalid parameter configuration.'
+  >&2 echo '   99 - No compatible call style was found.'
+  >&2 echo '=============================================================================='
+}
+
+_posix_adapter__sed() {
   posix_adapter__flag__extended='0'
 
   posix_adapter__flag__in_place='0'
@@ -76,14 +80,12 @@ posix_adapter__sed() {
         shift
         ;;
       --[!-]*)
-        posix_adapter__report_invalid_parameters \
-          'posix_adapter__sed' \
+        _report_invalid_parameter \
           "Unexpected option '${1}'!" \
-          'You can only use --extended or --expression or --in-place.'
+          'You can only use the available options.'
         ;;
       -[!-]*)
-        posix_adapter__report_invalid_parameters \
-          'posix_adapter__sed' \
+        _report_invalid_parameter \
           "Invalid single dashed option '${1}'!" \
           "posix_adapter only uses double dashed options like '--option'."
         ;;
@@ -99,8 +101,7 @@ posix_adapter__sed() {
             printf '%s' 'probably forgot the --expression flag before '; \
             printf '%s\n' 'your expression which is mandatory in posix_adapter.' \
           )"
-          posix_adapter__report_invalid_parameters \
-            'posix_adapter__sed' \
+          _report_invalid_parameter \
             'Unexpected parameter!' \
             "$posix_adapter__error_details"
         fi
@@ -255,10 +256,77 @@ _posix_adapter__sed__common() {
 
       ;;
     *)
-      posix_adapter__report_invalid_parameters \
-        'posix_adapter__sed' \
+      _report_invalid_parameter_combination \
         'Unexpected parameter combination!' \
-        '--expression is mandatory, --extended and --in-place is optional'
+        'You can only use the available options.'
       ;;
   esac
 }
+
+#==============================================================================
+# Invalid parameter error reporting helper function.
+#------------------------------------------------------------------------------
+# Globals:
+#   TOOL_NAME
+# Options:
+#   None
+# Arguments:
+#   [1] reason - Reason of the error.
+#   [2] details - More details about the error.
+# STDIN:
+#   None
+#------------------------------------------------------------------------------
+# Output variables:
+#   None
+# STDOUT:
+#   None
+# STDERR:
+#   Reported error.
+# Status:
+#   98  - The function will terminate the execution.
+#==============================================================================
+_report_invalid_parameter() {
+  reason="$1"
+  details="$2"
+  >&2 echo "ERROR | ${TOOL_NAME} | reason  | ${reason}"
+  >&2 echo "ERROR | ${TOOL_NAME} | details | ${details}"
+  _print_help
+  exit 98
+}
+
+#==============================================================================
+# Invalid parameter combination error reporting helper function.
+#------------------------------------------------------------------------------
+# Globals:
+#   TOOL_NAME
+# Options:
+#   None
+# Arguments:
+#   [1] reason - Reason of the error.
+#   [2] details - More details about the error.
+# STDIN:
+#   None
+#------------------------------------------------------------------------------
+# Output variables:
+#   None
+# STDOUT:
+#   None
+# STDERR:
+#   Reported error.
+# Status:
+#   99  - The function will terminate the execution.
+#==============================================================================
+_report_invalid_parameter_combination() {
+  reason="$1"
+  details="$2"
+  >&2 echo "ERROR | ${TOOL_NAME} | reason  | ${reason}"
+  >&2 echo "ERROR | ${TOOL_NAME} | details | ${details}"
+  _print_help
+  exit 99
+}
+
+#==============================================================================
+# ENTRY POINT
+#==============================================================================
+
+_posix_adapter__sed "$@"
diff --git a/bin/posix_adapter__sort b/bin/posix_adapter__sort
--- a/bin/posix_adapter__sort
+++ b/bin/posix_adapter__sort
@@ -9,37 +9,44 @@
 # TOOL: SORT
 #==============================================================================
 
-#==============================================================================
-#
-#  posix_adapter__sort [--zero-terminated] [--dictionary-order] [<path>]
-#
-#------------------------------------------------------------------------------
-# Execution mapping function for the 'sed' command line tool with a
-# uniform interface.
-#------------------------------------------------------------------------------
-# Globals:
-#   None
-# Options:
-#   --zero-terminated - Use the sort compatible -z flag.
-#   --dictionary-order - Use the sort compatible -d flag.
-# Arguments:
-#   [1] [path] - Optional file path.
-# STDIN:
-#   Input passed to the mapped command.
-#------------------------------------------------------------------------------
-# Output variables:
-#   None
-# STDOUT:
-#   Mapped command's output.
-# STDERR:
-#   Mapped command's error output. Mapping error output.
-# Status:
-#   0  - Call was successful.
-#   .. - Call failed with it's error status
-#   POSIX_ADAPTER__STATUS__INVALID_PARAMETERS - Invalid parameter configuration.
-#   POSIX_ADAPTER__STATUS__INCOMPATIBLE_CALL - No compatible call style was found.
-#==============================================================================
-posix_adapter__sort() {
+TOOL_NAME='posix_adapter__sort'
+
+_print_help() {
+  >&2 echo '=============================================================================='
+  >&2 echo ''
+  >&2 echo '  posix_adapter__sort --help'
+  >&2 echo '  posix_adapter__sort [--zero-terminated] [--dictionary-order] [<path>]'
+  >&2 echo ''
+  >&2 echo '------------------------------------------------------------------------------'
+  >&2 echo ' Execution mapping function for the "sed" command line tool with a'
+  >&2 echo ' uniform interface.'
+  >&2 echo '------------------------------------------------------------------------------'
+  >&2 echo ' Globals:'
+  >&2 echo '   None'
+  >&2 echo ' Options:'
+  >&2 echo '   --help - Prints out the help message and exits.'
+  >&2 echo '   --zero-terminated - Use the sort compatible -z flag.'
+  >&2 echo '   --dictionary-order - Use the sort compatible -d flag.'
+  >&2 echo ' Arguments:'
+  >&2 echo '   [1] [path] - Optional file path.'
+  >&2 echo ' STDIN:'
+  >&2 echo '   Input passed to the mapped command.'
+  >&2 echo '------------------------------------------------------------------------------'
+  >&2 echo ' Output variables:'
+  >&2 echo '   None'
+  >&2 echo ' STDOUT:'
+  >&2 echo '   Output of the mapped command.'
+  >&2 echo ' STDERR:'
+  >&2 echo '   Error output of the mapped command.'
+  >&2 echo ' Status:'
+  >&2 echo '   0  - Call was successful.'
+  >&2 echo '   .. - Call failed with its error status.'
+  >&2 echo '   98 - Invalid parameter configuration.'
+  >&2 echo '   99 - No compatible call style was found.'
+  >&2 echo '=============================================================================='
+}
+
+_posix_adapter__sort() {
   posix_adapter__flag__zero_terminated='0'
   posix_adapter__flag__dictionary_order='0'
 
@@ -58,14 +65,12 @@ posix_adapter__sort() {
         shift
         ;;
       --[!-]*)
-        posix_adapter__report_invalid_parameters \
-          'posix_adapter__sort' \
+        _report_invalid_parameter \
           "Unexpected option '${1}'!" \
-          'You can only use --zero-terminated or --dictionary-order.'
+          'You can only use the available options.'
         ;;
       -[!-]*)
-        posix_adapter__report_invalid_parameters \
-          'posix_adapter__sort' \
+        _report_invalid_parameter \
           "Invalid single dashed option '${1}'!" \
           "posix_adapter only uses double dashed options like '--option'."
         ;;
@@ -76,8 +81,7 @@ posix_adapter__sort() {
           posix_adapter__value__path="$1"
           shift
         else
-          posix_adapter__report_invalid_parameters \
-            'posix_adapter__sort' \
+          _report_invalid_parameter \
             'Unexpected parameter!' \
             "Parameter '${1}' is unexpected!"
         fi
@@ -208,10 +212,77 @@ _posix_adapter__sort__common() {
 
       ;;
     *)
-      posix_adapter__report_invalid_parameters \
-        'posix_adapter__sort' \
+      _report_invalid_parameter_combination \
         'Unexpected parameter combination!' \
-        'Only --zero-terminated and --dictionary-order is available.'
+        'You can only use the available options.'
       ;;
   esac
 }
+
+#==============================================================================
+# Invalid parameter error reporting helper function.
+#------------------------------------------------------------------------------
+# Globals:
+#   TOOL_NAME
+# Options:
+#   None
+# Arguments:
+#   [1] reason - Reason of the error.
+#   [2] details - More details about the error.
+# STDIN:
+#   None
+#------------------------------------------------------------------------------
+# Output variables:
+#   None
+# STDOUT:
+#   None
+# STDERR:
+#   Reported error.
+# Status:
+#   98  - The function will terminate the execution.
+#==============================================================================
+_report_invalid_parameter() {
+  reason="$1"
+  details="$2"
+  >&2 echo "ERROR | ${TOOL_NAME} | reason  | ${reason}"
+  >&2 echo "ERROR | ${TOOL_NAME} | details | ${details}"
+  _print_help
+  exit 98
+}
+
+#==============================================================================
+# Invalid parameter combination error reporting helper function.
+#------------------------------------------------------------------------------
+# Globals:
+#   TOOL_NAME
+# Options:
+#   None
+# Arguments:
+#   [1] reason - Reason of the error.
+#   [2] details - More details about the error.
+# STDIN:
+#   None
+#------------------------------------------------------------------------------
+# Output variables:
+#   None
+# STDOUT:
+#   None
+# STDERR:
+#   Reported error.
+# Status:
+#   99  - The function will terminate the execution.
+#==============================================================================
+_report_invalid_parameter_combination() {
+  reason="$1"
+  details="$2"
+  >&2 echo "ERROR | ${TOOL_NAME} | reason  | ${reason}"
+  >&2 echo "ERROR | ${TOOL_NAME} | details | ${details}"
+  _print_help
+  exit 99
+}
+
+#==============================================================================
+# ENTRY POINT
+#==============================================================================
+
+_posix_adapter__sort "$@"
diff --git a/bin/posix_adapter__wc b/bin/posix_adapter__wc
--- a/bin/posix_adapter__wc
+++ b/bin/posix_adapter__wc
@@ -9,38 +9,45 @@
 # TOOL: WC
 #==============================================================================
 
-#==============================================================================
-#
-#  posix_adapter__wc [--chars] [--lines] [--words] [<path>]
-#
-#------------------------------------------------------------------------------
-# Execution mapping function for the 'wc' command line tool with a
-# uniform interface.
-#------------------------------------------------------------------------------
-# Globals:
-#   None
-# Options:
-#   --chars - Use the wc compatible -c flag.
-#   --lines - Use the wc compatible -l flag.
-#   --words - Use the wc compatible -w flag.
-# Arguments:
-#   [1] [path] - Optional file path.
-# STDIN:
-#   Input passed to the mapped command.
-#------------------------------------------------------------------------------
-# Output variables:
-#   None
-# STDOUT:
-#   Mapped command's output.
-# STDERR:
-#   Mapped command's error output. Mapping error output.
-# Status:
-#   0  - Call was successful.
-#   .. - Call failed with it's error status
-#   POSIX_ADAPTER__STATUS__INVALID_PARAMETERS - Invalid parameter configuration.
-#   POSIX_ADAPTER__STATUS__INCOMPATIBLE_CALL - No compatible call style was found.
-#==============================================================================
-posix_adapter__wc() {
+TOOL_NAME='posix_adapter__wc'
+
+_print_help() {
+  >&2 echo '=============================================================================='
+  >&2 echo ''
+  >&2 echo '  posix_adapter__wc --help'
+  >&2 echo '  posix_adapter__wc [--chars] [--lines] [--words] [<path>]'
+  >&2 echo ''
+  >&2 echo '------------------------------------------------------------------------------'
+  >&2 echo ' Execution mapping function for the "wc" command line tool with a'
+  >&2 echo ' uniform interface.'
+  >&2 echo '------------------------------------------------------------------------------'
+  >&2 echo ' Globals:'
+  >&2 echo '   None'
+  >&2 echo ' Options:'
+  >&2 echo '   --help - Prints out the help message and exits.'
+  >&2 echo '   --chars - Use the wc compatible -c flag.'
+  >&2 echo '   --lines - Use the wc compatible -l flag.'
+  >&2 echo '   --words - Use the wc compatible -w flag.'
+  >&2 echo ' Arguments:'
+  >&2 echo '   [1] [path] - Optional file path.'
+  >&2 echo ' STDIN:'
+  >&2 echo '   Input passed to the mapped command.'
+  >&2 echo '------------------------------------------------------------------------------'
+  >&2 echo ' Output variables:'
+  >&2 echo '   None'
+  >&2 echo ' STDOUT:'
+  >&2 echo '   Output of the mapped command.'
+  >&2 echo ' STDERR:'
+  >&2 echo '   Error output of the mapped command.'
+  >&2 echo ' Status:'
+  >&2 echo '   0  - Call was successful.'
+  >&2 echo '   .. - Call failed with its error status.'
+  >&2 echo '   98 - Invalid parameter configuration.'
+  >&2 echo '   99 - No compatible call style was found.'
+  >&2 echo '=============================================================================='
+}
+
+_posix_adapter__wc() {
   posix_adapter__flag__chars='0'
   posix_adapter__flag__lines='0'
   posix_adapter__flag__words='0'
@@ -64,14 +71,12 @@ posix_adapter__wc() {
         shift
         ;;
       --[!-]*)
-        posix_adapter__report_invalid_parameters \
-          'posix_adapter__wc' \
+        _report_invalid_parameter \
           "Unexpected option '${1}'!" \
-          'You can only use --chars, --lines or --words.'
+          'You can only use the available options.'
         ;;
       -[!-]*)
-        posix_adapter__report_invalid_parameters \
-          'posix_adapter__wc' \
+        _report_invalid_parameter \
           "Invalid single dashed option '${1}'!" \
           "posix_adapter only uses double dashed options like '--option'."
         ;;
@@ -82,8 +87,7 @@ posix_adapter__wc() {
           posix_adapter__value__path="$1"
           shift
         else
-          posix_adapter__report_invalid_parameters \
-            'posix_adapter__wc' \
+          _report_invalid_parameter \
             'Unexpected parameter!' \
             "Parameter '${1}' is unexpected!"
         fi
@@ -102,15 +106,14 @@ posix_adapter__wc() {
   posix_adapter__decision="${posix_adapter__decision}${posix_adapter__flag__words}"
   posix_adapter__decision="${posix_adapter__decision}${posix_adapter__flag__path}"
 
-  case "$POSIX_ADAPTER__RUNTIME__OS" in
-
-    "$POSIX_ADAPTER__CONSTANT__OS__LINUX")
+  case "$(uname -s)" in
+    Linux)
       _posix_adapter__wc__common \
         "$posix_adapter__decision" \
         "$posix_adapter__value__path"
       ;;
 
-    "$POSIX_ADAPTER__CONSTANT__OS__MACOS")
+    Darwin)
       # This if else construction is needed because POSIX does not have the
       # pipefail feature.
       if posix_adapter__result="$( \
@@ -129,7 +132,9 @@ posix_adapter__wc() {
       ;;
 
     *)
-      posix_adapter__report_incompatible_call 'posix_adapter__wc'
+      _report_invalid_parameter_combination \
+        "Unsupported platform '$(uname -s)'!" \
+        'The tool is only implemented for Linux and Darwin so far.'
       ;;
   esac
 }
@@ -259,10 +264,77 @@ _posix_adapter__wc__common() {
 
       ;;
     *)
-      posix_adapter__report_invalid_parameters \
-        'posix_adapter__wc' \
+      _report_invalid_parameter_combination \
         'Unexpected parameter combination!' \
-        'You can only have either --chars, --lines or --words'
+        'You can only use the available options.'
       ;;
   esac
 }
+
+#==============================================================================
+# Invalid parameter error reporting helper function.
+#------------------------------------------------------------------------------
+# Globals:
+#   TOOL_NAME
+# Options:
+#   None
+# Arguments:
+#   [1] reason - Reason of the error.
+#   [2] details - More details about the error.
+# STDIN:
+#   None
+#------------------------------------------------------------------------------
+# Output variables:
+#   None
+# STDOUT:
+#   None
+# STDERR:
+#   Reported error.
+# Status:
+#   98  - The function will terminate the execution.
+#==============================================================================
+_report_invalid_parameter() {
+  reason="$1"
+  details="$2"
+  >&2 echo "ERROR | ${TOOL_NAME} | reason  | ${reason}"
+  >&2 echo "ERROR | ${TOOL_NAME} | details | ${details}"
+  _print_help
+  exit 98
+}
+
+#==============================================================================
+# Invalid parameter combination error reporting helper function.
+#------------------------------------------------------------------------------
+# Globals:
+#   TOOL_NAME
+# Options:
+#   None
+# Arguments:
+#   [1] reason - Reason of the error.
+#   [2] details - More details about the error.
+# STDIN:
+#   None
+#------------------------------------------------------------------------------
+# Output variables:
+#   None
+# STDOUT:
+#   None
+# STDERR:
+#   Reported error.
+# Status:
+#   99  - The function will terminate the execution.
+#==============================================================================
+_report_invalid_parameter_combination() {
+  reason="$1"
+  details="$2"
+  >&2 echo "ERROR | ${TOOL_NAME} | reason  | ${reason}"
+  >&2 echo "ERROR | ${TOOL_NAME} | details | ${details}"
+  _print_help
+  exit 99
+}
+
+#==============================================================================
+# ENTRY POINT
+#==============================================================================
+
+_posix_adapter__wc "$@"
