Bringing the function based interface back for speed

diff --git a/src/posix_adapter__basename b/src/posix_adapter__basename
--- a/src/posix_adapter__basename
+++ b/src/posix_adapter__basename
@@ -1,32 +1,30 @@
 #!/bin/sh
 #==============================================================================
-#      _ _
-#   __| (_)_ __ _ __   __ _ _ __ ___   ___
-#  / _` | | '__| '_ \ / _` | '_ ` _ \ / _ \
-# | (_| | | |  | | | | (_| | | | | | |  __/
-#  \__,_|_|_|  |_| |_|\__,_|_| |_| |_|\___|
+#   _
+#  | |__   __ _ ___  ___ _ __   __ _ _ __ ___   ___
+#  | '_ \ / _` / __|/ _ \ '_ \ / _` | '_ ` _ \ / _ \
+#  | |_) | (_| \__ \  __/ | | | (_| | | | | | |  __/
+#  |_.__/ \__,_|___/\___|_| |_|\__,_|_| |_| |_|\___|
 #==============================================================================
-# TOOL: DIRNAME
+# TOOL: BASENAME
 #==============================================================================
 
-TOOL_NAME='posix_adapter__dirname'
-
-_print_help() {
+_posix_adapter__basename__help() {
   >&2 echo '=============================================================================='
   >&2 echo ''
-  >&2 echo '  posix_adapter__dirname --help'
-  >&2 echo '  posix_adapter__dirname <path>'
+  >&2 echo '  posix_adapter__basename --help'
+  >&2 echo '  posix_adapter__basename <path>'
   >&2 echo ''
   >&2 echo '------------------------------------------------------------------------------'
-  >&2 echo ' Execution mapping function for the "dirname" command line tool with a uniform'
-  >&2 echo ' interface.'
+  >&2 echo ' Execution mapping function for the "basename" command line tool with a'
+  >&2 echo ' uniform interface.'
   >&2 echo '------------------------------------------------------------------------------'
   >&2 echo ' Globals:'
   >&2 echo '   None'
   >&2 echo ' Options:'
-  >&2 echo '   --help - Prints out the help message and exits.'
+  >&2 echo '   None'
   >&2 echo ' Arguments:'
-  >&2 echo '   [1] path - Path from which the directory name should be separated.'
+  >&2 echo '   [1] path - Path from which the basename should be separated.'
   >&2 echo ' STDIN:'
   >&2 echo '   Standard input can be used to pass a path.'
   >&2 echo '------------------------------------------------------------------------------'
@@ -44,34 +42,38 @@ _print_help() {
   >&2 echo '=============================================================================='
 }
 
-_posix_adapter__dirname() {
+posix_adapter__basename() {
   if [ "$#" -eq 0 ]
   then
-    # dirname does not support the standard input by it's own, so helping it
+    # basename does not support the standard input by it's own, so helping it
     # out with xargs..
-    xargs dirname
+    xargs basename
   else
     if [ "$#" -gt 1 ]
     then
-      _report_invalid_parameter \
+      _posix_adapter__basename__report_invalid_parameter \
         'Unexpected parameter count!' \
         "Only 1 parameter is expected, got ${#}!"
     fi
 
     case "$1" in
+      --help)
+        _posix_adapter__basename__help
+        exit 0
+        ;;
       --[!-]*)
-        _report_invalid_parameter \
+        _posix_adapter__basename__report_invalid_parameter \
           "Unexpected option '${1}'!" \
           'This function does not take options.'
         ;;
       -[!-]*)
-        _report_invalid_parameter \
+        _posix_adapter__basename__report_invalid_parameter \
           "Invalid single dashed option '${1}'!" \
           "posix_adapter only uses double dashed options like '--option'."
         ;;
     esac
 
-    dirname "$1"
+    basename "$1"
   fi
 }
 
@@ -79,7 +81,7 @@ _posix_adapter__dirname() {
 # Invalid parameter error reporting helper function.
 #------------------------------------------------------------------------------
 # Globals:
-#   TOOL_NAME
+#   None
 # Options:
 #   None
 # Arguments:
@@ -97,12 +99,12 @@ _posix_adapter__dirname() {
 # Status:
 #   98  - The function will terminate the execution.
 #==============================================================================
-_report_invalid_parameter() {
+_posix_adapter__basename__report_invalid_parameter() {
   reason="$1"
   details="$2"
-  >&2 echo "ERROR | ${TOOL_NAME} | reason  | ${reason}"
-  >&2 echo "ERROR | ${TOOL_NAME} | details | ${details}"
-  _print_help
+  >&2 echo "ERROR | posix_adapter__basename | reason  | ${reason}"
+  >&2 echo "ERROR | posix_adapter__basename | details | ${details}"
+  _posix_adapter__basename__help
   exit 98
 }
 
@@ -110,7 +112,7 @@ _report_invalid_parameter() {
 # Incompatible call error reporting helper function.
 #------------------------------------------------------------------------------
 # Globals:
-#   TOOL_NAME
+#   None
 # Options:
 #   None
 # Arguments:
@@ -128,12 +130,12 @@ _report_invalid_parameter() {
 # Status:
 #   99  - The function will terminate the execution.
 #==============================================================================
-_report_incompatible_call() {
-  reason="$1"
-  details="$2"
-  >&2 echo "ERROR | ${TOOL_NAME} | reason  | ${reason}"
-  >&2 echo "ERROR | ${TOOL_NAME} | details | ${details}"
-  _print_help
+_posix_adapter__basename__report_incompatible_call() {
+  ___reason="$1"
+  ___details="$2"
+  >&2 echo "ERROR | posix_adapter__basename | reason  | ${___reason}"
+  >&2 echo "ERROR | posix_adapter__basename | details | ${___details}"
+  _posix_adapter__basename__help
   exit 99
 }
 
@@ -141,4 +143,9 @@ _report_incompatible_call() {
 # ENTRY POINT
 #==============================================================================
 
-_posix_adapter__dirname "$@"
+# If the script is called directly, call the internal function.
+case $0 in
+  *posix_adapter__basename)
+    posix_adapter__basename "$@"
+    ;;
+esac
diff --git a/src/posix_adapter__cat b/src/posix_adapter__cat
--- a/src/posix_adapter__cat
+++ b/src/posix_adapter__cat
@@ -1,24 +1,22 @@
 #!/bin/sh
 #==============================================================================
-#   _                   _
-#  | |_ ___  _   _  ___| |__
-#  | __/ _ \| | | |/ __| '_ \
-#  | || (_) | |_| | (__| | | |
-#   \__\___/ \__,_|\___|_| |_|
+#            _
+#   ___ __ _| |_
+#  / __/ _` | __|
+# | (_| (_| | |_
+#  \___\__,_|\__|
 #==============================================================================
-# TOOL: TOUCH
+# TOOL: CAT
 #==============================================================================
 
-TOOL_NAME='posix_adapter__touch'
-
-_print_help() {
+_posix_adapter__cat__print_help() {
   >&2 echo '=============================================================================='
   >&2 echo ''
-  >&2 echo '  posix_adapter__touch --help'
-  >&2 echo '  posix_adapter__touch <path>'
+  >&2 echo '  posix_adapter__cat --help'
+  >&2 echo '  posix_adapter__cat [path]'
   >&2 echo ''
   >&2 echo '------------------------------------------------------------------------------'
-  >&2 echo ' Execution mapping function for the "touch" command line tool with a uniform'
+  >&2 echo ' Execution mapping function for the "cat" command line tool with a uniform'
   >&2 echo ' interface.'
   >&2 echo '------------------------------------------------------------------------------'
   >&2 echo ' Globals:'
@@ -26,7 +24,7 @@ _print_help() {
   >&2 echo ' Options:'
   >&2 echo '   --help - Prints out the help message and exits.'
   >&2 echo ' Arguments:'
-  >&2 echo '   [1] path - Path that needs to be touched.'
+  >&2 echo '   [1] [path] - Path thats content should be printed out.'
   >&2 echo ' STDIN:'
   >&2 echo '   Input passed to the mapped command.'
   >&2 echo '------------------------------------------------------------------------------'
@@ -44,31 +42,32 @@ _print_help() {
   >&2 echo '=============================================================================='
 }
 
-_posix_adapter__touch() {
+posix_adapter__cat() {
   if [ "$#" -eq 0 ]
   then
-    _report_invalid_parameter \
-      'Missing <path> parameter' \
-      'This function does not take options.'
+    cat
   elif [ "$#" -eq 1 ]
   then
     case "$1" in
+      --help)
+        _posix_adapter__cat__help
+        exit 0
+        ;;
     --[!-]*)
-        _report_invalid_parameter \
+        _posix_adapter__cat__report_invalid_parameter \
           "Unexpected option '${1}'!" \
           'This function does not take options.'
         ;;
     -[!-]*)
-        _report_invalid_parameter \
+        _posix_adapter__cat__report_invalid_parameter \
           "Invalid single dashed option '${1}'!" \
           "posix_adapter only uses double dashed options like '--option'."
         ;;
     esac
 
-    touch "$1"
-
+    cat "$1"
   else
-    _report_invalid_parameter \
+    _posix_adapter__cat__report_invalid_parameter \
       'Unexpected parameter count!' \
       "Only 1 parameter is expected, got ${#}!"
   fi
@@ -78,7 +77,7 @@ _posix_adapter__touch() {
 # Invalid parameter error reporting helper function.
 #------------------------------------------------------------------------------
 # Globals:
-#   TOOL_NAME
+#   None
 # Options:
 #   None
 # Arguments:
@@ -96,12 +95,12 @@ _posix_adapter__touch() {
 # Status:
 #   98  - The function will terminate the execution.
 #==============================================================================
-_report_invalid_parameter() {
+_posix_adapter__cat__report_invalid_parameter() {
   reason="$1"
   details="$2"
-  >&2 echo "ERROR | ${TOOL_NAME} | reason  | ${reason}"
-  >&2 echo "ERROR | ${TOOL_NAME} | details | ${details}"
-  _print_help
+  >&2 echo "ERROR | posix_adapter__cat | reason  | ${reason}"
+  >&2 echo "ERROR | posix_adapter__cat | details | ${details}"
+  _posix_adapter__cat__print_help
   exit 98
 }
 
@@ -109,7 +108,7 @@ _report_invalid_parameter() {
 # Incompatible call error reporting helper function.
 #------------------------------------------------------------------------------
 # Globals:
-#   TOOL_NAME
+#   None
 # Options:
 #   None
 # Arguments:
@@ -127,12 +126,12 @@ _report_invalid_parameter() {
 # Status:
 #   99  - The function will terminate the execution.
 #==============================================================================
-_report_incompatible_call() {
+_posix_adapter__cat__report_incompatible_call() {
   reason="$1"
   details="$2"
-  >&2 echo "ERROR | ${TOOL_NAME} | reason  | ${reason}"
-  >&2 echo "ERROR | ${TOOL_NAME} | details | ${details}"
-  _print_help
+  >&2 echo "ERROR | posix_adapter__cat | reason  | ${reason}"
+  >&2 echo "ERROR | posix_adapter__cat | details | ${details}"
+  _posix_adapter__cat__print_help
   exit 99
 }
 
@@ -140,4 +139,9 @@ _report_incompatible_call() {
 # ENTRY POINT
 #==============================================================================
 
-_posix_adapter__touch "$@"
+# If the script is called directly, call the internal function.
+case $0 in
+  *posix_adapter__cat)
+    posix_adapter__cat "$@"
+    ;;
+esac
diff --git a/src/posix_adapter__cut b/src/posix_adapter__cut
--- a/src/posix_adapter__cut
+++ b/src/posix_adapter__cut
@@ -1,34 +1,34 @@
 #!/bin/sh
 #==============================================================================
-#                  _
-#   ___  ___  _ __| |_
-#  / __|/ _ \| '__| __|
-#  \__ \ (_) | |  | |_
-#  |___/\___/|_|   \__|
+#             _
+#   ___ _   _| |_
+#  / __| | | | __|
+# | (__| |_| | |_
+#  \___|\__,_|\__|
 #==============================================================================
-# TOOL: SORT
+# TOOL: CUT
 #==============================================================================
 
-TOOL_NAME='posix_adapter__sort'
-
-_print_help() {
+_posix_adapter__cut__print_help() {
   >&2 echo '=============================================================================='
   >&2 echo ''
-  >&2 echo '  posix_adapter__sort --help'
-  >&2 echo '  posix_adapter__sort [--zero-terminated] [--dictionary-order] [<path>]'
+  >&2 echo '  posix_adapter__cut --help'
+  >&2 echo '  posix_adapter__cut --delimiter <delimiter_char> --fields <index_def> [file]'
+  >&2 echo '  posix_adapter__cut --characters <index_def> [file]'
   >&2 echo ''
   >&2 echo '------------------------------------------------------------------------------'
-  >&2 echo ' Execution mapping function for the "sed" command line tool with a'
-  >&2 echo ' uniform interface.'
+  >&2 echo ' Execution mapping function for the "cut" command line tool with a uniform'
+  >&2 echo ' interface.'
   >&2 echo '------------------------------------------------------------------------------'
   >&2 echo ' Globals:'
   >&2 echo '   None'
   >&2 echo ' Options:'
   >&2 echo '   --help - Prints out the help message and exits.'
-  >&2 echo '   --zero-terminated - Use the sort compatible -z flag.'
-  >&2 echo '   --dictionary-order - Use the sort compatible -d flag.'
+  >&2 echo '   --delimiter <delimiter_char> - cut compatible delimiter definition'
+  >&2 echo '   --fields <index_definition> - cut compatible fields definition'
+  >&2 echo '   --characters <index_definition> - cut compatible characters definition'
   >&2 echo ' Arguments:'
-  >&2 echo '   [1] [path] - Optional file path.'
+  >&2 echo '   [1] [file] - File that should be processed.'
   >&2 echo ' STDIN:'
   >&2 echo '   Input passed to the mapped command.'
   >&2 echo '------------------------------------------------------------------------------'
@@ -46,42 +46,59 @@ _print_help() {
   >&2 echo '=============================================================================='
 }
 
-_posix_adapter__sort() {
-  posix_adapter__flag__zero_terminated='0'
-  posix_adapter__flag__dictionary_order='0'
+posix_adapter__cut() {
+  posix_adapter__flag__delimiter='0'
+  posix_adapter__value__delimiter=''
 
-  posix_adapter__flag__path='0'
-  posix_adapter__value__path=''
+  posix_adapter__flag__fields='0'
+  posix_adapter__value__fields=''
+
+  posix_adapter__flag__characters='0'
+  posix_adapter__value__characters=''
+
+  posix_adapter__flag__file='0'
+  posix_adapter__value__file=''
 
   while [ "$#" -gt '0' ]
   do
     case "$1" in
-      --zero-terminated)
-        posix_adapter__flag__zero_terminated='1'
+      --delimiter)
+        posix_adapter__flag__delimiter='1'
+        posix_adapter__value__delimiter="$2"
+        shift
         shift
         ;;
-      --dictionary-order)
-        posix_adapter__flag__dictionary_order='1'
+      --fields)
+        posix_adapter__flag__fields='1'
+        posix_adapter__value__fields="$2"
+        shift
+        shift
+        ;;
+      --characters)
+        posix_adapter__flag__characters='1'
+        posix_adapter__value__characters="$2"
+        shift
         shift
         ;;
       --[!-]*)
-        _report_invalid_parameter \
+        _posix_adapter__cut__report_invalid_parameter \
           "Unexpected option '${1}'!" \
           'You can only use the available options.'
         ;;
       -[!-]*)
-        _report_invalid_parameter \
+        _posix_adapter__cut__report_invalid_parameter \
           "Invalid single dashed option '${1}'!" \
           "posix_adapter only uses double dashed options like '--option'."
         ;;
       *)
-        if [ "$posix_adapter__flag__path" -eq '0' ]
+        # Only one file is needed for now.
+        if [ "$posix_adapter__flag__file" -eq '0' ]
         then
-          posix_adapter__flag__path='1'
-          posix_adapter__value__path="$1"
+          posix_adapter__flag__file='1'
+          posix_adapter__value__file="$1"
           shift
         else
-          _report_invalid_parameter \
+          _posix_adapter__cut__report_invalid_parameter \
             'Unexpected parameter!' \
             "Parameter '${1}' is unexpected!"
         fi
@@ -90,17 +107,22 @@ _posix_adapter__sort() {
   done
 
   # Assembling the decision string.
-  # ,----- zero_terminated
-  # |,---- dictionary_order
-  # ||,--- path
-  # 000
-  posix_adapter__decision="${posix_adapter__flag__zero_terminated}"
-  posix_adapter__decision="${posix_adapter__decision}${posix_adapter__flag__dictionary_order}"
-  posix_adapter__decision="${posix_adapter__decision}${posix_adapter__flag__path}"
+  # ,----- delimiter
+  # |,---- fields
+  # ||,--- characters
+  # |||,-- file
+  # 0000
+  posix_adapter__decision="${posix_adapter__flag__delimiter}"
+  posix_adapter__decision="${posix_adapter__decision}${posix_adapter__flag__fields}"
+  posix_adapter__decision="${posix_adapter__decision}${posix_adapter__flag__characters}"
+  posix_adapter__decision="${posix_adapter__decision}${posix_adapter__flag__file}"
 
-  _posix_adapter__sort__common \
+  _posix_adapter__cut__common \
     "$posix_adapter__decision" \
-    "$posix_adapter__value__path"
+    "$posix_adapter__value__delimiter" \
+    "$posix_adapter__value__fields" \
+    "$posix_adapter__value__characters" \
+    "$posix_adapter__value__file"
 }
 
 #==============================================================================
@@ -112,7 +134,11 @@ _posix_adapter__sort() {
 #   None
 # Arguments:
 #   [1] decision_string - String that decodes the optional parameter presence.
-#   [2] value_path - Value for the positional path argument.
+#   [2] value_delimiter -  Value passed with the delimiter flag.
+#   [3] value_fields - Value passed with the fields flag.
+#   [4] value_characters - Value passed with the characters flag.
+#   [5] value_file - File path input that should be processed, otherwise the
+#       standard input will be read.
 # STDIN:
 #   Input passed to the mapped command.
 #------------------------------------------------------------------------------
@@ -126,93 +152,64 @@ _posix_adapter__sort() {
 #   0  - Call succeeded.
 #   .. - Call failed with it's error status
 #==============================================================================
-_posix_adapter__sort__common() {
+_posix_adapter__cut__common() {
   posix_adapter__decision_string="$1"
-  posix_adapter__value__path="$2"
+  posix_adapter__value__delimiter="$2"
+  posix_adapter__value__fields="$3"
+  posix_adapter__value__characters="$4"
+  posix_adapter__value__file="$5"
 
   case "$posix_adapter__decision_string" in
-  # ,----- zero_terminated
-  # |,---- dictionary_order
-  # ||,--- path
-    000)
-      sort \
-        \
-        \
-        \
-
-      ;;
-  # ,----- zero_terminated
-  # |,---- dictionary_order
-  # ||,--- path
-    001)
-      sort \
-        \
-        \
-        "$posix_adapter__value__path" \
-
-      ;;
-  # ,----- zero_terminated
-  # |,---- dictionary_order
-  # ||,--- path
-    010)
-      sort \
-        \
-        --dictionary-order \
-        \
-
-      ;;
-  # ,----- zero_terminated
-  # |,---- dictionary_order
-  # ||,--- path
-    011)
-      sort \
-        \
-        --dictionary-order \
-        "$posix_adapter__value__path" \
-
-      ;;
-  # ,----- zero_terminated
-  # |,---- dictionary_order
-  # ||,--- path
-    100)
-      sort \
-        --zero-terminated \
+  # ,----- delimiter
+  # |,---- fields
+  # ||,--- characters
+  # |||,-- file
+    1100)
+      cut \
+        -d "$posix_adapter__value__delimiter" \
+        -f "$posix_adapter__value__fields" \
         \
         \
 
       ;;
-  # ,----- zero_terminated
-  # |,---- dictionary_order
-  # ||,--- path
-    101)
-      sort \
-        --zero-terminated \
+  # ,----- delimiter
+  # |,---- fields
+  # ||,--- characters
+  # |||,-- file
+    0010)
+      cut \
         \
-        "$posix_adapter__value__path" \
-
-      ;;
-  # ,----- zero_terminated
-  # |,---- dictionary_order
-  # ||,--- path
-    110)
-      sort \
-        --zero-terminated \
-        --dictionary-order \
+        \
+        -c "$posix_adapter__value__characters" \
         \
 
       ;;
-  # ,----- zero_terminated
-  # |,---- dictionary_order
-  # ||,--- path
-    111)
-      sort \
-        --zero-terminated \
-        --dictionary-order \
-        "$posix_adapter__value__path" \
+  # ,----- delimiter
+  # |,---- fields
+  # ||,--- characters
+  # |||,-- file
+    1101)
+      cut \
+        -d "$posix_adapter__value__delimiter" \
+        -f "$posix_adapter__value__fields" \
+        \
+        "$posix_adapter__value__file" \
+
+      ;;
+  # ,----- delimiter
+  # |,---- fields
+  # ||,--- characters
+  # |||,-- file
+    0011)
+      cut \
+        \
+        \
+        -c "$posix_adapter__value__characters" \
+        "$posix_adapter__value__file" \
 
       ;;
     *)
-      _report_incompatible_call \
+      _posix_adapter__cut__report_incompatible_call \
         'Unexpected parameter combination!' \
         'You can only use the available options.'
       ;;
@@ -223,7 +220,7 @@ _posix_adapter__sort__common() {
 # Invalid parameter error reporting helper function.
 #------------------------------------------------------------------------------
 # Globals:
-#   TOOL_NAME
+#   None
 # Options:
 #   None
 # Arguments:
@@ -241,12 +238,12 @@ _posix_adapter__sort__common() {
 # Status:
 #   98  - The function will terminate the execution.
 #==============================================================================
-_report_invalid_parameter() {
+_posix_adapter__cut__report_invalid_parameter() {
   reason="$1"
   details="$2"
-  >&2 echo "ERROR | ${TOOL_NAME} | reason  | ${reason}"
-  >&2 echo "ERROR | ${TOOL_NAME} | details | ${details}"
-  _print_help
+  >&2 echo "ERROR | posix_adapter__cut | reason  | ${reason}"
+  >&2 echo "ERROR | posix_adapter__cut | details | ${details}"
+  _posix_adapter__cut__print_help
   exit 98
 }
 
@@ -254,7 +251,7 @@ _report_invalid_parameter() {
 # Incompatible call error reporting helper function.
 #------------------------------------------------------------------------------
 # Globals:
-#   TOOL_NAME
+#   None
 # Options:
 #   None
 # Arguments:
@@ -272,12 +269,12 @@ _report_invalid_parameter() {
 # Status:
 #   99  - The function will terminate the execution.
 #==============================================================================
-_report_incompatible_call() {
+_posix_adapter__cut__report_incompatible_call() {
   reason="$1"
   details="$2"
-  >&2 echo "ERROR | ${TOOL_NAME} | reason  | ${reason}"
-  >&2 echo "ERROR | ${TOOL_NAME} | details | ${details}"
-  _print_help
+  >&2 echo "ERROR | posix_adapter__cut | reason  | ${reason}"
+  >&2 echo "ERROR | posix_adapter__cut | details | ${details}"
+  _posix_adapter__cut__print_help
   exit 99
 }
 
@@ -285,4 +282,9 @@ _report_incompatible_call() {
 # ENTRY POINT
 #==============================================================================
 
-_posix_adapter__sort "$@"
+# If the script is called directly, call the internal function.
+case $0 in
+  *posix_adapter__cut)
+    posix_adapter__cut "$@"
+    ;;
+esac
diff --git a/src/posix_adapter__date b/src/posix_adapter__date
--- a/src/posix_adapter__date
+++ b/src/posix_adapter__date
@@ -1,33 +1,30 @@
 #!/bin/sh
 #==============================================================================
-#              _       _    __
-#   _ __  _ __(_)_ __ | |_ / _|
-#  | '_ \| '__| | '_ \| __| |_
-#  | |_) | |  | | | | | |_|  _|
-#  | .__/|_|  |_|_| |_|\__|_|
-#==|_|=========================================================================
-# TOOL: PRINTF
+#      _       _
+#   __| | __ _| |_ ___
+#  / _` |/ _` | __/ _ \
+# | (_| | (_| | ||  __/
+#  \__,_|\__,_|\__\___|
+#==============================================================================
+# TOOL: DATE
 #==============================================================================
 
-TOOL_NAME='posix_adapter__printf'
-
-_print_help() {
+_posix_adapter__date__print_help() {
   >&2 echo '=============================================================================='
   >&2 echo ''
-  >&2 echo '  posix_adapter__printf --help'
-  >&2 echo '  posix_adapter__printf <printf_specification>..'
+  >&2 echo '  posix_adapter__date --help'
+  >&2 echo '  posix_adapter__date <format_string>'
   >&2 echo ''
   >&2 echo '------------------------------------------------------------------------------'
-  >&2 echo ' Execution mapping function for the "printf" command line tool with a uniform'
-  >&2 echo ' interface. This is the only command mapping besides tput that is only a proxy'
-  >&2 echo ' because of the nature of printf.'
+  >&2 echo ' Execution mapping function for the "date" command line tool with a uniform'
+  >&2 echo ' interface.'
   >&2 echo '------------------------------------------------------------------------------'
   >&2 echo ' Globals:'
   >&2 echo '   None'
   >&2 echo ' Options:'
   >&2 echo '   --help - Prints out the help message and exits.'
   >&2 echo ' Arguments:'
-  >&2 echo '   [..] specification - printf compatible specification.'
+  >&2 echo '   [1] format_string - Format string the date should be generated from.'
   >&2 echo ' STDIN:'
   >&2 echo '   Input passed to the mapped command.'
   >&2 echo '------------------------------------------------------------------------------'
@@ -45,23 +42,40 @@ _print_help() {
   >&2 echo '=============================================================================='
 }
 
-_posix_adapter__printf() {
-  if [ "$1" = '--help' ]
+posix_adapter__date() {
+  if [ "$#" -eq 0 ]
   then
-    _print_help
-    exit 0
+    _posix_adapter__date__report_invalid_parameter \
+      'Missing parameter!' \
+      'A singular <format> parameter was expected!'
+  elif [ "$#" -ne 1 ]
+  then
+    _posix_adapter__date__report_invalid_parameter \
+      'Unexpected parameter count!' \
+      "Only 1 parameter is expected, got ${#}!"
   fi
 
-  # We are proxying all the parameters here, hence ignoring the warning.
-  # shellcheck disable=SC2059
-  printf "$@"
+  case "$1" in
+    --[!-]*)
+      _posix_adapter__date__report_invalid_parameter \
+        "Unexpected option '${1}'!" \
+        'This function does not take options.'
+      ;;
+    -[!-]*)
+      _posix_adapter__date__report_invalid_parameter \
+        "Invalid single dashed option '${1}'!" \
+        "posix_adapter only uses double dashed options like '--option'."
+      ;;
+  esac
+
+  date "$1"
 }
 
 #==============================================================================
 # Invalid parameter error reporting helper function.
 #------------------------------------------------------------------------------
 # Globals:
-#   TOOL_NAME
+#   None
 # Options:
 #   None
 # Arguments:
@@ -79,12 +93,12 @@ _posix_adapter__printf() {
 # Status:
 #   98  - The function will terminate the execution.
 #==============================================================================
-_report_invalid_parameter() {
+_posix_adapter__date__report_invalid_parameter() {
   reason="$1"
   details="$2"
-  >&2 echo "ERROR | ${TOOL_NAME} | reason  | ${reason}"
-  >&2 echo "ERROR | ${TOOL_NAME} | details | ${details}"
-  _print_help
+  >&2 echo "ERROR | posix_adapter__date | reason  | ${reason}"
+  >&2 echo "ERROR | posix_adapter__date | details | ${details}"
+  _posix_adapter__date__print_help
   exit 98
 }
 
@@ -92,7 +106,7 @@ _report_invalid_parameter() {
 # Incompatible call error reporting helper function.
 #------------------------------------------------------------------------------
 # Globals:
-#   TOOL_NAME
+#   None
 # Options:
 #   None
 # Arguments:
@@ -110,12 +124,12 @@ _report_invalid_parameter() {
 # Status:
 #   99  - The function will terminate the execution.
 #==============================================================================
-_report_incompatible_call() {
+_posix_adapter__date__report_incompatible_call() {
   reason="$1"
   details="$2"
-  >&2 echo "ERROR | ${TOOL_NAME} | reason  | ${reason}"
-  >&2 echo "ERROR | ${TOOL_NAME} | details | ${details}"
-  _print_help
+  >&2 echo "ERROR | posix_adapter__date | reason  | ${reason}"
+  >&2 echo "ERROR | posix_adapter__date | details | ${details}"
+  _posix_adapter__date__print_help
   exit 99
 }
 
@@ -123,4 +137,9 @@ _report_incompatible_call() {
 # ENTRY POINT
 #==============================================================================
 
-_posix_adapter__printf "$@"
+# If the script is called directly, call the internal function.
+case $0 in
+  *posix_adapter__date)
+    posix_adapter__date "$@"
+    ;;
+esac
diff --git a/src/posix_adapter__dirname b/src/posix_adapter__dirname
--- a/src/posix_adapter__dirname
+++ b/src/posix_adapter__dirname
@@ -1,39 +1,32 @@
 #!/bin/sh
 #==============================================================================
-#   _               _
-#  | |_ _ __  _   _| |_
-#  | __| '_ \| | | | __|
-#  | |_| |_) | |_| | |_
-#   \__| .__/ \__,_|\__|
-#======|_|=====================================================================
-# TOOL: TPUT
+#      _ _
+#   __| (_)_ __ _ __   __ _ _ __ ___   ___
+#  / _` | | '__| '_ \ / _` | '_ ` _ \ / _ \
+# | (_| | | |  | | | | (_| | | | | | |  __/
+#  \__,_|_|_|  |_| |_|\__,_|_| |_| |_|\___|
+#==============================================================================
+# TOOL: DIRNAME
 #==============================================================================
 
-TOOL_NAME='posix_adapter__tput'
-
-_print_help() {
+_posix_adapter__dirname__print_help() {
   >&2 echo '=============================================================================='
   >&2 echo ''
-  >&2 echo '  posix_adapter__tput --help'
-  >&2 echo '  posix_adapter__tput --is-available'
-  >&2 echo '  posix_adapter__tput <tput_specification>..'
+  >&2 echo '  posix_adapter__dirname --help'
+  >&2 echo '  posix_adapter__dirname <path>'
   >&2 echo ''
   >&2 echo '------------------------------------------------------------------------------'
-  >&2 echo ' Execution mapping function for the "tput" command line tool. This is the only'
-  >&2 echo ' command mapping besides printf that is only a proxy because of the nature of'
-  >&2 echo ' tput. It also performs a fail-safe step and supresses not supported escape'
-  >&2 echo ' sequences by returnin an empty string in case of error.'
+  >&2 echo ' Execution mapping function for the "dirname" command line tool with a uniform'
+  >&2 echo ' interface.'
   >&2 echo '------------------------------------------------------------------------------'
   >&2 echo ' Globals:'
   >&2 echo '   None'
   >&2 echo ' Options:'
   >&2 echo '   --help - Prints out the help message and exits.'
-  >&2 echo '   --is-available - Runs a check if tput is actually available on the current'
-  >&2 echo '                    system and then exists with the status code.'
   >&2 echo ' Arguments:'
-  >&2 echo '   [..] specification - tput compatible specification.'
+  >&2 echo '   [1] path - Path from which the directory name should be separated.'
   >&2 echo ' STDIN:'
-  >&2 echo '   Input passed to the mapped command.'
+  >&2 echo '   Standard input can be used to pass a path.'
   >&2 echo '------------------------------------------------------------------------------'
   >&2 echo ' Output variables:'
   >&2 echo '   None'
@@ -42,30 +35,41 @@ _print_help() {
   >&2 echo ' STDERR:'
   >&2 echo '   Error output of the mapped command.'
   >&2 echo ' Status:'
-  >&2 echo '   0 - Normal execution output, or the success of the availability check.'
-  >&2 echo '   1 - Availability check failed.'
+  >&2 echo '   0  - Call was successful.'
+  >&2 echo '   .. - Call failed with its error status.'
+  >&2 echo '   98 - Invalid parameter configuration.'
+  >&2 echo '   99 - No compatible call style was found.'
   >&2 echo '=============================================================================='
 }
 
-_posix_adapter__tput() {
-  # This is a minimal non-fail-safe implementation for now..
-  if [ "$1" = '--is-available' ]
+posix_adapter__dirname() {
+  if [ "$#" -eq 0 ]
   then
-    if command -v tput >/dev/null && tput init >/dev/null 2>&1
+    # dirname does not support the standard input by it's own, so helping it
+    # out with xargs..
+    xargs dirname
+  else
+    if [ "$#" -gt 1 ]
     then
-      return 0
-    else
-      return 1
+      _posix_adapter__dirname__report_invalid_parameter \
+        'Unexpected parameter count!' \
+        "Only 1 parameter is expected, got ${#}!"
     fi
-  elif [ "$1" = '--help' ]
-  then
-    _print_help
-    exit 0
-  fi
 
-  if ! tput "$@" 2>/dev/null
-  then
-    printf '%s' ''
+    case "$1" in
+      --[!-]*)
+        _posix_adapter__dirname__report_invalid_parameter \
+          "Unexpected option '${1}'!" \
+          'This function does not take options.'
+        ;;
+      -[!-]*)
+        _posix_adapter__dirname__report_invalid_parameter \
+          "Invalid single dashed option '${1}'!" \
+          "posix_adapter only uses double dashed options like '--option'."
+        ;;
+    esac
+
+    dirname "$1"
   fi
 }
 
@@ -73,7 +77,7 @@ _posix_adapter__tput() {
 # Invalid parameter error reporting helper function.
 #------------------------------------------------------------------------------
 # Globals:
-#   TOOL_NAME
+#   None
 # Options:
 #   None
 # Arguments:
@@ -91,12 +95,12 @@ _posix_adapter__tput() {
 # Status:
 #   98  - The function will terminate the execution.
 #==============================================================================
-_report_invalid_parameter() {
+_posix_adapter__dirname__report_invalid_parameter() {
   reason="$1"
   details="$2"
-  >&2 echo "ERROR | ${TOOL_NAME} | reason  | ${reason}"
-  >&2 echo "ERROR | ${TOOL_NAME} | details | ${details}"
-  _print_help
+  >&2 echo "ERROR | posix_adapter__dirname | reason  | ${reason}"
+  >&2 echo "ERROR | posix_adapter__dirname | details | ${details}"
+  _posix_adapter__dirname__print_help
   exit 98
 }
 
@@ -104,7 +108,7 @@ _report_invalid_parameter() {
 # Incompatible call error reporting helper function.
 #------------------------------------------------------------------------------
 # Globals:
-#   TOOL_NAME
+#   None
 # Options:
 #   None
 # Arguments:
@@ -122,12 +126,12 @@ _report_invalid_parameter() {
 # Status:
 #   99  - The function will terminate the execution.
 #==============================================================================
-_report_incompatible_call() {
+_posix_adapter__dirname__report_incompatible_call() {
   reason="$1"
   details="$2"
-  >&2 echo "ERROR | ${TOOL_NAME} | reason  | ${reason}"
-  >&2 echo "ERROR | ${TOOL_NAME} | details | ${details}"
-  _print_help
+  >&2 echo "ERROR | posix_adapter__dirname | reason  | ${reason}"
+  >&2 echo "ERROR | posix_adapter__dirname | details | ${details}"
+  _posix_adapter__dirname__print_help
   exit 99
 }
 
@@ -135,4 +139,9 @@ _report_incompatible_call() {
 # ENTRY POINT
 #==============================================================================
 
-_posix_adapter__tput "$@"
+# If the script is called directly, call the internal function.
+case $0 in
+  *posix_adapter__dirname)
+    posix_adapter__dirname "$@"
+    ;;
+esac
diff --git a/src/posix_adapter__echo b/src/posix_adapter__echo
--- a/src/posix_adapter__echo
+++ b/src/posix_adapter__echo
@@ -1,35 +1,31 @@
 #!/bin/sh
 #==============================================================================
-#
-#   __       _     _
-#  / _| ___ | | __| |
-# | |_ / _ \| |/ _` |
-# |  _| (_) | | (_| |
-# |_|  \___/|_|\__,_|
+#            _
+#   ___  ___| |__   ___
+#  / _ \/ __| '_ \ / _ \
+# |  __/ (__| | | | (_) |
+#  \___|\___|_| |_|\___/
 #==============================================================================
-# TOOL: FOLD
+# TOOL: ECHO
 #==============================================================================
 
-TOOL_NAME='posix_adapter__fold'
-
-_print_help() {
+_posix_adapter__echo__print_help() {
   >&2 echo '=============================================================================='
   >&2 echo ''
-  >&2 echo '  posix_adapter__fold --help'
-  >&2 echo '  posix_adapter__fold [--spaces] --width <line_width>'
+  >&2 echo '  posix_adapter__echo --help'
+  >&2 echo '  posix_adapter__echo [--no-newline] <string>'
   >&2 echo ''
   >&2 echo '------------------------------------------------------------------------------'
-  >&2 echo ' Execution mapping function for the "fold" command line tool with a'
-  >&2 echo ' uniform interface.'
+  >&2 echo ' Execution mapping function for the "echo" command line tool with a uniform'
+  >&2 echo ' interface.'
   >&2 echo '------------------------------------------------------------------------------'
   >&2 echo ' Globals:'
   >&2 echo '   None'
   >&2 echo ' Options:'
   >&2 echo '   --help - Prints out the help message and exits.'
-  >&2 echo '   --spaces - Use the fold compatible -s flag to break at spaces'
-  >&2 echo '   --width <line_width> - Use the fold compatible -w flag.'
+  >&2 echo '   --no-newline - Flag that should prevent printing the trailing new line.'
   >&2 echo ' Arguments:'
-  >&2 echo '   None'
+  >&2 echo '   [1] string - String that should be printed.'
   >&2 echo ' STDIN:'
   >&2 echo '   Input passed to the mapped command.'
   >&2 echo '------------------------------------------------------------------------------'
@@ -47,57 +43,61 @@ _print_help() {
   >&2 echo '=============================================================================='
 }
 
-_posix_adapter__fold() {
-  posix_adapter__flag__spaces='0'
+posix_adapter__echo() {
+  posix_adapter__flag__no_newline='0'
 
-  posix_adapter__flag__width='0'
-  posix_adapter__value__width=''
+  posix_adapter__value__string=''
+
+  if [ "$#" -eq 0 ]
+  then
+    _posix_adapter__echo__report_invalid_parameter \
+      'Missing string parameter!' \
+      'A singular <string> parameter was expected!'
+  fi
 
   while [ "$#" -gt '0' ]
   do
     case "$1" in
-      --spaces)
-        posix_adapter__flag__spaces='1'
-        shift
-        ;;
-      --width)
-        posix_adapter__flag__width='1'
-        posix_adapter__value__width="$2"
-        shift
+      --no-newline)
+        posix_adapter__flag__no_newline='1'
         shift
         ;;
       --[!-]*)
-        _report_invalid_parameter \
+        _posix_adapter__echo__report_invalid_parameter \
           "Unexpected option '${1}'!" \
           'You can only use the available options.'
         ;;
       -[!-]*)
-        _report_invalid_parameter \
+        _posix_adapter__echo__report_invalid_parameter \
           "Invalid single dashed option '${1}'!" \
           "posix_adapter only uses double dashed options like '--option'."
         ;;
       *)
-        _report_invalid_parameter \
-          'Unexpected parameter!' \
-          "Parameter '${1}' is unexpected!"
+        posix_adapter__value__string="$1"
+        shift
+        if [ "$#" -gt '0' ]
+        then
+          _posix_adapter__echo__report_invalid_parameter \
+            'Unexpected parameter!' \
+            'Multiple separated strings passed only one is expected!'
+        fi
+        break
         ;;
     esac
   done
 
   # Assembling the decision string.
-  # ,----- spaces
-  # |,---- width
-  # 00
-  posix_adapter__decision="${posix_adapter__flag__spaces}"
-  posix_adapter__decision="${posix_adapter__decision}${posix_adapter__flag__width}"
+  # ,-- no_newline
+  # 0
+  posix_adapter__decision="${posix_adapter__flag__no_newline}"
 
-  _posix_adapter__fold__common \
+  _posix_adapter__echo__common \
     "$posix_adapter__decision" \
-    "$posix_adapter__value__width"
+    "$posix_adapter__value__string"
 }
 
 #==============================================================================
-# Common based call mapping function.
+# Common call mapping function.
 #------------------------------------------------------------------------------
 # Globals:
 #   None
@@ -105,7 +105,7 @@ _posix_adapter__fold() {
 #   None
 # Arguments:
 #   [1] decision_string - String that decodes the optional parameter presence.
-#   [2] value_width - Value for optional width parameter.
+#   [2] value_string -  String passed to the echo command.
 # STDIN:
 #   Input passed to the mapped command.
 #------------------------------------------------------------------------------
@@ -119,45 +119,21 @@ _posix_adapter__fold() {
 #   0  - Call succeeded.
 #   .. - Call failed with it's error status
 #==============================================================================
-_posix_adapter__fold__common() {
+_posix_adapter__echo__common() {
   posix_adapter__decision_string="$1"
-  posix_adapter__value__width="$2"
+  posix_adapter__value__string="$2"
 
   case "$posix_adapter__decision_string" in
-  # ,----- spaces
-  # |,---- width
-    00)
-      fold \
-        \
-        \
-
+  # ,-- no_newline
+    0)
+      echo "$posix_adapter__value__string"
       ;;
-  # ,----- spaces
-  # |,---- width
-    01)
-      fold \
-        \
-        -w "$posix_adapter__value__width" \
-
-      ;;
-  # ,----- spaces
-  # |,---- width
-    10)
-      fold \
-        -s \
-        \
-
-      ;;
-  # ,----- spaces
-  # |,---- width
-    11)
-      fold \
-        -s \
-        -w "$posix_adapter__value__width" \
-
+  # ,-- no_newline
+    1)
+      printf '%s' "$posix_adapter__value__string"
       ;;
     *)
-      _report_incompatible_call \
+      _posix_adapter__echo__report_incompatible_call \
         'Unexpected parameter combination!' \
         'You can only use the available options.'
       ;;
@@ -168,7 +144,7 @@ _posix_adapter__fold__common() {
 # Invalid parameter error reporting helper function.
 #------------------------------------------------------------------------------
 # Globals:
-#   TOOL_NAME
+#   None
 # Options:
 #   None
 # Arguments:
@@ -186,12 +162,12 @@ _posix_adapter__fold__common() {
 # Status:
 #   98  - The function will terminate the execution.
 #==============================================================================
-_report_invalid_parameter() {
+_posix_adapter__echo__report_invalid_parameter() {
   reason="$1"
   details="$2"
-  >&2 echo "ERROR | ${TOOL_NAME} | reason  | ${reason}"
-  >&2 echo "ERROR | ${TOOL_NAME} | details | ${details}"
-  _print_help
+  >&2 echo "ERROR | posix_adapter__echo | reason  | ${reason}"
+  >&2 echo "ERROR | posix_adapter__echo | details | ${details}"
+  _posix_adapter__echo__print_help
   exit 98
 }
 
@@ -199,7 +175,7 @@ _report_invalid_parameter() {
 # Incompatible call error reporting helper function.
 #------------------------------------------------------------------------------
 # Globals:
-#   TOOL_NAME
+#   None
 # Options:
 #   None
 # Arguments:
@@ -217,12 +193,12 @@ _report_invalid_parameter() {
 # Status:
 #   99  - The function will terminate the execution.
 #==============================================================================
-_report_incompatible_call() {
+_posix_adapter__echo__report_incompatible_call() {
   reason="$1"
   details="$2"
-  >&2 echo "ERROR | ${TOOL_NAME} | reason  | ${reason}"
-  >&2 echo "ERROR | ${TOOL_NAME} | details | ${details}"
-  _print_help
+  >&2 echo "ERROR | posix_adapter__echo | reason  | ${reason}"
+  >&2 echo "ERROR | posix_adapter__echo | details | ${details}"
+  _posix_adapter__echo__print_help
   exit 99
 }
 
@@ -230,4 +206,9 @@ _report_incompatible_call() {
 # ENTRY POINT
 #==============================================================================
 
-_posix_adapter__fold "$@"
+# If the script is called directly, call the internal function.
+case $0 in
+  *posix_adapter__echo)
+    posix_adapter__echo "$@"
+    ;;
+esac
diff --git a/src/posix_adapter__find b/src/posix_adapter__find
--- a/src/posix_adapter__find
+++ b/src/posix_adapter__find
@@ -9,9 +9,7 @@
 # TOOL: FIND
 #==============================================================================
 
-TOOL_NAME='posix_adapter__find'
-
-_print_help() {
+_posix_adapter__find__print_help() {
   >&2 echo '=============================================================================='
   >&2 echo ''
   >&2 echo '  posix_adapter__find --help'
@@ -50,7 +48,7 @@ _print_help() {
   >&2 echo '=============================================================================='
 }
 
-_posix_adapter__find() {
+posix_adapter__find() {
   posix_adapter__flag__type='0'
   posix_adapter__value__type=''
 
@@ -104,12 +102,12 @@ _posix_adapter__find() {
         shift
         ;;
       --[!-]*)
-        _report_invalid_parameter \
+        _posix_adapter__find__report_invalid_parameter \
           "Unexpected option '${1}'!" \
           'You can only use the available options.'
         ;;
       -[!-]*)
-        _report_invalid_parameter \
+        _posix_adapter__find__report_invalid_parameter \
           "Invalid single dashed option '${1}'!" \
           "posix_adapter only uses double dashed options like '--option'."
         ;;
@@ -121,7 +119,7 @@ _posix_adapter__find() {
           posix_adapter__value__path="$1"
           shift
         else
-          _report_invalid_parameter \
+          _posix_adapter__find__report_invalid_parameter \
             'Unexpected parameter!' \
             "Parameter '${1}' is unexpected!"
         fi
@@ -670,7 +668,7 @@ _posix_adapter__find__common() {
 
       ;;
     *)
-      _report_incompatible_call \
+      _posix_adapter__find__report_incompatible_call \
         'Unexpected parameter combination!' \
         'You can only use the available options.'
       ;;
@@ -681,7 +679,7 @@ _posix_adapter__find__common() {
 # Invalid parameter error reporting helper function.
 #------------------------------------------------------------------------------
 # Globals:
-#   TOOL_NAME
+#   None
 # Options:
 #   None
 # Arguments:
@@ -699,12 +697,12 @@ _posix_adapter__find__common() {
 # Status:
 #   98  - The function will terminate the execution.
 #==============================================================================
-_report_invalid_parameter() {
+_posix_adapter__find__report_invalid_parameter() {
   reason="$1"
   details="$2"
-  >&2 echo "ERROR | ${TOOL_NAME} | reason  | ${reason}"
-  >&2 echo "ERROR | ${TOOL_NAME} | details | ${details}"
-  _print_help
+  >&2 echo "ERROR | posix_adapter__find | reason  | ${reason}"
+  >&2 echo "ERROR | posix_adapter__find | details | ${details}"
+  _posix_adapter__find__print_help
   exit 98
 }
 
@@ -712,7 +710,7 @@ _report_invalid_parameter() {
 # Incompatible call error reporting helper function.
 #------------------------------------------------------------------------------
 # Globals:
-#   TOOL_NAME
+#   None
 # Options:
 #   None
 # Arguments:
@@ -730,12 +728,12 @@ _report_invalid_parameter() {
 # Status:
 #   99  - The function will terminate the execution.
 #==============================================================================
-_report_incompatible_call() {
+_posix_adapter__find__report_incompatible_call() {
   reason="$1"
   details="$2"
-  >&2 echo "ERROR | ${TOOL_NAME} | reason  | ${reason}"
-  >&2 echo "ERROR | ${TOOL_NAME} | details | ${details}"
-  _print_help
+  >&2 echo "ERROR | posix_adapter__find | reason  | ${reason}"
+  >&2 echo "ERROR | posix_adapter__find | details | ${details}"
+  _posix_adapter__find__print_help
   exit 99
 }
 
@@ -743,4 +741,9 @@ _report_incompatible_call() {
 # ENTRY POINT
 #==============================================================================
 
-_posix_adapter__find "$@"
+# If the script is called directly, call the internal function.
+case $0 in
+  *posix_adapter__find)
+    posix_adapter__find "$@"
+    ;;
+esac
diff --git a/src/posix_adapter__fold b/src/posix_adapter__fold
--- a/src/posix_adapter__fold
+++ b/src/posix_adapter__fold
@@ -1,40 +1,35 @@
 #!/bin/sh
 #==============================================================================
-#   _
-#  | |_ __
-#  | | '_ \
-#  | | | | |
-#  |_|_| |_|
 #
+#   __       _     _
+#  / _| ___ | | __| |
+# | |_ / _ \| |/ _` |
+# |  _| (_) | | (_| |
+# |_|  \___/|_|\__,_|
 #==============================================================================
-# TOOL: LN
+# TOOL: FOLD
 #==============================================================================
 
-TOOL_NAME='posix_adapter__ln'
-
-_print_help() {
+_posix_adapter__fold__print_help() {
   >&2 echo '=============================================================================='
   >&2 echo ''
-  >&2 echo '  posix_adapter__ln --help'
-  >&2 echo '  posix_adapter__ln [--symbolic] [--verbose] --target <target_path>'
-  >&2 echo '      --link-name <link_name>'
+  >&2 echo '  posix_adapter__fold --help'
+  >&2 echo '  posix_adapter__fold [--spaces] --width <line_width>'
   >&2 echo ''
   >&2 echo '------------------------------------------------------------------------------'
-  >&2 echo ' Execution mapping function for the "ln" command line tool with a uniform'
-  >&2 echo ' interface.'
+  >&2 echo ' Execution mapping function for the "fold" command line tool with a'
+  >&2 echo ' uniform interface.'
   >&2 echo '------------------------------------------------------------------------------'
   >&2 echo ' Globals:'
   >&2 echo '   None'
   >&2 echo ' Options:'
   >&2 echo '   --help - Prints out the help message and exits.'
-  >&2 echo '   --symbolic - Optional flag that should make the created link symbolic.'
-  >&2 echo '   --symbolic - Optional flag that makes the execution verbose.'
-  >&2 echo '   --target <target_path> - Mandatory target path option.'
-  >&2 echo '   --link-name <link_name> - Mandatory link name option.'
+  >&2 echo '   --spaces - Use the fold compatible -s flag to break at spaces'
+  >&2 echo '   --width <line_width> - Use the fold compatible -w flag.'
   >&2 echo ' Arguments:'
   >&2 echo '   None'
   >&2 echo ' STDIN:'
-  >&2 echo '   None'
+  >&2 echo '   Input passed to the mapped command.'
   >&2 echo '------------------------------------------------------------------------------'
   >&2 echo ' Output variables:'
   >&2 echo '   None'
@@ -50,76 +45,57 @@ _print_help() {
   >&2 echo '=============================================================================='
 }
 
-_posix_adapter__ln() {
-  posix_adapter__flag__symbolic='0'
-  posix_adapter__flag__verbose='0'
+posix_adapter__fold() {
+  posix_adapter__flag__spaces='0'
 
-  posix_adapter__flag__target='0'
-  posix_adapter__value__target=''
-
-  posix_adapter__flag__link_name='0'
-  posix_adapter__value__link_name=''
+  posix_adapter__flag__width='0'
+  posix_adapter__value__width=''
 
   while [ "$#" -gt '0' ]
   do
     case "$1" in
-      --symbolic)
-        posix_adapter__flag__symbolic='1'
+      --spaces)
+        posix_adapter__flag__spaces='1'
         shift
         ;;
-      --verbose)
-        posix_adapter__flag__verbose='1'
-        shift
-        ;;
-      --target)
-        posix_adapter__flag__target='1'
-        posix_adapter__value__target="$2"
-        shift
-        shift
-        ;;
-      --link-name)
-        posix_adapter__flag__link_name='1'
-        posix_adapter__value__link_name="$2"
+      --width)
+        posix_adapter__flag__width='1'
+        posix_adapter__value__width="$2"
         shift
         shift
         ;;
       --[!-]*)
-        _report_invalid_parameter \
+        _posix_adapter__fold__report_invalid_parameter \
           "Unexpected option '${1}'!" \
           'You can only use the available options.'
         ;;
       -[!-]*)
-        _report_invalid_parameter \
+        _posix_adapter__fold__report_invalid_parameter \
           "Invalid single dashed option '${1}'!" \
           "posix_adapter only uses double dashed options like '--option'."
         ;;
       *)
-        _report_invalid_parameter \
+        _posix_adapter__fold__report_invalid_parameter \
           'Unexpected parameter!' \
-          'This function does not take positional arguments.'
+          "Parameter '${1}' is unexpected!"
         ;;
     esac
   done
 
   # Assembling the decision string.
-  # ,----- symbolic
-  # |,---- verbose
-  # ||,--- target
-  # |||,-- link_name
-  # 0000
-  posix_adapter__decision="${posix_adapter__flag__symbolic}"
-  posix_adapter__decision="${posix_adapter__decision}${posix_adapter__flag__verbose}"
-  posix_adapter__decision="${posix_adapter__decision}${posix_adapter__flag__target}"
-  posix_adapter__decision="${posix_adapter__decision}${posix_adapter__flag__link_name}"
+  # ,----- spaces
+  # |,---- width
+  # 00
+  posix_adapter__decision="${posix_adapter__flag__spaces}"
+  posix_adapter__decision="${posix_adapter__decision}${posix_adapter__flag__width}"
 
-  _posix_adapter__ln__common \
+  _posix_adapter__fold__common \
     "$posix_adapter__decision" \
-    "$posix_adapter__value__target" \
-    "$posix_adapter__value__link_name"
+    "$posix_adapter__value__width"
 }
 
 #==============================================================================
-# Common call mapping function.
+# Common based call mapping function.
 #------------------------------------------------------------------------------
 # Globals:
 #   None
@@ -127,8 +103,7 @@ _posix_adapter__ln() {
 #   None
 # Arguments:
 #   [1] decision_string - String that decodes the optional parameter presence.
-#   [2] value__target_path -  Target path passed to the command.
-#   [3] value__link_name -  Link name passed to the command.
+#   [2] value_width - Value for optional width parameter.
 # STDIN:
 #   Input passed to the mapped command.
 #------------------------------------------------------------------------------
@@ -142,62 +117,45 @@ _posix_adapter__ln() {
 #   0  - Call succeeded.
 #   .. - Call failed with it's error status
 #==============================================================================
-_posix_adapter__ln__common() {
+_posix_adapter__fold__common() {
   posix_adapter__decision_string="$1"
-  posix_adapter__value__target_path="$2"
-  posix_adapter__value__link_name="$3"
+  posix_adapter__value__width="$2"
 
   case "$posix_adapter__decision_string" in
-  # ,----- symbolic
-  # |,---- verbose
-  # ||,--- target
-  # |||,-- link_name
-    0011)
-      ln \
+  # ,----- spaces
+  # |,---- width
+    00)
+      fold \
         \
         \
-        "$posix_adapter__value__target_path" \
-        "$posix_adapter__value__link_name" \
 
       ;;
-  # ,----- symbolic
-  # |,---- verbose
-  # ||,--- target
-  # |||,-- link_name
-    0111)
-      ln \
+  # ,----- spaces
+  # |,---- width
+    01)
+      fold \
         \
-        -v \
-        "$posix_adapter__value__target_path" \
-        "$posix_adapter__value__link_name" \
+        -w "$posix_adapter__value__width" \
 
       ;;
-  # ,----- symbolic
-  # |,---- verbose
-  # ||,--- target
-  # |||,-- link_name
-    1011)
-      ln \
+  # ,----- spaces
+  # |,---- width
+    10)
+      fold \
         -s \
         \
-        "$posix_adapter__value__target_path" \
-        "$posix_adapter__value__link_name" \
 
       ;;
-  # ,----- symbolic
-  # |,---- verbose
-  # ||,--- target
-  # |||,-- link_name
-    1111)
-      ln \
+  # ,----- spaces
+  # |,---- width
+    11)
+      fold \
         -s \
-        -v \
-        "$posix_adapter__value__target_path" \
-        "$posix_adapter__value__link_name" \
+        -w "$posix_adapter__value__width" \
 
       ;;
     *)
-      _report_incompatible_call \
+      _posix_adapter__fold__report_incompatible_call \
         'Unexpected parameter combination!' \
         'You can only use the available options.'
       ;;
@@ -208,7 +166,7 @@ _posix_adapter__ln__common() {
 # Invalid parameter error reporting helper function.
 #------------------------------------------------------------------------------
 # Globals:
-#   TOOL_NAME
+#   None
 # Options:
 #   None
 # Arguments:
@@ -226,12 +184,12 @@ _posix_adapter__ln__common() {
 # Status:
 #   98  - The function will terminate the execution.
 #==============================================================================
-_report_invalid_parameter() {
+_posix_adapter__fold__report_invalid_parameter() {
   reason="$1"
   details="$2"
-  >&2 echo "ERROR | ${TOOL_NAME} | reason  | ${reason}"
-  >&2 echo "ERROR | ${TOOL_NAME} | details | ${details}"
-  _print_help
+  >&2 echo "ERROR | posix_adapter__fold | reason  | ${reason}"
+  >&2 echo "ERROR | posix_adapter__fold | details | ${details}"
+  _posix_adapter__fold__print_help
   exit 98
 }
 
@@ -239,7 +197,7 @@ _report_invalid_parameter() {
 # Incompatible call error reporting helper function.
 #------------------------------------------------------------------------------
 # Globals:
-#   TOOL_NAME
+#   None
 # Options:
 #   None
 # Arguments:
@@ -257,12 +215,12 @@ _report_invalid_parameter() {
 # Status:
 #   99  - The function will terminate the execution.
 #==============================================================================
-_report_incompatible_call() {
+_posix_adapter__fold__report_incompatible_call() {
   reason="$1"
   details="$2"
-  >&2 echo "ERROR | ${TOOL_NAME} | reason  | ${reason}"
-  >&2 echo "ERROR | ${TOOL_NAME} | details | ${details}"
-  _print_help
+  >&2 echo "ERROR | posix_adapter__fold | reason  | ${reason}"
+  >&2 echo "ERROR | posix_adapter__fold | details | ${details}"
+  _posix_adapter__fold__print_help
   exit 99
 }
 
@@ -270,4 +228,9 @@ _report_incompatible_call() {
 # ENTRY POINT
 #==============================================================================
 
-_posix_adapter__ln "$@"
+# If the script is called directly, call the internal function.
+case $0 in
+  *posix_adapter__fold)
+    posix_adapter__fold "$@"
+    ;;
+esac
diff --git a/src/posix_adapter__grep b/src/posix_adapter__grep
--- a/src/posix_adapter__grep
+++ b/src/posix_adapter__grep
@@ -8,9 +8,7 @@
 # TOOL: GREP
 #==============================================================================
 
-TOOL_NAME='posix_adapter__grep'
-
-_print_help() {
+_posix_adapter__grep__print_help() {
   >&2 echo '=============================================================================='
   >&2 echo ''
   >&2 echo '  posix_adapter__grep --help'
@@ -49,7 +47,8 @@ _print_help() {
   >&2 echo '   99 - No compatible call style was found.'
   >&2 echo '=============================================================================='
 }
-_posix_adapter__grep() {
+
+posix_adapter__grep() {
   posix_adapter__flag__extended='0'
   posix_adapter__flag__silent='0'
   posix_adapter__flag__invert_match='0'
@@ -86,12 +85,12 @@ _posix_adapter__grep() {
         shift
         ;;
       --[!-]*)
-        _report_invalid_parameter \
+        _posix_adapter__grep__report_invalid_parameter \
           "Unexpected option '${1}'!" \
           'You can only use the available options.'
         ;;
       -[!-]*)
-        _report_invalid_parameter \
+        _posix_adapter__grep__report_invalid_parameter \
           "Invalid single dashed option '${1}'!" \
           "posix_adapter only uses double dashed options like '--option'."
         ;;
@@ -108,7 +107,7 @@ _posix_adapter__grep() {
             posix_adapter__value__path="$1"
             shift
           else
-            _report_invalid_parameter \
+            _posix_adapter__grep__report_invalid_parameter \
               'Unexpected parameter!' \
               "Parameter '${1}' is unexpected!"
           fi
@@ -119,7 +118,7 @@ _posix_adapter__grep() {
 
   if [ "$posix_adapter__flag__pattern" -eq '0' ]
   then
-    _report_invalid_parameter \
+    _posix_adapter__grep__report_invalid_parameter \
       'Missing <pattern> argument!' \
       'To be able to use grep, you need to specify at least a pattern.'
   fi
@@ -1264,7 +1263,7 @@ _posix_adapter__grep__common() {
 
       ;;
     *)
-      _report_incompatible_call \
+      _posix_adapter__grep__report_incompatible_call \
         'Unexpected parameter combination!' \
         'You can only use the available options.'
       ;;
@@ -1275,7 +1274,7 @@ _posix_adapter__grep__common() {
 # Invalid parameter error reporting helper function.
 #------------------------------------------------------------------------------
 # Globals:
-#   TOOL_NAME
+#   None
 # Options:
 #   None
 # Arguments:
@@ -1293,12 +1292,12 @@ _posix_adapter__grep__common() {
 # Status:
 #   98  - The function will terminate the execution.
 #==============================================================================
-_report_invalid_parameter() {
+_posix_adapter__grep__report_invalid_parameter() {
   reason="$1"
   details="$2"
-  >&2 echo "ERROR | ${TOOL_NAME} | reason  | ${reason}"
-  >&2 echo "ERROR | ${TOOL_NAME} | details | ${details}"
-  _print_help
+  >&2 echo "ERROR | posix_adapter__grep | reason  | ${reason}"
+  >&2 echo "ERROR | posix_adapter__grep | details | ${details}"
+  _posix_adapter__grep__print_help
   exit 98
 }
 
@@ -1306,7 +1305,7 @@ _report_invalid_parameter() {
 # Incompatible call error reporting helper function.
 #------------------------------------------------------------------------------
 # Globals:
-#   TOOL_NAME
+#   None
 # Options:
 #   None
 # Arguments:
@@ -1324,12 +1323,12 @@ _report_invalid_parameter() {
 # Status:
 #   99  - The function will terminate the execution.
 #==============================================================================
-_report_incompatible_call() {
+_posix_adapter__grep__report_incompatible_call() {
   reason="$1"
   details="$2"
-  >&2 echo "ERROR | ${TOOL_NAME} | reason  | ${reason}"
-  >&2 echo "ERROR | ${TOOL_NAME} | details | ${details}"
-  _print_help
+  >&2 echo "ERROR | posix_adapter__grep | reason  | ${reason}"
+  >&2 echo "ERROR | posix_adapter__grep | details | ${details}"
+  _posix_adapter__grep__print_help
   exit 99
 }
 
@@ -1337,4 +1336,9 @@ _report_incompatible_call() {
 # ENTRY POINT
 #==============================================================================
 
-_posix_adapter__grep "$@"
+# If the script is called directly, call the internal function.
+case $0 in
+  *posix_adapter__grep)
+    posix_adapter__grep "$@"
+    ;;
+esac
diff --git a/src/posix_adapter__ln b/src/posix_adapter__ln
--- a/src/posix_adapter__ln
+++ b/src/posix_adapter__ln
@@ -1,33 +1,34 @@
 #!/bin/sh
 #==============================================================================
+#   _
+#  | |_ __
+#  | | '_ \
+#  | | | | |
+#  |_|_| |_|
 #
-#  _   _ _ __   __ _ _ __ ___   ___
-# | | | | '_ \ / _` | '_ ` _ \ / _ \
-# | |_| | | | | (_| | | | | | |  __/
-#  \__,_|_| |_|\__,_|_| |_| |_|\___|
 #==============================================================================
-# TOOL: UNAME
+# TOOL: LN
 #==============================================================================
 
-TOOL_NAME='posix_adapter__uname'
-
-_print_help() {
+_posix_adapter__ln__print_help() {
   >&2 echo '=============================================================================='
   >&2 echo ''
-  >&2 echo '  posix_adapter__uname --help'
-  >&2 echo '  posix_adapter__uname [--kernel-name] [--kernel-release] [--machine]'
+  >&2 echo '  posix_adapter__ln --help'
+  >&2 echo '  posix_adapter__ln [--symbolic] [--verbose] --target <target_path>'
+  >&2 echo '      --link-name <link_name>'
   >&2 echo ''
   >&2 echo '------------------------------------------------------------------------------'
-  >&2 echo ' Execution mapping function for the "uname" command line tool with a uniform'
+  >&2 echo ' Execution mapping function for the "ln" command line tool with a uniform'
   >&2 echo ' interface.'
   >&2 echo '------------------------------------------------------------------------------'
   >&2 echo ' Globals:'
   >&2 echo '   None'
   >&2 echo ' Options:'
   >&2 echo '   --help - Prints out the help message and exits.'
-  >&2 echo '   --kernel-name - uname compatible kernel name flag.'
-  >&2 echo '   --kernel-release - uname compatible kernel release flag.'
-  >&2 echo '   --machine - uname compatible machine flag.'
+  >&2 echo '   --symbolic - Optional flag that should make the created link symbolic.'
+  >&2 echo '   --symbolic - Optional flag that makes the execution verbose.'
+  >&2 echo '   --target <target_path> - Mandatory target path option.'
+  >&2 echo '   --link-name <link_name> - Mandatory link name option.'
   >&2 echo ' Arguments:'
   >&2 echo '   None'
   >&2 echo ' STDIN:'
@@ -47,55 +48,72 @@ _print_help() {
   >&2 echo '=============================================================================='
 }
 
-_posix_adapter__uname() {
-  posix_adapter__flag__kernel_name='0'
-  posix_adapter__flag__kernel_release='0'
-  posix_adapter__flag__machine='0'
+posix_adapter__ln() {
+  posix_adapter__flag__symbolic='0'
+  posix_adapter__flag__verbose='0'
+
+  posix_adapter__flag__target='0'
+  posix_adapter__value__target=''
+
+  posix_adapter__flag__link_name='0'
+  posix_adapter__value__link_name=''
 
   while [ "$#" -gt '0' ]
   do
     case "$1" in
-      --kernel-name)
-        posix_adapter__flag__kernel_name='1'
+      --symbolic)
+        posix_adapter__flag__symbolic='1'
         shift
         ;;
-      --kernel-release)
-        posix_adapter__flag__kernel_release='1'
+      --verbose)
+        posix_adapter__flag__verbose='1'
         shift
         ;;
-      --machine)
-        posix_adapter__flag__machine='1'
+      --target)
+        posix_adapter__flag__target='1'
+        posix_adapter__value__target="$2"
+        shift
+        shift
+        ;;
+      --link-name)
+        posix_adapter__flag__link_name='1'
+        posix_adapter__value__link_name="$2"
+        shift
         shift
         ;;
       --[!-]*)
-        _report_invalid_parameter \
+        _posix_adapter__ln__report_invalid_parameter \
           "Unexpected option '${1}'!" \
           'You can only use the available options.'
         ;;
       -[!-]*)
-        _report_invalid_parameter \
+        _posix_adapter__ln__report_invalid_parameter \
           "Invalid single dashed option '${1}'!" \
           "posix_adapter only uses double dashed options like '--option'."
         ;;
       *)
-        _report_invalid_parameter \
+        _posix_adapter__ln__report_invalid_parameter \
           'Unexpected parameter!' \
-          "Parameter '${1}' is unexpected!"
+          'This function does not take positional arguments.'
         ;;
     esac
   done
 
   # Assembling the decision string.
-  # ,------ kernel_name
-  # |,----- kernel_release
-  # ||,---- machine
-  # 000
-  posix_adapter__decision="${posix_adapter__flag__kernel_name}"
-  posix_adapter__decision="${posix_adapter__decision}${posix_adapter__flag__kernel_release}"
-  posix_adapter__decision="${posix_adapter__decision}${posix_adapter__flag__machine}"
+  # ,----- symbolic
+  # |,---- verbose
+  # ||,--- target
+  # |||,-- link_name
+  # 0000
+  posix_adapter__decision="${posix_adapter__flag__symbolic}"
+  posix_adapter__decision="${posix_adapter__decision}${posix_adapter__flag__verbose}"
+  posix_adapter__decision="${posix_adapter__decision}${posix_adapter__flag__target}"
+  posix_adapter__decision="${posix_adapter__decision}${posix_adapter__flag__link_name}"
 
-  _posix_adapter__uname__common \
-    "$posix_adapter__decision"
+  _posix_adapter__ln__common \
+    "$posix_adapter__decision" \
+    "$posix_adapter__value__target" \
+    "$posix_adapter__value__link_name"
 }
 
 #==============================================================================
@@ -107,6 +125,8 @@ _posix_adapter__uname() {
 #   None
 # Arguments:
 #   [1] decision_string - String that decodes the optional parameter presence.
+#   [2] value__target_path -  Target path passed to the command.
+#   [3] value__link_name -  Link name passed to the command.
 # STDIN:
 #   Input passed to the mapped command.
 #------------------------------------------------------------------------------
@@ -120,82 +140,62 @@ _posix_adapter__uname() {
 #   0  - Call succeeded.
 #   .. - Call failed with it's error status
 #==============================================================================
-_posix_adapter__uname__common() {
+_posix_adapter__ln__common() {
   posix_adapter__decision_string="$1"
+  posix_adapter__value__target_path="$2"
+  posix_adapter__value__link_name="$3"
 
   case "$posix_adapter__decision_string" in
-  # ,------ kernel_name
-  # |,----- kernel_release
-  # ||,---- machine
-    000)
-      uname \
+  # ,----- symbolic
+  # |,---- verbose
+  # ||,--- target
+  # |||,-- link_name
+    0011)
+      ln \
         \
         \
-        \
+        "$posix_adapter__value__target_path" \
+        "$posix_adapter__value__link_name" \
 
       ;;
-  # ,------ kernel_name
-  # |,----- kernel_release
-  # ||,---- machine
-    001)
-      uname \
+  # ,----- symbolic
+  # |,---- verbose
+  # ||,--- target
+  # |||,-- link_name
+    0111)
+      ln \
         \
-        \
-        -m \
+        -v \
+        "$posix_adapter__value__target_path" \
+        "$posix_adapter__value__link_name" \
 
       ;;
-  # ,------ kernel_name
-  # |,----- kernel_release
-  # ||,---- machine
-    010)
-      uname \
-        \
-        -r \
-        \
-
-      ;;
-  # ,------ kernel_name
-  # |,----- kernel_release
-  # ||,---- machine
-    011)
-      uname \
-        \
-        -r \
-        -m \
-
-      ;;
-  # ,------ kernel_name
-  # |,----- kernel_release
-  # ||,---- machine
-    100)
-      uname \
+  # ,----- symbolic
+  # |,---- verbose
+  # ||,--- target
+  # |||,-- link_name
+    1011)
+      ln \
         -s \
         \
-        \
+        "$posix_adapter__value__target_path" \
+        "$posix_adapter__value__link_name" \
 
       ;;
-  # ,------ kernel_name
-  # |,----- kernel_release
-  # ||,---- machine
-    101)
-      uname \
+  # ,----- symbolic
+  # |,---- verbose
+  # ||,--- target
+  # |||,-- link_name
+    1111)
+      ln \
         -s \
-        \
-        -m \
-
-      ;;
-  # ,------ kernel_name
-  # |,----- kernel_release
-  # ||,---- machine
-    111)
-      uname \
-        -s \
-        -r \
-        -m \
+        -v \
+        "$posix_adapter__value__target_path" \
+        "$posix_adapter__value__link_name" \
 
       ;;
     *)
-      _report_incompatible_call \
+      _posix_adapter__ln__report_incompatible_call \
         'Unexpected parameter combination!' \
         'You can only use the available options.'
       ;;
@@ -206,7 +206,7 @@ _posix_adapter__uname__common() {
 # Invalid parameter error reporting helper function.
 #------------------------------------------------------------------------------
 # Globals:
-#   TOOL_NAME
+#   None
 # Options:
 #   None
 # Arguments:
@@ -224,12 +224,12 @@ _posix_adapter__uname__common() {
 # Status:
 #   98  - The function will terminate the execution.
 #==============================================================================
-_report_invalid_parameter() {
+_posix_adapter__ln__report_invalid_parameter() {
   reason="$1"
   details="$2"
-  >&2 echo "ERROR | ${TOOL_NAME} | reason  | ${reason}"
-  >&2 echo "ERROR | ${TOOL_NAME} | details | ${details}"
-  _print_help
+  >&2 echo "ERROR | posix_adapter__ln | reason  | ${reason}"
+  >&2 echo "ERROR | posix_adapter__ln | details | ${details}"
+  _posix_adapter__ln__print_help
   exit 98
 }
 
@@ -237,7 +237,7 @@ _report_invalid_parameter() {
 # Incompatible call error reporting helper function.
 #------------------------------------------------------------------------------
 # Globals:
-#   TOOL_NAME
+#   None
 # Options:
 #   None
 # Arguments:
@@ -255,12 +255,12 @@ _report_invalid_parameter() {
 # Status:
 #   99  - The function will terminate the execution.
 #==============================================================================
-_report_incompatible_call() {
+_posix_adapter__ln__report_incompatible_call() {
   reason="$1"
   details="$2"
-  >&2 echo "ERROR | ${TOOL_NAME} | reason  | ${reason}"
-  >&2 echo "ERROR | ${TOOL_NAME} | details | ${details}"
-  _print_help
+  >&2 echo "ERROR | posix_adapter__ln | reason  | ${reason}"
+  >&2 echo "ERROR | posix_adapter__ln | details | ${details}"
+  _posix_adapter__ln__print_help
   exit 99
 }
 
@@ -268,4 +268,9 @@ _report_incompatible_call() {
 # ENTRY POINT
 #==============================================================================
 
-_posix_adapter__uname "$@"
+# If the script is called directly, call the internal function.
+case $0 in
+  *posix_adapter__ln)
+    posix_adapter__ln "$@"
+    ;;
+esac
diff --git a/src/posix_adapter__ls b/src/posix_adapter__ls
--- a/src/posix_adapter__ls
+++ b/src/posix_adapter__ls
@@ -1,36 +1,34 @@
 #!/bin/sh
 #==============================================================================
-#                _
-# __  ____  ____| |
-# \ \/ /\ \/ / _` |
-#  >  <  >  < (_| |
-# /_/\_\/_/\_\__,_|
+#   _
+#  | |___
+#  | / __|
+#  | \__ \
+#  |_|___/
 #==============================================================================
-# TOOL: XXD
+# TOOL: LS
 #==============================================================================
 
-TOOL_NAME='posix_adapter__xxd'
-
-_print_help() {
+_posix_adapter__ls__print_help() {
   >&2 echo '=============================================================================='
   >&2 echo ''
-  >&2 echo '  posix_adapter__xxd --help'
-  >&2 echo '  posix_adapter__xxd [--plain] [--revert]'
+  >&2 echo '  posix_adapter__ls --help'
+  >&2 echo '  posix_adapter__ls [--all] [--almost-all] <path>'
   >&2 echo ''
   >&2 echo '------------------------------------------------------------------------------'
-  >&2 echo ' Execution mapping function for the "xxd" command line tool with a uniform'
-  >&2 echo ' interface.'
+  >&2 echo ' Execution mapping function for the "ls" command line tool with a'
+  >&2 echo ' uniform interface.'
   >&2 echo '------------------------------------------------------------------------------'
   >&2 echo ' Globals:'
   >&2 echo '   None'
   >&2 echo ' Options:'
   >&2 echo '   --help - Prints out the help message and exits.'
-  >&2 echo '   --plain - xxd compatible plain hexdump flag -p.'
-  >&2 echo '   --revert - xxd compatible revert flag -r.'
+  >&2 echo '   --all - ls compatible -a flag equivavelent.'
+  >&2 echo '   --almost-all - ls compatible -A flag equivavelent.'
   >&2 echo ' Arguments:'
-  >&2 echo '   None'
+  >&2 echo '   [1] path - Path that should be listed.'
   >&2 echo ' STDIN:'
-  >&2 echo '   Value is read from the standard input.'
+  >&2 echo '   Input passed to the mapped command.'
   >&2 echo '------------------------------------------------------------------------------'
   >&2 echo ' Output variables:'
   >&2 echo '   None'
@@ -46,48 +44,66 @@ _print_help() {
   >&2 echo '=============================================================================='
 }
 
-_posix_adapter__xxd() {
-  posix_adapter__flag__plain='0'
-  posix_adapter__flag__revert='0'
+posix_adapter__ls() {
+  posix_adapter__flag__all='0'
+  posix_adapter__flag__almost_all='0'
+
+  posix_adapter__flag__path='0'
+  posix_adapter__value__path=''
 
   while [ "$#" -gt '0' ]
   do
     case "$1" in
-      --plain)
-        posix_adapter__flag__plain='1'
+      --all)
+        posix_adapter__flag__all='1'
         shift
         ;;
-      --revert)
-        posix_adapter__flag__revert='1'
+      --almost-all)
+        posix_adapter__flag__almost_all='1'
         shift
         ;;
       --[!-]*)
-        _report_invalid_parameter \
+        _posix_adapter__ls__report_invalid_parameter \
           "Unexpected option '${1}'!" \
           'You can only use the available options.'
         ;;
       -[!-]*)
-        _report_invalid_parameter \
+        _posix_adapter__ls__report_invalid_parameter \
           "Invalid single dashed option '${1}'!" \
           "posix_adapter only uses double dashed options like '--option'."
         ;;
       *)
-        _report_invalid_parameter \
-          'Unexpected parameter!' \
-          "Parameter '${1}' is unexpected!"
+        if [ "$posix_adapter__flag__path" -eq '0' ]
+        then
+          posix_adapter__flag__path='1'
+          posix_adapter__value__path="$1"
+          shift
+        else
+          _posix_adapter__ls__report_invalid_parameter \
+            'Unexpected parameter!' \
+            "Parameter '${1}' is unexpected!"
+        fi
         ;;
     esac
   done
 
-  # Assembling the decision string.
-  # ,------ plain
-  # |,----- revert
-  # 00
-  posix_adapter__decision="${posix_adapter__flag__plain}"
-  posix_adapter__decision="${posix_adapter__decision}${posix_adapter__flag__revert}"
+  if [ "$posix_adapter__flag__path" -eq '0' ]
+  then
+    _posix_adapter__ls__report_invalid_parameter \
+      'Missing <path> argument!' \
+      'To be able to use ls, you need to specify a path to work with.'
+  fi
 
-  _posix_adapter__xxd__common \
-    "$posix_adapter__decision"
+  # Assembling the decision string.
+  # ,-- all
+  # |,- almost_all
+  # 00
+  posix_adapter__decision="${posix_adapter__flag__all}"
+  posix_adapter__decision="${posix_adapter__decision}${posix_adapter__flag__almost_all}"
+
+  _posix_adapter__ls__common \
+    "$posix_adapter__decision" \
+    "$posix_adapter__value__path"
 }
 
 #==============================================================================
@@ -99,6 +115,7 @@ _posix_adapter__xxd() {
 #   None
 # Arguments:
 #   [1] decision_string - String that decodes the optional parameter presence.
+#   [2] value_path - Path value.
 # STDIN:
 #   Input passed to the mapped command.
 #------------------------------------------------------------------------------
@@ -112,60 +129,40 @@ _posix_adapter__xxd() {
 #   0  - Call succeeded.
 #   .. - Call failed with it's error status
 #==============================================================================
-_posix_adapter__xxd__common() {
+_posix_adapter__ls__common() {
   posix_adapter__decision_string="$1"
+  posix_adapter__value__path="$2"
 
   case "$posix_adapter__decision_string" in
-  # ,------ plain
-  # |,----- revert
-    10)
-      if command -v xxd >/dev/null
-      then
-        xxd -p
-      else
-        # Since xxd is not a common tool and for linux it is mostly shipped
-        # with vim, we are replacing its functionality with python as a last
-        # resort.
-        if command -v python >/dev/null
-        then
-          python -c 'import sys;print("".join([line.encode().hex() for line in sys.stdin]))'
+  # ,-- all
+  # |,- almost_all
+    00)
+      ls \
+        \
+        \
+        "$posix_adapter__value__path" \
 
-        elif command -v python3 >/dev/null
-        then
-          python3 -c 'import sys;print("".join([line.encode().hex() for line in sys.stdin]))'
-
-        else
-          _report_incompatible_call \
-            'No python nor python3 executable was found.' \
-            'Posix adapter is out of options to provide the desired functionality..'
-        fi
-      fi
       ;;
-  # ,------ plain
-  # |,----- revert
-    11)
-      if command -v xxd >/dev/null
-      then
-        xxd -p -r
-      else
-        # See the explanation one case up for the usage of python.
-        if command -v python >/dev/null
-        then
-          python -c 'import sys;print("".join([bytearray.fromhex(line).decode() for line in sys.stdin]).rstrip())'
+  # ,-- all
+  # |,- almost_all
+    01)
+      ls \
+        \
+        -A \
+        "$posix_adapter__value__path" \
 
-        elif command -v python3 >/dev/null
-        then
-          python3 -c 'import sys;print("".join([bytearray.fromhex(line).decode() for line in sys.stdin]).rstrip())'
+      ;;
+  # ,-- all
+  # |,- almost_all
+    10)
+      ls \
+        -a \
+        \
+        "$posix_adapter__value__path" \
 
-        else
-          _report_incompatible_call \
-            'No python nor python3 executable was found.' \
-            'Posix adapter is out of options to provide the desired functionality..'
-        fi
-      fi
       ;;
     *)
-      _report_incompatible_call \
+      _posix_adapter__ls__report_incompatible_call \
         'Unexpected parameter combination!' \
         'You can only use the available options.'
       ;;
@@ -176,7 +173,7 @@ _posix_adapter__xxd__common() {
 # Invalid parameter error reporting helper function.
 #------------------------------------------------------------------------------
 # Globals:
-#   TOOL_NAME
+#   None
 # Options:
 #   None
 # Arguments:
@@ -194,12 +191,12 @@ _posix_adapter__xxd__common() {
 # Status:
 #   98  - The function will terminate the execution.
 #==============================================================================
-_report_invalid_parameter() {
+_posix_adapter__ls__report_invalid_parameter() {
   reason="$1"
   details="$2"
-  >&2 echo "ERROR | ${TOOL_NAME} | reason  | ${reason}"
-  >&2 echo "ERROR | ${TOOL_NAME} | details | ${details}"
-  _print_help
+  >&2 echo "ERROR | posix_adapter__ls | reason  | ${reason}"
+  >&2 echo "ERROR | posix_adapter__ls | details | ${details}"
+  _posix_adapter__ls__print_help
   exit 98
 }
 
@@ -207,7 +204,7 @@ _report_invalid_parameter() {
 # Incompatible call error reporting helper function.
 #------------------------------------------------------------------------------
 # Globals:
-#   TOOL_NAME
+#   None
 # Options:
 #   None
 # Arguments:
@@ -225,12 +222,12 @@ _report_invalid_parameter() {
 # Status:
 #   99  - The function will terminate the execution.
 #==============================================================================
-_report_incompatible_call() {
+_posix_adapter__ls__report_incompatible_call() {
   reason="$1"
   details="$2"
-  >&2 echo "ERROR | ${TOOL_NAME} | reason  | ${reason}"
-  >&2 echo "ERROR | ${TOOL_NAME} | details | ${details}"
-  _print_help
+  >&2 echo "ERROR | posix_adapter__ls | reason  | ${reason}"
+  >&2 echo "ERROR | posix_adapter__ls | details | ${details}"
+  _posix_adapter__ls__print_help
   exit 99
 }
 
@@ -238,4 +235,9 @@ _report_incompatible_call() {
 # ENTRY POINT
 #==============================================================================
 
-_posix_adapter__xxd "$@"
+# If the script is called directly, call the internal function.
+case $0 in
+  *posix_adapter__ls)
+    posix_adapter__ls "$@"
+    ;;
+esac
diff --git a/src/posix_adapter__mkdir b/src/posix_adapter__mkdir
--- a/src/posix_adapter__mkdir
+++ b/src/posix_adapter__mkdir
@@ -1,35 +1,31 @@
 #!/bin/sh
 #==============================================================================
-#
-# __      _____
-# \ \ /\ / / __|
-#  \ V  V / (__
-#   \_/\_/ \___|
+#             _       _ _
+#   _ __ ___ | | ____| (_)_ __
+#  | '_ ` _ \| |/ / _` | | '__|
+#  | | | | | |   < (_| | | |
+#  |_| |_| |_|_|\_\__,_|_|_|
 #==============================================================================
-# TOOL: WC
+# TOOL: MKDIR
 #==============================================================================
 
-TOOL_NAME='posix_adapter__wc'
-
-_print_help() {
+_posix_adapter__mkdir__print_help() {
   >&2 echo '=============================================================================='
   >&2 echo ''
-  >&2 echo '  posix_adapter__wc --help'
-  >&2 echo '  posix_adapter__wc [--chars] [--lines] [--words] [<path>]'
+  >&2 echo '  posix_adapter__mkdir --help'
+  >&2 echo '  posix_adapter__mkdir [--parents] <path>'
   >&2 echo ''
   >&2 echo '------------------------------------------------------------------------------'
-  >&2 echo ' Execution mapping function for the "wc" command line tool with a'
-  >&2 echo ' uniform interface.'
+  >&2 echo ' Execution mapping function for the "mkdir" command line tool with a uniform'
+  >&2 echo ' interface.'
   >&2 echo '------------------------------------------------------------------------------'
   >&2 echo ' Globals:'
   >&2 echo '   None'
   >&2 echo ' Options:'
   >&2 echo '   --help - Prints out the help message and exits.'
-  >&2 echo '   --chars - Use the wc compatible -c flag.'
-  >&2 echo '   --lines - Use the wc compatible -l flag.'
-  >&2 echo '   --words - Use the wc compatible -w flag.'
+  >&2 echo '   --parents - mkdir compatible alias for the -p flag.'
   >&2 echo ' Arguments:'
-  >&2 echo '   [1] [path] - Optional file path.'
+  >&2 echo '   [1] path - Path that should be created.'
   >&2 echo ' STDIN:'
   >&2 echo '   Input passed to the mapped command.'
   >&2 echo '------------------------------------------------------------------------------'
@@ -47,10 +43,8 @@ _print_help() {
   >&2 echo '=============================================================================='
 }
 
-_posix_adapter__wc() {
-  posix_adapter__flag__chars='0'
-  posix_adapter__flag__lines='0'
-  posix_adapter__flag__words='0'
+posix_adapter__mkdir() {
+  posix_adapter__flag__parents='0'
 
   posix_adapter__flag__path='0'
   posix_adapter__value__path=''
@@ -58,25 +52,21 @@ _posix_adapter__wc() {
   while [ "$#" -gt '0' ]
   do
     case "$1" in
-      --chars)
-        posix_adapter__flag__chars='1'
-        shift
+      --help)
+        _posix_adapter__mkdir__help
+        exit 0
         ;;
-      --lines)
-        posix_adapter__flag__lines='1'
-        shift
-        ;;
-      --words)
-        posix_adapter__flag__words='1'
+      --parents)
+        posix_adapter__flag__parents='1'
         shift
         ;;
       --[!-]*)
-        _report_invalid_parameter \
+        _posix_adapter__mkdir__report_invalid_parameter \
           "Unexpected option '${1}'!" \
-          'You can only use the available options.'
+          'You can only use --parents.'
         ;;
       -[!-]*)
-        _report_invalid_parameter \
+        _posix_adapter__mkdir__report_invalid_parameter \
           "Invalid single dashed option '${1}'!" \
           "posix_adapter only uses double dashed options like '--option'."
         ;;
@@ -87,7 +77,7 @@ _posix_adapter__wc() {
           posix_adapter__value__path="$1"
           shift
         else
-          _report_invalid_parameter \
+          _posix_adapter__mkdir__report_invalid_parameter \
             'Unexpected parameter!' \
             "Parameter '${1}' is unexpected!"
         fi
@@ -95,52 +85,25 @@ _posix_adapter__wc() {
     esac
   done
 
+  if [ "$posix_adapter__flag__path" -eq '0' ]
+  then
+    _posix_adapter__mkdir__report_invalid_parameter \
+      'Missing <path> argument!' \
+      'A directory can only be created if you pass a path for it.'
+  fi
+
   # Assembling the decision string.
-  # ,----- chars
-  # |,---- lines
-  # ||,--- words
-  # |||,-- path
-  # 0000
-  posix_adapter__decision="${posix_adapter__flag__chars}"
-  posix_adapter__decision="${posix_adapter__decision}${posix_adapter__flag__lines}"
-  posix_adapter__decision="${posix_adapter__decision}${posix_adapter__flag__words}"
-  posix_adapter__decision="${posix_adapter__decision}${posix_adapter__flag__path}"
+  # ,-- parents
+  # 0
+  posix_adapter__decision="${posix_adapter__flag__parents}"
 
-  case "$(uname -s)" in
-    Linux)
-      _posix_adapter__wc__common \
-        "$posix_adapter__decision" \
-        "$posix_adapter__value__path"
-      ;;
-
-    Darwin)
-      # This if else construction is needed because POSIX does not have the
-      # pipefail feature.
-      if posix_adapter__result="$( \
-        _posix_adapter__wc__common \
-          "$posix_adapter__decision" \
-          "$posix_adapter__value__path" \
-      )"
-      then
-        # Some old BSD based wc implementations pads these results with empty
-        # spaces, hence the additional xargs call.
-        echo "$posix_adapter__result" | xargs
-      else
-        posix_adapter__status="$?"
-        exit "$posix_adapter__status"
-      fi
-      ;;
-
-    *)
-      _report_incompatible_call \
-        "Unsupported platform '$(uname -s)'!" \
-        'The tool is only implemented for Linux and Darwin so far.'
-      ;;
-  esac
+  _posix_adapter__mkdir__common \
+    "$posix_adapter__decision" \
+    "$posix_adapter__value__path"
 }
 
 #==============================================================================
-# Common call mapping function.
+# Common call mapping function
 #------------------------------------------------------------------------------
 # Globals:
 #   None
@@ -148,7 +111,7 @@ _posix_adapter__wc() {
 #   None
 # Arguments:
 #   [1] decision_string - String that decodes the optional parameter presence.
-#   [2] value_path - Value for the positional path argument.
+#   [2] value_path - Path for the mkdir command.
 # STDIN:
 #   Input passed to the mapped command.
 #------------------------------------------------------------------------------
@@ -162,111 +125,29 @@ _posix_adapter__wc() {
 #   0  - Call succeeded.
 #   .. - Call failed with it's error status
 #==============================================================================
-_posix_adapter__wc__common() {
+_posix_adapter__mkdir__common() {
   posix_adapter__decision_string="$1"
   posix_adapter__value__path="$2"
 
   case "$posix_adapter__decision_string" in
-  # ,----- chars
-  # |,---- lines
-  # ||,--- words
-  # |||,-- path
-    0000)
-      wc \
-        \
-        \
-        \
-        \
-
-      ;;
-  # ,----- chars
-  # |,---- lines
-  # ||,--- words
-  # |||,-- path
-    0001)
-      wc \
-        \
-        \
+  # ,-- parents
+    0)
+      mkdir \
         \
         "$posix_adapter__value__path" \
 
       ;;
-  # ,----- chars
-  # |,---- lines
-  # ||,--- words
-  # |||,-- path
-    0010)
-      wc \
-        \
-        \
-        -w \
-        \
-
-      ;;
-  # ,----- chars
-  # |,---- lines
-  # ||,--- words
-  # |||,-- path
-    0011)
-      wc \
-        \
-        \
-        -w \
-        "$posix_adapter__value__path" \
-
-      ;;
-  # ,----- chars
-  # |,---- lines
-  # ||,--- words
-  # |||,-- path
-    0100)
-      wc \
-        \
-        -l \
-        \
-        \
-
-      ;;
-  # ,----- chars
-  # |,---- lines
-  # ||,--- words
-  # |||,-- path
-    0101)
-      wc \
-        \
-        -l \
-        \
-        "$posix_adapter__value__path" \
-
-      ;;
-  # ,----- chars
-  # |,---- lines
-  # ||,--- words
-  # |||,-- path
-    1000)
-      wc \
-        -c \
-        \
-        \
-        \
-
-      ;;
-  # ,----- chars
-  # |,---- lines
-  # ||,--- words
-  # |||,-- path
-    1001)
-      wc \
-        -c \
-        \
-        \
+  # ,-- parents
+    1)
+      mkdir \
+        -p \
         "$posix_adapter__value__path" \
 
       ;;
     *)
-      _report_incompatible_call \
+      _posix_adapter__mkdir__report_incompatible_call \
         'Unexpected parameter combination!' \
-        'You can only use the available options.'
+        'You can only have (--delimiter --fields) or (--characters).'
       ;;
   esac
 }
@@ -275,7 +156,7 @@ _posix_adapter__wc__common() {
 # Invalid parameter error reporting helper function.
 #------------------------------------------------------------------------------
 # Globals:
-#   TOOL_NAME
+#   None
 # Options:
 #   None
 # Arguments:
@@ -293,12 +174,12 @@ _posix_adapter__wc__common() {
 # Status:
 #   98  - The function will terminate the execution.
 #==============================================================================
-_report_invalid_parameter() {
+_posix_adapter__mkdir__report_invalid_parameter() {
   reason="$1"
   details="$2"
-  >&2 echo "ERROR | ${TOOL_NAME} | reason  | ${reason}"
-  >&2 echo "ERROR | ${TOOL_NAME} | details | ${details}"
-  _print_help
+  >&2 echo "ERROR | posix_adapter__mkdir | reason  | ${reason}"
+  >&2 echo "ERROR | posix_adapter__mkdir | details | ${details}"
+  _posix_adapter__mkdir__print_help
   exit 98
 }
 
@@ -306,7 +187,7 @@ _report_invalid_parameter() {
 # Incompatible call error reporting helper function.
 #------------------------------------------------------------------------------
 # Globals:
-#   TOOL_NAME
+#   None
 # Options:
 #   None
 # Arguments:
@@ -324,12 +205,12 @@ _report_invalid_parameter() {
 # Status:
 #   99  - The function will terminate the execution.
 #==============================================================================
-_report_incompatible_call() {
+_posix_adapter__mkdir__report_incompatible_call() {
   reason="$1"
   details="$2"
-  >&2 echo "ERROR | ${TOOL_NAME} | reason  | ${reason}"
-  >&2 echo "ERROR | ${TOOL_NAME} | details | ${details}"
-  _print_help
+  >&2 echo "ERROR | posix_adapter__mkdir | reason  | ${reason}"
+  >&2 echo "ERROR | posix_adapter__mkdir | details | ${details}"
+  _posix_adapter__mkdir__print_help
   exit 99
 }
 
@@ -337,4 +218,9 @@ _report_incompatible_call() {
 # ENTRY POINT
 #==============================================================================
 
-_posix_adapter__wc "$@"
+# If the script is called directly, call the internal function.
+case $0 in
+  *posix_adapter__mkdir)
+    posix_adapter__mkdir "$@"
+    ;;
+esac
diff --git a/src/posix_adapter__mkfifo b/src/posix_adapter__mkfifo
--- a/src/posix_adapter__mkfifo
+++ b/src/posix_adapter__mkfifo
@@ -9,9 +9,7 @@
 # TOOL: MKFIFO
 #==============================================================================
 
-TOOL_NAME='posix_adapter__mkfifo'
-
-_print_help() {
+_posix_adapter__mkfifo__print_help() {
   >&2 echo '=============================================================================='
   >&2 echo ''
   >&2 echo '  posix_adapter__mkfifo --help'
@@ -44,27 +42,27 @@ _print_help() {
   >&2 echo '=============================================================================='
 }
 
-_posix_adapter__mkfifo() {
+posix_adapter__mkfifo() {
   if [ "$#" -eq 0 ]
   then
-    _report_invalid_parameter \
+    _posix_adapter__mkfifo__report_invalid_parameter \
       'Missing parameter!' \
       'A singular <path> parameter was expected!'
   elif [ "$#" -ne 1 ]
   then
-    _report_invalid_parameter \
+    _posix_adapter__mkfifo__report_invalid_parameter \
       'Unexpected parameter count!' \
       "Only 1 parameter is expected, got ${#}!"
   fi
 
   case "$1" in
     --[!-]*)
-      _report_invalid_parameter \
+      _posix_adapter__mkfifo__report_invalid_parameter \
         "Unexpected option '${1}'!" \
         'This function does not take options.'
       ;;
     -[!-]*)
-      _report_invalid_parameter \
+      _posix_adapter__mkfifo__report_invalid_parameter \
         "Invalid single dashed option '${1}'!" \
         "posix_adapter only uses double dashed options like '--option'."
       ;;
@@ -77,7 +75,7 @@ _posix_adapter__mkfifo() {
 # Invalid parameter error reporting helper function.
 #------------------------------------------------------------------------------
 # Globals:
-#   TOOL_NAME
+#   None
 # Options:
 #   None
 # Arguments:
@@ -95,12 +93,12 @@ _posix_adapter__mkfifo() {
 # Status:
 #   98  - The function will terminate the execution.
 #==============================================================================
-_report_invalid_parameter() {
+_posix_adapter__mkfifo__report_invalid_parameter() {
   reason="$1"
   details="$2"
-  >&2 echo "ERROR | ${TOOL_NAME} | reason  | ${reason}"
-  >&2 echo "ERROR | ${TOOL_NAME} | details | ${details}"
-  _print_help
+  >&2 echo "ERROR | posix_adapter__mkfifo | reason  | ${reason}"
+  >&2 echo "ERROR | posix_adapter__mkfifo | details | ${details}"
+  _posix_adapter__mkfifo__print_help
   exit 98
 }
 
@@ -108,7 +106,7 @@ _report_invalid_parameter() {
 # Incompatible call error reporting helper function.
 #------------------------------------------------------------------------------
 # Globals:
-#   TOOL_NAME
+#   None
 # Options:
 #   None
 # Arguments:
@@ -126,12 +124,12 @@ _report_invalid_parameter() {
 # Status:
 #   99  - The function will terminate the execution.
 #==============================================================================
-_report_incompatible_call() {
+_posix_adapter__mkfifo__report_incompatible_call() {
   reason="$1"
   details="$2"
-  >&2 echo "ERROR | ${TOOL_NAME} | reason  | ${reason}"
-  >&2 echo "ERROR | ${TOOL_NAME} | details | ${details}"
-  _print_help
+  >&2 echo "ERROR | posix_adapter__mkfifo | reason  | ${reason}"
+  >&2 echo "ERROR | posix_adapter__mkfifo | details | ${details}"
+  _posix_adapter__mkfifo__print_help
   exit 99
 }
 
@@ -139,4 +137,9 @@ _report_incompatible_call() {
 # ENTRY POINT
 #==============================================================================
 
-_posix_adapter__mkfifo "$@"
+# If the script is called directly, call the internal function.
+case $0 in
+  *posix_adapter__mkfifo)
+    posix_adapter__mkfifo "$@"
+    ;;
+esac
diff --git a/src/posix_adapter__mktemp b/src/posix_adapter__mktemp
--- a/src/posix_adapter__mktemp
+++ b/src/posix_adapter__mktemp
@@ -9,9 +9,7 @@
 # TOOL: MKTEMP
 #==============================================================================
 
-TOOL_NAME='posix_adapter__mktemp'
-
-_print_help() {
+_posix_adapter__mktemp__print_help() {
   >&2 echo '=============================================================================='
   >&2 echo ''
   >&2 echo '  posix_adapter__mktemp --help'
@@ -47,7 +45,7 @@ _print_help() {
   >&2 echo '=============================================================================='
 }
 
-_posix_adapter__mktemp() {
+posix_adapter__mktemp() {
   posix_adapter__flag__directory='0'
 
   posix_adapter__flag__tmpdir='0'
@@ -70,12 +68,12 @@ _posix_adapter__mktemp() {
         shift
         ;;
       --[!-]*)
-        _report_invalid_parameter \
+        _posix_adapter__mktemp__report_invalid_parameter \
           "Unexpected option '${1}'!" \
           'You can only use the available options.'
         ;;
       -[!-]*)
-        _report_invalid_parameter \
+        _posix_adapter__mktemp__report_invalid_parameter \
           "Invalid single dashed option '${1}'!" \
           "posix_adapter only uses double dashed options like '--option'."
         ;;
@@ -86,7 +84,7 @@ _posix_adapter__mktemp() {
           posix_adapter__value__template="$1"
           shift
         else
-          _report_invalid_parameter \
+          _posix_adapter__mktemp__report_invalid_parameter \
             'Unexpected parameter!' \
             "Parameter '${1}' is unexpected!"
         fi
@@ -96,7 +94,7 @@ _posix_adapter__mktemp() {
 
   if [ "$posix_adapter__flag__template" -eq '0' ]
   then
-    _report_invalid_parameter \
+    _posix_adapter__mktemp__report_invalid_parameter \
       'Missing <template> argument!' \
       'To be able to use grep, you need to specify at least a pattern.'
   fi
@@ -124,7 +122,7 @@ _posix_adapter__mktemp() {
       ;;
 
     *)
-      _report_incompatible_call \
+      _posix_adapter__mktemp__report_incompatible_call \
         "Unsupported platform '$(uname -s)'!" \
         'The tool is only implemented for Linux and Darwin so far.'
       ;;
@@ -198,7 +196,7 @@ _posix_adapter__mktemp__linux() {
 
       ;;
     *)
-      _report_incompatible_call \
+      _posix_adapter__mktemp__report_incompatible_call \
         'Unexpected parameter combination!' \
         'You can only have --directory --tmpdir.'
       ;;
@@ -268,7 +266,7 @@ _posix_adapter__mktemp__darwin() {
 
       ;;
     *)
-      _report_incompatible_call \
+      _posix_adapter__mktemp__report_incompatible_call \
         'Unexpected parameter combination!' \
         'You can only use the available options.'
       ;;
@@ -279,7 +277,7 @@ _posix_adapter__mktemp__darwin() {
 # Invalid parameter error reporting helper function.
 #------------------------------------------------------------------------------
 # Globals:
-#   TOOL_NAME
+#   None
 # Options:
 #   None
 # Arguments:
@@ -297,12 +295,12 @@ _posix_adapter__mktemp__darwin() {
 # Status:
 #   98  - The function will terminate the execution.
 #==============================================================================
-_report_invalid_parameter() {
+_posix_adapter__mktemp__report_invalid_parameter() {
   reason="$1"
   details="$2"
-  >&2 echo "ERROR | ${TOOL_NAME} | reason  | ${reason}"
-  >&2 echo "ERROR | ${TOOL_NAME} | details | ${details}"
-  _print_help
+  >&2 echo "ERROR | posix_adapter__mktemp | reason  | ${reason}"
+  >&2 echo "ERROR | posix_adapter__mktemp | details | ${details}"
+  _posix_adapter__mktemp__print_help
   exit 98
 }
 
@@ -310,7 +308,7 @@ _report_invalid_parameter() {
 # Incompatible call error reporting helper function.
 #------------------------------------------------------------------------------
 # Globals:
-#   TOOL_NAME
+#   None
 # Options:
 #   None
 # Arguments:
@@ -328,12 +326,12 @@ _report_invalid_parameter() {
 # Status:
 #   99  - The function will terminate the execution.
 #==============================================================================
-_report_incompatible_call() {
+_posix_adapter__mktemp__report_incompatible_call() {
   reason="$1"
   details="$2"
-  >&2 echo "ERROR | ${TOOL_NAME} | reason  | ${reason}"
-  >&2 echo "ERROR | ${TOOL_NAME} | details | ${details}"
-  _print_help
+  >&2 echo "ERROR | posix_adapter__mktemp | reason  | ${reason}"
+  >&2 echo "ERROR | posix_adapter__mktemp | details | ${details}"
+  _posix_adapter__mktemp__print_help
   exit 99
 }
 
@@ -341,4 +339,9 @@ _report_incompatible_call() {
 # ENTRY POINT
 #==============================================================================
 
-_posix_adapter__mktemp "$@"
+# If the script is called directly, call the internal function.
+case $0 in
+  *posix_adapter__mktemp)
+    posix_adapter__mktemp "$@"
+    ;;
+esac
diff --git a/src/posix_adapter__printf b/src/posix_adapter__printf
--- a/src/posix_adapter__printf
+++ b/src/posix_adapter__printf
@@ -1,32 +1,31 @@
 #!/bin/sh
 #==============================================================================
-#            _
-#   ___ __ _| |_
-#  / __/ _` | __|
-# | (_| (_| | |_
-#  \___\__,_|\__|
-#==============================================================================
-# TOOL: CAT
+#              _       _    __
+#   _ __  _ __(_)_ __ | |_ / _|
+#  | '_ \| '__| | '_ \| __| |_
+#  | |_) | |  | | | | | |_|  _|
+#  | .__/|_|  |_|_| |_|\__|_|
+#==|_|=========================================================================
+# TOOL: PRINTF
 #==============================================================================
 
-TOOL_NAME='posix_adapter__cat'
-
-_print_help() {
+_posix_adapter__printf__print_help() {
   >&2 echo '=============================================================================='
   >&2 echo ''
-  >&2 echo '  posix_adapter__cat --help'
-  >&2 echo '  posix_adapter__cat [path]'
+  >&2 echo '  posix_adapter__printf --help'
+  >&2 echo '  posix_adapter__printf <printf_specification>..'
   >&2 echo ''
   >&2 echo '------------------------------------------------------------------------------'
-  >&2 echo ' Execution mapping function for the "cat" command line tool with a uniform'
-  >&2 echo ' interface.'
+  >&2 echo ' Execution mapping function for the "printf" command line tool with a uniform'
+  >&2 echo ' interface. This is the only command mapping besides tput that is only a proxy'
+  >&2 echo ' because of the nature of printf.'
   >&2 echo '------------------------------------------------------------------------------'
   >&2 echo ' Globals:'
   >&2 echo '   None'
   >&2 echo ' Options:'
   >&2 echo '   --help - Prints out the help message and exits.'
   >&2 echo ' Arguments:'
-  >&2 echo '   [1] [path] - Path thats content should be printed out.'
+  >&2 echo '   [..] specification - printf compatible specification.'
   >&2 echo ' STDIN:'
   >&2 echo '   Input passed to the mapped command.'
   >&2 echo '------------------------------------------------------------------------------'
@@ -44,42 +43,23 @@ _print_help() {
   >&2 echo '=============================================================================='
 }
 
-_posix_adapter__cat() {
-  if [ "$#" -eq 0 ]
+posix_adapter__printf() {
+  if [ "$1" = '--help' ]
   then
-    cat
-  elif [ "$#" -eq 1 ]
-  then
-    case "$1" in
-      --help)
-        _posix_adapter__cat__help
-        exit 0
-        ;;
-    --[!-]*)
-        _report_invalid_parameter \
-          "Unexpected option '${1}'!" \
-          'This function does not take options.'
-        ;;
-    -[!-]*)
-        _report_invalid_parameter \
-          "Invalid single dashed option '${1}'!" \
-          "posix_adapter only uses double dashed options like '--option'."
-        ;;
-    esac
-
-    cat "$1"
-  else
-    _report_invalid_parameter \
-      'Unexpected parameter count!' \
-      "Only 1 parameter is expected, got ${#}!"
+    _posix_adapter__printf__print_help
+    exit 0
   fi
+
+  # We are proxying all the parameters here, hence ignoring the warning.
+  # shellcheck disable=SC2059
+  printf "$@"
 }
 
 #==============================================================================
 # Invalid parameter error reporting helper function.
 #------------------------------------------------------------------------------
 # Globals:
-#   TOOL_NAME
+#   None
 # Options:
 #   None
 # Arguments:
@@ -97,12 +77,12 @@ _posix_adapter__cat() {
 # Status:
 #   98  - The function will terminate the execution.
 #==============================================================================
-_report_invalid_parameter() {
+_posix_adapter__printf__report_invalid_parameter() {
   reason="$1"
   details="$2"
-  >&2 echo "ERROR | ${TOOL_NAME} | reason  | ${reason}"
-  >&2 echo "ERROR | ${TOOL_NAME} | details | ${details}"
-  _print_help
+  >&2 echo "ERROR | posix_adapter__printf | reason  | ${reason}"
+  >&2 echo "ERROR | posix_adapter__printf | details | ${details}"
+  _posix_adapter__printf__print_help
   exit 98
 }
 
@@ -110,7 +90,7 @@ _report_invalid_parameter() {
 # Incompatible call error reporting helper function.
 #------------------------------------------------------------------------------
 # Globals:
-#   TOOL_NAME
+#   None
 # Options:
 #   None
 # Arguments:
@@ -128,12 +108,12 @@ _report_invalid_parameter() {
 # Status:
 #   99  - The function will terminate the execution.
 #==============================================================================
-_report_incompatible_call() {
+_posix_adapter__printf__report_incompatible_call() {
   reason="$1"
   details="$2"
-  >&2 echo "ERROR | ${TOOL_NAME} | reason  | ${reason}"
-  >&2 echo "ERROR | ${TOOL_NAME} | details | ${details}"
-  _print_help
+  >&2 echo "ERROR | posix_adapter__printf | reason  | ${reason}"
+  >&2 echo "ERROR | posix_adapter__printf | details | ${details}"
+  _posix_adapter__printf__print_help
   exit 99
 }
 
@@ -141,4 +121,9 @@ _report_incompatible_call() {
 # ENTRY POINT
 #==============================================================================
 
-_posix_adapter__cat "$@"
+# If the script is called directly, call the internal function.
+case $0 in
+  *posix_adapter__printf)
+    posix_adapter__printf "$@"
+    ;;
+esac
diff --git a/src/posix_adapter__realpath b/src/posix_adapter__realpath
--- a/src/posix_adapter__realpath
+++ b/src/posix_adapter__realpath
@@ -9,9 +9,7 @@
 # TOOL: REALPATH
 #==============================================================================
 
-TOOL_NAME='posix_adapter__realpath'
-
-_print_help() {
+_posix_adapter__realpath__print_help() {
   >&2 echo '=============================================================================='
   >&2 echo ''
   >&2 echo '  posix_adapter__realpath --help'
@@ -46,7 +44,7 @@ _print_help() {
   >&2 echo '=============================================================================='
 }
 
-_posix_adapter__realpath() {
+posix_adapter__realpath() {
   posix_adapter__flag__no_symlinks='0'
 
   posix_adapter__flag__relative_to='0'
@@ -69,12 +67,12 @@ _posix_adapter__realpath() {
         shift
         ;;
       --[!-]*)
-        _report_invalid_parameter \
+        _posix_adapter__realpath__report_invalid_parameter \
           "Unexpected option '${1}'!" \
           'You can only use the available options.'
         ;;
       -[!-]*)
-        _report_invalid_parameter \
+        _posix_adapter__realpath__report_invalid_parameter \
           "Invalid single dashed option '${1}'!" \
           "posix_adapter only uses double dashed options like '--option'."
         ;;
@@ -85,7 +83,7 @@ _posix_adapter__realpath() {
           posix_adapter__value__path="$1"
           shift
         else
-          _report_invalid_parameter \
+          _posix_adapter__realpath__report_invalid_parameter \
             'Unexpected parameter!' \
             "Parameter '${1}' is unexpected!"
         fi
@@ -95,7 +93,7 @@ _posix_adapter__realpath() {
 
   if [ "$posix_adapter__flag__path" -eq '0' ]
   then
-    _report_invalid_parameter \
+    _posix_adapter__realpath__report_invalid_parameter \
       'Missing <path> argument!' \
       'To be able to use realpath, you need to specify a path to work with.'
   fi
@@ -123,7 +121,7 @@ _posix_adapter__realpath() {
       ;;
 
     *)
-      _report_incompatible_call \
+      _posix_adapter__realpath__report_incompatible_call \
         "Unsupported platform '$(uname -s)'!" \
         'The tool is only implemented for Linux and Darwin so far.'
       ;;
@@ -197,7 +195,7 @@ _posix_adapter__realpath__linux() {
 
       ;;
     *)
-      _report_incompatible_call \
+      _posix_adapter__realpath__report_incompatible_call \
         'Unexpected parameter combination!' \
         'You can only use the available options.'
       ;;
@@ -252,7 +250,7 @@ _posix_adapter__realpath__darwin() {
             "$posix_adapter__value__path"
 
         else
-          _report_incompatible_call \
+          _posix_adapter__realpath__report_incompatible_call \
             'No python nor python3 executable was found.' \
             'Posix adapter is out of options to provide the desired functionality..'
         fi
@@ -276,7 +274,7 @@ _posix_adapter__realpath__darwin() {
             "$posix_adapter__value__path" "$posix_adapter__value__relative_to"
 
         else
-          _report_incompatible_call \
+          _posix_adapter__realpath__report_incompatible_call \
             'No python nor python3 executable was found.' \
             'Posix adapter is out of options to provide the desired functionality..'
         fi
@@ -300,7 +298,7 @@ _posix_adapter__realpath__darwin() {
             "$posix_adapter__value__path"
 
         else
-          _report_incompatible_call \
+          _posix_adapter__realpath__report_incompatible_call \
             'No python nor python3 executable was found.' \
             'Posix adapter is out of options to provide the desired functionality..'
         fi
@@ -324,14 +322,14 @@ _posix_adapter__realpath__darwin() {
             "$posix_adapter__value__path" "$posix_adapter__value__relative_to"
 
         else
-          _report_incompatible_call \
+          _posix_adapter__realpath__report_incompatible_call \
             'No python nor python3 executable was found.' \
             'Posix adapter is out of options to provide the desired functionality..'
         fi
       fi
       ;;
     *)
-      _report_incompatible_call \
+      _posix_adapter__realpath__report_incompatible_call \
         'Unexpected parameter combination!' \
         'You can only use the available options.'
       ;;
@@ -342,7 +340,7 @@ _posix_adapter__realpath__darwin() {
 # Invalid parameter error reporting helper function.
 #------------------------------------------------------------------------------
 # Globals:
-#   TOOL_NAME
+#   None
 # Options:
 #   None
 # Arguments:
@@ -360,12 +358,12 @@ _posix_adapter__realpath__darwin() {
 # Status:
 #   98  - The function will terminate the execution.
 #==============================================================================
-_report_invalid_parameter() {
+_posix_adapter__realpath__report_invalid_parameter() {
   reason="$1"
   details="$2"
-  >&2 echo "ERROR | ${TOOL_NAME} | reason  | ${reason}"
-  >&2 echo "ERROR | ${TOOL_NAME} | details | ${details}"
-  _print_help
+  >&2 echo "ERROR | posix_adapter__realpath | reason  | ${reason}"
+  >&2 echo "ERROR | posix_adapter__realpath | details | ${details}"
+  _posix_adapter__realpath__print_help
   exit 98
 }
 
@@ -373,7 +371,7 @@ _report_invalid_parameter() {
 # Incompatible call error reporting helper function.
 #------------------------------------------------------------------------------
 # Globals:
-#   TOOL_NAME
+#   None
 # Options:
 #   None
 # Arguments:
@@ -391,12 +389,12 @@ _report_invalid_parameter() {
 # Status:
 #   99  - The function will terminate the execution.
 #==============================================================================
-_report_incompatible_call() {
+_posix_adapter__realpath__report_incompatible_call() {
   reason="$1"
   details="$2"
-  >&2 echo "ERROR | ${TOOL_NAME} | reason  | ${reason}"
-  >&2 echo "ERROR | ${TOOL_NAME} | details | ${details}"
-  _print_help
+  >&2 echo "ERROR | posix_adapter__realpath | reason  | ${reason}"
+  >&2 echo "ERROR | posix_adapter__realpath | details | ${details}"
+  _posix_adapter__realpath__print_help
   exit 99
 }
 
@@ -404,4 +402,9 @@ _report_incompatible_call() {
 # ENTRY POINT
 #==============================================================================
 
-_posix_adapter__realpath "$@"
+# If the script is called directly, call the internal function.
+case $0 in
+  *posix_adapter__realpath)
+    posix_adapter__realpath "$@"
+    ;;
+esac
diff --git a/src/posix_adapter__rm b/src/posix_adapter__rm
--- a/src/posix_adapter__rm
+++ b/src/posix_adapter__rm
@@ -1,36 +1,33 @@
 #!/bin/sh
 #==============================================================================
-#                _
-#   ___  ___  __| |
-#  / __|/ _ \/ _` |
-#  \__ \  __/ (_| |
-#  |___/\___|\__,_|
+#
+#   _ __ _ __ ___
+#  | '__| '_ ` _ \
+#  | |  | | | | | |
+#  |_|  |_| |_| |_|
 #==============================================================================
-# TOOL: SED
+# TOOL: RM
 #==============================================================================
 
-TOOL_NAME='posix_adapter__sed'
-
-_print_help() {
+_posix_adapter__rm__print_help() {
   >&2 echo '=============================================================================='
   >&2 echo ''
-  >&2 echo '  posix_adapter__sed --help'
-  >&2 echo '  posix_adapter__sed [--extended] [--in-place <suffix>]'
-  >&2 echo '      [--expression <expression>] [<path>]'
+  >&2 echo '  posix_adapter__rm --help'
+  >&2 echo '  posix_adapter__rm [--recursive] [--force] <path>'
   >&2 echo ''
   >&2 echo '------------------------------------------------------------------------------'
-  >&2 echo ' Execution mapping function for the "sed" command line tool with a'
-  >&2 echo ' uniform interface.'
+  >&2 echo ' Execution mapping function for the "rm" command line tool with a uniform'
+  >&2 echo ' interface.'
   >&2 echo '------------------------------------------------------------------------------'
   >&2 echo ' Globals:'
   >&2 echo '   None'
   >&2 echo ' Options:'
   >&2 echo '   --help - Prints out the help message and exits.'
-  >&2 echo '   --extended - Use the extended regexp engine.'
-  >&2 echo '   --in-place <suffix> - In place processing with optional backup with suffix.'
-  >&2 echo '   --expression <expression> - Expression that should be executed.'
+  >&2 echo '   --recursive - rm compatible flag for the -r flag.'
+  >&2 echo '   --force - rm compatible flag for the -f flag.'
+  >&2 echo '   --verbose - rm compatible flag for the -v flag.'
   >&2 echo ' Arguments:'
-  >&2 echo '   [1] [path] - Optional file path.'
+  >&2 echo '   [1] path - Path that should be removed.'
   >&2 echo ' STDIN:'
   >&2 echo '   Input passed to the mapped command.'
   >&2 echo '------------------------------------------------------------------------------'
@@ -48,14 +45,10 @@ _print_help() {
   >&2 echo '=============================================================================='
 }
 
-_posix_adapter__sed() {
-  posix_adapter__flag__extended='0'
-
-  posix_adapter__flag__in_place='0'
-  posix_adapter__value__in_place_suffix=''
-
-  posix_adapter__flag__expression='0'
-  posix_adapter__value__expression=''
+posix_adapter__rm() {
+  posix_adapter__flag__recursive='0'
+  posix_adapter__flag__force='0'
+  posix_adapter__flag__verbose='0'
 
   posix_adapter__flag__path='0'
   posix_adapter__value__path=''
@@ -63,29 +56,25 @@ _posix_adapter__sed() {
   while [ "$#" -gt '0' ]
   do
     case "$1" in
-      --extended)
-        posix_adapter__flag__extended='1'
+      --recursive)
+        posix_adapter__flag__recursive='1'
         shift
         ;;
-      --in-place)
-        posix_adapter__flag__in_place='1'
-        posix_adapter__value__in_place_suffix="$2"
-        shift
+      --force)
+        posix_adapter__flag__force='1'
         shift
         ;;
-      --expression)
-        posix_adapter__flag__expression='1'
-        posix_adapter__value__expression="$2"
-        shift
+      --verbose)
+        posix_adapter__flag__verbose='1'
         shift
         ;;
       --[!-]*)
-        _report_invalid_parameter \
+        _posix_adapter__rm__report_invalid_parameter \
           "Unexpected option '${1}'!" \
           'You can only use the available options.'
         ;;
       -[!-]*)
-        _report_invalid_parameter \
+        _posix_adapter__rm__report_invalid_parameter \
           "Invalid single dashed option '${1}'!" \
           "posix_adapter only uses double dashed options like '--option'."
         ;;
@@ -96,34 +85,32 @@ _posix_adapter__sed() {
           posix_adapter__value__path="$1"
           shift
         else
-          posix_adapter__error_details="$( \
-            printf '%s' 'You have already passed a path argument, you '; \
-            printf '%s' 'probably forgot the --expression flag before '; \
-            printf '%s\n' 'your expression which is mandatory in posix_adapter.' \
-          )"
-          _report_invalid_parameter \
+          _posix_adapter__rm__report_invalid_parameter \
             'Unexpected parameter!' \
-            "$posix_adapter__error_details"
+            "Parameter '${1}' is unexpected!"
         fi
         ;;
     esac
   done
 
-  # Assembling the decision string.
-  # ,----- extended
-  # |,---- in_place
-  # ||,--- expression
-  # |||,-- path
-  # 0000
-  posix_adapter__decision="${posix_adapter__flag__extended}"
-  posix_adapter__decision="${posix_adapter__decision}${posix_adapter__flag__in_place}"
-  posix_adapter__decision="${posix_adapter__decision}${posix_adapter__flag__expression}"
-  posix_adapter__decision="${posix_adapter__decision}${posix_adapter__flag__path}"
+  if [ "$posix_adapter__flag__path" -eq '0' ]
+  then
+    _posix_adapter__rm__report_invalid_parameter \
+      'Missing <path> argument!' \
+      'To be able to use rm, you need to specify a path to work with.'
+  fi
 
-  _posix_adapter__sed__common \
+  # Assembling the decision string.
+  # ,---- recursive
+  # |,--- force
+  # ||,-- verbose
+  # 000
+  posix_adapter__decision="${posix_adapter__flag__recursive}"
+  posix_adapter__decision="${posix_adapter__decision}${posix_adapter__flag__force}"
+  posix_adapter__decision="${posix_adapter__decision}${posix_adapter__flag__verbose}"
+
+  _posix_adapter__rm__common \
     "$posix_adapter__decision" \
-    "$posix_adapter__value__in_place_suffix" \
-    "$posix_adapter__value__expression" \
     "$posix_adapter__value__path"
 }
 
@@ -136,9 +123,7 @@ _posix_adapter__sed() {
 #   None
 # Arguments:
 #   [1] decision_string - String that decodes the optional parameter presence.
-#   [2] value_in_place_suffix - Value passed with the expression flag.
-#   [3] value_expression - Value passed with the expression flag.
-#   [4] value_path - Value for the positional path argument.
+#   [2] value_path - Path value.
 # STDIN:
 #   Input passed to the mapped command.
 #------------------------------------------------------------------------------
@@ -152,111 +137,109 @@ _posix_adapter__sed() {
 #   0  - Call succeeded.
 #   .. - Call failed with it's error status
 #==============================================================================
-_posix_adapter__sed__common() {
+_posix_adapter__rm__common() {
   posix_adapter__decision_string="$1"
-  posix_adapter__value__in_place_suffix="$2"
-  posix_adapter__value__expression="$3"
-  posix_adapter__value__path="$4"
+  posix_adapter__value__path="$2"
 
   case "$posix_adapter__decision_string" in
-  # ,----- extended
-  # |,---- in_place
-  # ||,--- expression
-  # |||,-- path
-    0010)
-      sed \
+  # ,---- recursive
+  # |,--- force
+  # ||,-- verbose
+  # 000
+    000)
+      rm \
         \
         \
-        -e "$posix_adapter__value__expression" \
         \
-
-      ;;
-  # ,----- extended
-  # |,---- in_place
-  # ||,--- expression
-  # |||,-- path
-    0011)
-      sed \
-        \
-        \
-        -e "$posix_adapter__value__expression" \
         "$posix_adapter__value__path" \
 
       ;;
-  # ,----- extended
-  # |,---- in_place
-  # ||,--- expression
-  # |||,-- path
-    0110)
-      sed \
+  # ,---- recursive
+  # |,--- force
+  # ||,-- verbose
+  # 000
+    001)
+      rm \
         \
-        -i"$posix_adapter__value__in_place_suffix" \
-        -e "$posix_adapter__value__expression" \
         \
-
-      ;;
-  # ,----- extended
-  # |,---- in_place
-  # ||,--- expression
-  # |||,-- path
-    0111)
-      sed \
-        \
-        -i"$posix_adapter__value__in_place_suffix" \
-        -e "$posix_adapter__value__expression" \
+        -v \
         "$posix_adapter__value__path" \
 
       ;;
-  # ,----- extended
-  # |,---- in_place
-  # ||,--- expression
-  # |||,-- path
-    1010)
-      sed \
-        -E \
+  # ,---- recursive
+  # |,--- force
+  # ||,-- verbose
+  # 000
+    010)
+      rm \
         \
-        -e "$posix_adapter__value__expression" \
+        -f \
         \
-
-      ;;
-  # ,----- extended
-  # |,---- in_place
-  # ||,--- expression
-  # |||,-- path
-    1011)
-      sed \
-        -E \
-        \
-        -e "$posix_adapter__value__expression" \
         "$posix_adapter__value__path" \
 
       ;;
-  # ,----- extended
-  # |,---- in_place
-  # ||,--- expression
-  # |||,-- path
-    1110)
-      sed \
-        -E \
-        -i"$posix_adapter__value__in_place_suffix" \
-        -e "$posix_adapter__value__expression" \
+  # ,---- recursive
+  # |,--- force
+  # ||,-- verbose
+  # 000
+    011)
+      rm \
         \
+        -f \
+        -v \
+        "$posix_adapter__value__path" \
 
       ;;
-  # ,----- extended
-  # |,---- in_place
-  # ||,--- expression
-  # |||,-- path
-    1111)
-      sed \
-        -E \
-        -i"$posix_adapter__value__in_place_suffix" \
-        -e "$posix_adapter__value__expression" \
+  # ,---- recursive
+  # |,--- force
+  # ||,-- verbose
+  # 000
+    100)
+      rm \
+        -r \
+        \
+        \
+        "$posix_adapter__value__path" \
+
+      ;;
+  # ,---- recursive
+  # |,--- force
+  # ||,-- verbose
+  # 000
+    101)
+      rm \
+        -r \
+        \
+        -v \
+        "$posix_adapter__value__path" \
+
+      ;;
+  # ,---- recursive
+  # |,--- force
+  # ||,-- verbose
+  # 000
+    110)
+      rm \
+        -r \
+        -f \
+        \
+        "$posix_adapter__value__path" \
+
+      ;;
+  # ,---- recursive
+  # |,--- force
+  # ||,-- verbose
+  # 000
+    111)
+      rm \
+        -r \
+        -f \
+        -v \
         "$posix_adapter__value__path" \
 
       ;;
     *)
-      _report_incompatible_call \
+      _posix_adapter__rm__report_incompatible_call \
         'Unexpected parameter combination!' \
         'You can only use the available options.'
       ;;
@@ -267,7 +250,7 @@ _posix_adapter__sed__common() {
 # Invalid parameter error reporting helper function.
 #------------------------------------------------------------------------------
 # Globals:
-#   TOOL_NAME
+#   None
 # Options:
 #   None
 # Arguments:
@@ -285,12 +268,12 @@ _posix_adapter__sed__common() {
 # Status:
 #   98  - The function will terminate the execution.
 #==============================================================================
-_report_invalid_parameter() {
+_posix_adapter__rm__report_invalid_parameter() {
   reason="$1"
   details="$2"
-  >&2 echo "ERROR | ${TOOL_NAME} | reason  | ${reason}"
-  >&2 echo "ERROR | ${TOOL_NAME} | details | ${details}"
-  _print_help
+  >&2 echo "ERROR | posix_adapter__rm | reason  | ${reason}"
+  >&2 echo "ERROR | posix_adapter__rm | details | ${details}"
+  _posix_adapter__rm__print_help
   exit 98
 }
 
@@ -298,7 +281,7 @@ _report_invalid_parameter() {
 # Incompatible call error reporting helper function.
 #------------------------------------------------------------------------------
 # Globals:
-#   TOOL_NAME
+#   None
 # Options:
 #   None
 # Arguments:
@@ -316,12 +299,12 @@ _report_invalid_parameter() {
 # Status:
 #   99  - The function will terminate the execution.
 #==============================================================================
-_report_incompatible_call() {
+_posix_adapter__rm__report_incompatible_call() {
   reason="$1"
   details="$2"
-  >&2 echo "ERROR | ${TOOL_NAME} | reason  | ${reason}"
-  >&2 echo "ERROR | ${TOOL_NAME} | details | ${details}"
-  _print_help
+  >&2 echo "ERROR | posix_adapter__rm | reason  | ${reason}"
+  >&2 echo "ERROR | posix_adapter__rm | details | ${details}"
+  _posix_adapter__rm__print_help
   exit 99
 }
 
@@ -329,4 +312,9 @@ _report_incompatible_call() {
 # ENTRY POINT
 #==============================================================================
 
-_posix_adapter__sed "$@"
+# If the script is called directly, call the internal function.
+case $0 in
+  *posix_adapter__rm)
+    posix_adapter__rm "$@"
+    ;;
+esac
diff --git a/src/posix_adapter__sed b/src/posix_adapter__sed
--- a/src/posix_adapter__sed
+++ b/src/posix_adapter__sed
@@ -1,34 +1,34 @@
 #!/bin/sh
 #==============================================================================
-#   _
-#  | |___
-#  | / __|
-#  | \__ \
-#  |_|___/
+#                _
+#   ___  ___  __| |
+#  / __|/ _ \/ _` |
+#  \__ \  __/ (_| |
+#  |___/\___|\__,_|
 #==============================================================================
-# TOOL: LS
+# TOOL: SED
 #==============================================================================
 
-TOOL_NAME='posix_adapter__ls'
-
-_print_help() {
+_posix_adapter__sed__print_help() {
   >&2 echo '=============================================================================='
   >&2 echo ''
-  >&2 echo '  posix_adapter__ls --help'
-  >&2 echo '  posix_adapter__ls [--all] [--almost-all] <path>'
+  >&2 echo '  posix_adapter__sed --help'
+  >&2 echo '  posix_adapter__sed [--extended] [--in-place <suffix>]'
+  >&2 echo '      [--expression <expression>] [<path>]'
   >&2 echo ''
   >&2 echo '------------------------------------------------------------------------------'
-  >&2 echo ' Execution mapping function for the "ls" command line tool with a'
+  >&2 echo ' Execution mapping function for the "sed" command line tool with a'
   >&2 echo ' uniform interface.'
   >&2 echo '------------------------------------------------------------------------------'
   >&2 echo ' Globals:'
   >&2 echo '   None'
   >&2 echo ' Options:'
   >&2 echo '   --help - Prints out the help message and exits.'
-  >&2 echo '   --all - ls compatible -a flag equivavelent.'
-  >&2 echo '   --almost-all - ls compatible -A flag equivavelent.'
+  >&2 echo '   --extended - Use the extended regexp engine.'
+  >&2 echo '   --in-place <suffix> - In place processing with optional backup with suffix.'
+  >&2 echo '   --expression <expression> - Expression that should be executed.'
   >&2 echo ' Arguments:'
-  >&2 echo '   [1] path - Path that should be listed.'
+  >&2 echo '   [1] [path] - Optional file path.'
   >&2 echo ' STDIN:'
   >&2 echo '   Input passed to the mapped command.'
   >&2 echo '------------------------------------------------------------------------------'
@@ -46,9 +46,14 @@ _print_help() {
   >&2 echo '=============================================================================='
 }
 
-_posix_adapter__ls() {
-  posix_adapter__flag__all='0'
-  posix_adapter__flag__almost_all='0'
+posix_adapter__sed() {
+  posix_adapter__flag__extended='0'
+
+  posix_adapter__flag__in_place='0'
+  posix_adapter__value__in_place_suffix=''
+
+  posix_adapter__flag__expression='0'
+  posix_adapter__value__expression=''
 
   posix_adapter__flag__path='0'
   posix_adapter__value__path=''
@@ -56,21 +61,29 @@ _posix_adapter__ls() {
   while [ "$#" -gt '0' ]
   do
     case "$1" in
-      --all)
-        posix_adapter__flag__all='1'
+      --extended)
+        posix_adapter__flag__extended='1'
         shift
         ;;
-      --almost-all)
-        posix_adapter__flag__almost_all='1'
+      --in-place)
+        posix_adapter__flag__in_place='1'
+        posix_adapter__value__in_place_suffix="$2"
+        shift
+        shift
+        ;;
+      --expression)
+        posix_adapter__flag__expression='1'
+        posix_adapter__value__expression="$2"
+        shift
         shift
         ;;
       --[!-]*)
-        _report_invalid_parameter \
+        _posix_adapter__sed__report_invalid_parameter \
           "Unexpected option '${1}'!" \
           'You can only use the available options.'
         ;;
       -[!-]*)
-        _report_invalid_parameter \
+        _posix_adapter__sed__report_invalid_parameter \
           "Invalid single dashed option '${1}'!" \
           "posix_adapter only uses double dashed options like '--option'."
         ;;
@@ -81,30 +94,34 @@ _posix_adapter__ls() {
           posix_adapter__value__path="$1"
           shift
         else
-          _report_invalid_parameter \
+          posix_adapter__error_details="$( \
+            printf '%s' 'You have already passed a path argument, you '; \
+            printf '%s' 'probably forgot the --expression flag before '; \
+            printf '%s\n' 'your expression which is mandatory in posix_adapter.' \
+          )"
+          _posix_adapter__sed__report_invalid_parameter \
             'Unexpected parameter!' \
-            "Parameter '${1}' is unexpected!"
+            "$posix_adapter__error_details"
         fi
         ;;
     esac
   done
 
-  if [ "$posix_adapter__flag__path" -eq '0' ]
-  then
-    _report_invalid_parameter \
-      'Missing <path> argument!' \
-      'To be able to use ls, you need to specify a path to work with.'
-  fi
-
   # Assembling the decision string.
-  # ,-- all
-  # |,- almost_all
-  # 00
-  posix_adapter__decision="${posix_adapter__flag__all}"
-  posix_adapter__decision="${posix_adapter__decision}${posix_adapter__flag__almost_all}"
+  # ,----- extended
+  # |,---- in_place
+  # ||,--- expression
+  # |||,-- path
+  # 0000
+  posix_adapter__decision="${posix_adapter__flag__extended}"
+  posix_adapter__decision="${posix_adapter__decision}${posix_adapter__flag__in_place}"
+  posix_adapter__decision="${posix_adapter__decision}${posix_adapter__flag__expression}"
+  posix_adapter__decision="${posix_adapter__decision}${posix_adapter__flag__path}"
 
-  _posix_adapter__ls__common \
+  _posix_adapter__sed__common \
     "$posix_adapter__decision" \
+    "$posix_adapter__value__in_place_suffix" \
+    "$posix_adapter__value__expression" \
     "$posix_adapter__value__path"
 }
 
@@ -117,7 +134,9 @@ _posix_adapter__ls() {
 #   None
 # Arguments:
 #   [1] decision_string - String that decodes the optional parameter presence.
-#   [2] value_path - Path value.
+#   [2] value_in_place_suffix - Value passed with the expression flag.
+#   [3] value_expression - Value passed with the expression flag.
+#   [4] value_path - Value for the positional path argument.
 # STDIN:
 #   Input passed to the mapped command.
 #------------------------------------------------------------------------------
@@ -131,40 +150,111 @@ _posix_adapter__ls() {
 #   0  - Call succeeded.
 #   .. - Call failed with it's error status
 #==============================================================================
-_posix_adapter__ls__common() {
+_posix_adapter__sed__common() {
   posix_adapter__decision_string="$1"
-  posix_adapter__value__path="$2"
+  posix_adapter__value__in_place_suffix="$2"
+  posix_adapter__value__expression="$3"
+  posix_adapter__value__path="$4"
 
   case "$posix_adapter__decision_string" in
-  # ,-- all
-  # |,- almost_all
-    00)
-      ls \
+  # ,----- extended
+  # |,---- in_place
+  # ||,--- expression
+  # |||,-- path
+    0010)
+      sed \
         \
         \
+        -e "$posix_adapter__value__expression" \
+        \
+
+      ;;
+  # ,----- extended
+  # |,---- in_place
+  # ||,--- expression
+  # |||,-- path
+    0011)
+      sed \
+        \
+        \
+        -e "$posix_adapter__value__expression" \
         "$posix_adapter__value__path" \
 
       ;;
-  # ,-- all
-  # |,- almost_all
-    01)
-      ls \
+  # ,----- extended
+  # |,---- in_place
+  # ||,--- expression
+  # |||,-- path
+    0110)
+      sed \
         \
-        -A \
+        -i"$posix_adapter__value__in_place_suffix" \
+        -e "$posix_adapter__value__expression" \
+        \
+
+      ;;
+  # ,----- extended
+  # |,---- in_place
+  # ||,--- expression
+  # |||,-- path
+    0111)
+      sed \
+        \
+        -i"$posix_adapter__value__in_place_suffix" \
+        -e "$posix_adapter__value__expression" \
         "$posix_adapter__value__path" \
 
       ;;
-  # ,-- all
-  # |,- almost_all
-    10)
-      ls \
-        -a \
+  # ,----- extended
+  # |,---- in_place
+  # ||,--- expression
+  # |||,-- path
+    1010)
+      sed \
+        -E \
         \
+        -e "$posix_adapter__value__expression" \
+        \
+
+      ;;
+  # ,----- extended
+  # |,---- in_place
+  # ||,--- expression
+  # |||,-- path
+    1011)
+      sed \
+        -E \
+        \
+        -e "$posix_adapter__value__expression" \
+        "$posix_adapter__value__path" \
+
+      ;;
+  # ,----- extended
+  # |,---- in_place
+  # ||,--- expression
+  # |||,-- path
+    1110)
+      sed \
+        -E \
+        -i"$posix_adapter__value__in_place_suffix" \
+        -e "$posix_adapter__value__expression" \
+        \
+
+      ;;
+  # ,----- extended
+  # |,---- in_place
+  # ||,--- expression
+  # |||,-- path
+    1111)
+      sed \
+        -E \
+        -i"$posix_adapter__value__in_place_suffix" \
+        -e "$posix_adapter__value__expression" \
         "$posix_adapter__value__path" \
 
       ;;
     *)
-      _report_incompatible_call \
+      _posix_adapter__sed__report_incompatible_call \
         'Unexpected parameter combination!' \
         'You can only use the available options.'
       ;;
@@ -175,7 +265,7 @@ _posix_adapter__ls__common() {
 # Invalid parameter error reporting helper function.
 #------------------------------------------------------------------------------
 # Globals:
-#   TOOL_NAME
+#   None
 # Options:
 #   None
 # Arguments:
@@ -193,12 +283,12 @@ _posix_adapter__ls__common() {
 # Status:
 #   98  - The function will terminate the execution.
 #==============================================================================
-_report_invalid_parameter() {
+_posix_adapter__sed__report_invalid_parameter() {
   reason="$1"
   details="$2"
-  >&2 echo "ERROR | ${TOOL_NAME} | reason  | ${reason}"
-  >&2 echo "ERROR | ${TOOL_NAME} | details | ${details}"
-  _print_help
+  >&2 echo "ERROR | posix_adapter__sed | reason  | ${reason}"
+  >&2 echo "ERROR | posix_adapter__sed | details | ${details}"
+  _posix_adapter__sed__print_help
   exit 98
 }
 
@@ -206,7 +296,7 @@ _report_invalid_parameter() {
 # Incompatible call error reporting helper function.
 #------------------------------------------------------------------------------
 # Globals:
-#   TOOL_NAME
+#   None
 # Options:
 #   None
 # Arguments:
@@ -224,12 +314,12 @@ _report_invalid_parameter() {
 # Status:
 #   99  - The function will terminate the execution.
 #==============================================================================
-_report_incompatible_call() {
+_posix_adapter__sed__report_incompatible_call() {
   reason="$1"
   details="$2"
-  >&2 echo "ERROR | ${TOOL_NAME} | reason  | ${reason}"
-  >&2 echo "ERROR | ${TOOL_NAME} | details | ${details}"
-  _print_help
+  >&2 echo "ERROR | posix_adapter__sed | reason  | ${reason}"
+  >&2 echo "ERROR | posix_adapter__sed | details | ${details}"
+  _posix_adapter__sed__print_help
   exit 99
 }
 
@@ -237,4 +327,9 @@ _report_incompatible_call() {
 # ENTRY POINT
 #==============================================================================
 
-_posix_adapter__ls "$@"
+# If the script is called directly, call the internal function.
+case $0 in
+  *posix_adapter__sed)
+    posix_adapter__sed "$@"
+    ;;
+esac
diff --git a/src/posix_adapter__sort b/src/posix_adapter__sort
--- a/src/posix_adapter__sort
+++ b/src/posix_adapter__sort
@@ -1,33 +1,32 @@
 #!/bin/sh
 #==============================================================================
-#                      _ _ _       _
-#   _ __ ___  __ _  __| | (_)_ __ | | __
-#  | '__/ _ \/ _` |/ _` | | | '_ \| |/ /
-#  | | |  __/ (_| | (_| | | | | | |   <
-#  |_|  \___|\__,_|\__,_|_|_|_| |_|_|\_\
+#                  _
+#   ___  ___  _ __| |_
+#  / __|/ _ \| '__| __|
+#  \__ \ (_) | |  | |_
+#  |___/\___/|_|   \__|
 #==============================================================================
-# TOOL: READLINK
+# TOOL: SORT
 #==============================================================================
 
-TOOL_NAME='posix_adapter__readlink'
-
-_print_help() {
+_posix_adapter__sort__print_help() {
   >&2 echo '=============================================================================='
   >&2 echo ''
-  >&2 echo '  posix_adapter__readlink --help'
-  >&2 echo '  posix_adapter__readlink [--canonicalize] <path>'
+  >&2 echo '  posix_adapter__sort --help'
+  >&2 echo '  posix_adapter__sort [--zero-terminated] [--dictionary-order] [<path>]'
   >&2 echo ''
   >&2 echo '------------------------------------------------------------------------------'
-  >&2 echo ' Execution mapping function for the "readlink" command line tool with a'
+  >&2 echo ' Execution mapping function for the "sed" command line tool with a'
   >&2 echo ' uniform interface.'
   >&2 echo '------------------------------------------------------------------------------'
   >&2 echo ' Globals:'
   >&2 echo '   None'
   >&2 echo ' Options:'
   >&2 echo '   --help - Prints out the help message and exits.'
-  >&2 echo '   --canonicalize - readlink compatible flag for the original -f flag.'
+  >&2 echo '   --zero-terminated - Use the sort compatible -z flag.'
+  >&2 echo '   --dictionary-order - Use the sort compatible -d flag.'
   >&2 echo ' Arguments:'
-  >&2 echo '   [1] path - Path that should be resolved.'
+  >&2 echo '   [1] [path] - Optional file path.'
   >&2 echo ' STDIN:'
   >&2 echo '   Input passed to the mapped command.'
   >&2 echo '------------------------------------------------------------------------------'
@@ -45,8 +44,9 @@ _print_help() {
   >&2 echo '=============================================================================='
 }
 
-_posix_adapter__readlink() {
-  posix_adapter__flag__canonicalize='0'
+posix_adapter__sort() {
+  posix_adapter__flag__zero_terminated='0'
+  posix_adapter__flag__dictionary_order='0'
 
   posix_adapter__flag__path='0'
   posix_adapter__value__path=''
@@ -54,17 +54,21 @@ _posix_adapter__readlink() {
   while [ "$#" -gt '0' ]
   do
     case "$1" in
-      --canonicalize)
-        posix_adapter__flag__canonicalize='1'
+      --zero-terminated)
+        posix_adapter__flag__zero_terminated='1'
+        shift
+        ;;
+      --dictionary-order)
+        posix_adapter__flag__dictionary_order='1'
         shift
         ;;
       --[!-]*)
-        _report_invalid_parameter \
+        _posix_adapter__sort__report_invalid_parameter \
           "Unexpected option '${1}'!" \
           'You can only use the available options.'
         ;;
       -[!-]*)
-        _report_invalid_parameter \
+        _posix_adapter__sort__report_invalid_parameter \
           "Invalid single dashed option '${1}'!" \
           "posix_adapter only uses double dashed options like '--option'."
         ;;
@@ -75,7 +79,7 @@ _posix_adapter__readlink() {
           posix_adapter__value__path="$1"
           shift
         else
-          _report_invalid_parameter \
+          _posix_adapter__sort__report_invalid_parameter \
             'Unexpected parameter!' \
             "Parameter '${1}' is unexpected!"
         fi
@@ -83,41 +87,22 @@ _posix_adapter__readlink() {
     esac
   done
 
-  if [ "$posix_adapter__flag__path" -eq '0' ]
-  then
-    _report_invalid_parameter \
-      'Missing <path> argument!' \
-      'To be able to use readlink, you need to specify a path to work with.'
-  fi
-
   # Assembling the decision string.
-  # ,-- canonicalize
-  # 0
-  posix_adapter__decision="${posix_adapter__flag__canonicalize}"
+  # ,----- zero_terminated
+  # |,---- dictionary_order
+  # ||,--- path
+  # 000
+  posix_adapter__decision="${posix_adapter__flag__zero_terminated}"
+  posix_adapter__decision="${posix_adapter__decision}${posix_adapter__flag__dictionary_order}"
+  posix_adapter__decision="${posix_adapter__decision}${posix_adapter__flag__path}"
 
-  case "$(uname -s)" in
-    Linux)
-      _posix_adapter__readlink__linux \
-        "$posix_adapter__decision" \
-        "$posix_adapter__value__path"
-      ;;
-
-    Darwin)
-      _posix_adapter__readlink__darwin \
-        "$posix_adapter__decision" \
-        "$posix_adapter__value__path"
-      ;;
-
-    *)
-      _report_incompatible_call \
-        "Unsupported platform '$(uname -s)'!" \
-        'The tool is only implemented for Linux and Darwin so far.'
-      ;;
-  esac
+  _posix_adapter__sort__common \
+    "$posix_adapter__decision" \
+    "$posix_adapter__value__path"
 }
 
 #==============================================================================
-# Linux based call mapping function.
+# Common call mapping function.
 #------------------------------------------------------------------------------
 # Globals:
 #   None
@@ -125,7 +110,7 @@ _posix_adapter__readlink() {
 #   None
 # Arguments:
 #   [1] decision_string - String that decodes the optional parameter presence.
-#   [2] value_path - Path value.
+#   [2] value_path - Value for the positional path argument.
 # STDIN:
 #   Input passed to the mapped command.
 #------------------------------------------------------------------------------
@@ -139,94 +124,93 @@ _posix_adapter__readlink() {
 #   0  - Call succeeded.
 #   .. - Call failed with it's error status
 #==============================================================================
-_posix_adapter__readlink__linux() {
+_posix_adapter__sort__common() {
   posix_adapter__decision_string="$1"
   posix_adapter__value__path="$2"
 
   case "$posix_adapter__decision_string" in
-  # ,-- canonicalize
-    0)
-      readlink \
+  # ,----- zero_terminated
+  # |,---- dictionary_order
+  # ||,--- path
+    000)
+      sort \
+        \
+        \
+        \
+
+      ;;
+  # ,----- zero_terminated
+  # |,---- dictionary_order
+  # ||,--- path
+    001)
+      sort \
+        \
         \
         "$posix_adapter__value__path" \
 
       ;;
-  # ,-- canonicalize
-    1)
-      readlink \
-        -f \
+  # ,----- zero_terminated
+  # |,---- dictionary_order
+  # ||,--- path
+    010)
+      sort \
+        \
+        --dictionary-order \
+        \
+
+      ;;
+  # ,----- zero_terminated
+  # |,---- dictionary_order
+  # ||,--- path
+    011)
+      sort \
+        \
+        --dictionary-order \
         "$posix_adapter__value__path" \
 
       ;;
-    *)
-      _report_incompatible_call \
-        'Unexpected parameter combination!' \
-        'You can only use the available options.'
+  # ,----- zero_terminated
+  # |,---- dictionary_order
+  # ||,--- path
+    100)
+      sort \
+        --zero-terminated \
+        \
+        \
+
       ;;
-  esac
-}
-
-#==============================================================================
-# Darwin based call mapping function.
-#------------------------------------------------------------------------------
-# Globals:
-#   None
-# Options:
-#   None
-# Arguments:
-#   [1] decision_string - String that decodes the optional parameter presence.
-#   [2] value_path - Path value.
-# STDIN:
-#   Input passed to the mapped command.
-#------------------------------------------------------------------------------
-# Output variables:
-#   None
-# STDOUT:
-#   Mapped command's output.
-# STDERR:
-#   Mapped command's error output. Mapping error output.
-# Status:
-#   0  - Call succeeded.
-#   .. - Call failed with it's error status
-#==============================================================================
-_posix_adapter__readlink__darwin() {
-  posix_adapter__decision_string="$1"
-  posix_adapter__value__path="$2"
-
-  case "$posix_adapter__decision_string" in
-  # ,-- canonicalize
-    0)
-      readlink \
+  # ,----- zero_terminated
+  # |,---- dictionary_order
+  # ||,--- path
+    101)
+      sort \
+        --zero-terminated \
         \
         "$posix_adapter__value__path" \
 
       ;;
-  # ,-- canonicalize
-    1)
-      if ! readlink -f "$posix_adapter__value__path" 2>/dev/null
-      then
-        # Yep we are using python as a last resort..
-        if command -v python >/dev/null
-        then
-          python -c \
-            'import os,sys; print(os.path.realpath(os.path.expanduser(sys.argv[1])))' \
-            "$posix_adapter__value__path"
+  # ,----- zero_terminated
+  # |,---- dictionary_order
+  # ||,--- path
+    110)
+      sort \
+        --zero-terminated \
+        --dictionary-order \
+        \
 
-        elif command -v python3 >/dev/null
-        then
-          python3 -c \
-            'import os,sys; print(os.path.realpath(os.path.expanduser(sys.argv[1])))' \
-            "$posix_adapter__value__path"
+      ;;
+  # ,----- zero_terminated
+  # |,---- dictionary_order
+  # ||,--- path
+    111)
+      sort \
+        --zero-terminated \
+        --dictionary-order \
+        "$posix_adapter__value__path" \
 
-        else
-          _report_incompatible_call \
-            'No python nor python3 executable was found.' \
-            'Posix adapter is out of options to provide the desired functionality..'
-        fi
-      fi
       ;;
     *)
-      _report_incompatible_call \
+      _posix_adapter__sort__report_incompatible_call \
         'Unexpected parameter combination!' \
         'You can only use the available options.'
       ;;
@@ -237,7 +221,7 @@ _posix_adapter__readlink__darwin() {
 # Invalid parameter error reporting helper function.
 #------------------------------------------------------------------------------
 # Globals:
-#   TOOL_NAME
+#   None
 # Options:
 #   None
 # Arguments:
@@ -255,12 +239,12 @@ _posix_adapter__readlink__darwin() {
 # Status:
 #   98  - The function will terminate the execution.
 #==============================================================================
-_report_invalid_parameter() {
+_posix_adapter__sort__report_invalid_parameter() {
   reason="$1"
   details="$2"
-  >&2 echo "ERROR | ${TOOL_NAME} | reason  | ${reason}"
-  >&2 echo "ERROR | ${TOOL_NAME} | details | ${details}"
-  _print_help
+  >&2 echo "ERROR | posix_adapter__sort | reason  | ${reason}"
+  >&2 echo "ERROR | posix_adapter__sort | details | ${details}"
+  _posix_adapter__sort__print_help
   exit 98
 }
 
@@ -268,7 +252,7 @@ _report_invalid_parameter() {
 # Incompatible call error reporting helper function.
 #------------------------------------------------------------------------------
 # Globals:
-#   TOOL_NAME
+#   None
 # Options:
 #   None
 # Arguments:
@@ -286,12 +270,12 @@ _report_invalid_parameter() {
 # Status:
 #   99  - The function will terminate the execution.
 #==============================================================================
-_report_incompatible_call() {
+_posix_adapter__sort__report_incompatible_call() {
   reason="$1"
   details="$2"
-  >&2 echo "ERROR | ${TOOL_NAME} | reason  | ${reason}"
-  >&2 echo "ERROR | ${TOOL_NAME} | details | ${details}"
-  _print_help
+  >&2 echo "ERROR | posix_adapter__sort | reason  | ${reason}"
+  >&2 echo "ERROR | posix_adapter__sort | details | ${details}"
+  _posix_adapter__sort__print_help
   exit 99
 }
 
@@ -299,4 +283,9 @@ _report_incompatible_call() {
 # ENTRY POINT
 #==============================================================================
 
-_posix_adapter__readlink "$@"
+# If the script is called directly, call the internal function.
+case $0 in
+  *posix_adapter__sort)
+    posix_adapter__sort "$@"
+    ;;
+esac
diff --git a/src/posix_adapter__touch b/src/posix_adapter__touch
--- a/src/posix_adapter__touch
+++ b/src/posix_adapter__touch
@@ -1,33 +1,30 @@
 #!/bin/sh
 #==============================================================================
-#            _
-#   ___  ___| |__   ___
-#  / _ \/ __| '_ \ / _ \
-# |  __/ (__| | | | (_) |
-#  \___|\___|_| |_|\___/
+#   _                   _
+#  | |_ ___  _   _  ___| |__
+#  | __/ _ \| | | |/ __| '_ \
+#  | || (_) | |_| | (__| | | |
+#   \__\___/ \__,_|\___|_| |_|
 #==============================================================================
-# TOOL: ECHO
+# TOOL: TOUCH
 #==============================================================================
 
-TOOL_NAME='posix_adapter__echo'
-
-_print_help() {
+_posix_adapter__touch__print_help() {
   >&2 echo '=============================================================================='
   >&2 echo ''
-  >&2 echo '  posix_adapter__echo --help'
-  >&2 echo '  posix_adapter__echo [--no-newline] <string>'
+  >&2 echo '  posix_adapter__touch --help'
+  >&2 echo '  posix_adapter__touch <path>'
   >&2 echo ''
   >&2 echo '------------------------------------------------------------------------------'
-  >&2 echo ' Execution mapping function for the "echo" command line tool with a uniform'
+  >&2 echo ' Execution mapping function for the "touch" command line tool with a uniform'
   >&2 echo ' interface.'
   >&2 echo '------------------------------------------------------------------------------'
   >&2 echo ' Globals:'
   >&2 echo '   None'
   >&2 echo ' Options:'
   >&2 echo '   --help - Prints out the help message and exits.'
-  >&2 echo '   --no-newline - Flag that should prevent printing the trailing new line.'
   >&2 echo ' Arguments:'
-  >&2 echo '   [1] string - String that should be printed.'
+  >&2 echo '   [1] path - Path that needs to be touched.'
   >&2 echo ' STDIN:'
   >&2 echo '   Input passed to the mapped command.'
   >&2 echo '------------------------------------------------------------------------------'
@@ -45,108 +42,41 @@ _print_help() {
   >&2 echo '=============================================================================='
 }
 
-_posix_adapter__echo() {
-  posix_adapter__flag__no_newline='0'
-
-  posix_adapter__value__string=''
-
+posix_adapter__touch() {
   if [ "$#" -eq 0 ]
   then
-    _report_invalid_parameter \
-      'Missing string parameter!' \
-      'A singular <string> parameter was expected!'
-  fi
-
-  while [ "$#" -gt '0' ]
-  do
+    _posix_adapter__touch__report_invalid_parameter \
+      'Missing <path> parameter' \
+      'This function does not take options.'
+  elif [ "$#" -eq 1 ]
+  then
     case "$1" in
-      --no-newline)
-        posix_adapter__flag__no_newline='1'
-        shift
-        ;;
-      --[!-]*)
-        _report_invalid_parameter \
+    --[!-]*)
+        _posix_adapter__touch__report_invalid_parameter \
           "Unexpected option '${1}'!" \
-          'You can only use the available options.'
+          'This function does not take options.'
         ;;
-      -[!-]*)
-        _report_invalid_parameter \
+    -[!-]*)
+        _posix_adapter__touch__report_invalid_parameter \
           "Invalid single dashed option '${1}'!" \
           "posix_adapter only uses double dashed options like '--option'."
         ;;
-      *)
-        posix_adapter__value__string="$1"
-        shift
-        if [ "$#" -gt '0' ]
-        then
-          _report_invalid_parameter \
-            'Unexpected parameter!' \
-            'Multiple separated strings passed only one is expected!'
-        fi
-        break
-        ;;
     esac
-  done
 
-  # Assembling the decision string.
-  # ,-- no_newline
-  # 0
-  posix_adapter__decision="${posix_adapter__flag__no_newline}"
+    touch "$1"
 
-  _posix_adapter__echo__common \
-    "$posix_adapter__decision" \
-    "$posix_adapter__value__string"
-}
-
-#==============================================================================
-# Common call mapping function.
-#------------------------------------------------------------------------------
-# Globals:
-#   None
-# Options:
-#   None
-# Arguments:
-#   [1] decision_string - String that decodes the optional parameter presence.
-#   [2] value_string -  String passed to the echo command.
-# STDIN:
-#   Input passed to the mapped command.
-#------------------------------------------------------------------------------
-# Output variables:
-#   None
-# STDOUT:
-#   Mapped command's output.
-# STDERR:
-#   Mapped command's error output. Mapping error output.
-# Status:
-#   0  - Call succeeded.
-#   .. - Call failed with it's error status
-#==============================================================================
-_posix_adapter__echo__common() {
-  posix_adapter__decision_string="$1"
-  posix_adapter__value__string="$2"
-
-  case "$posix_adapter__decision_string" in
-  # ,-- no_newline
-    0)
-      echo "$posix_adapter__value__string"
-      ;;
-  # ,-- no_newline
-    1)
-      printf '%s' "$posix_adapter__value__string"
-      ;;
-    *)
-      _report_incompatible_call \
-        'Unexpected parameter combination!' \
-        'You can only use the available options.'
-      ;;
-  esac
+  else
+    _posix_adapter__touch__report_invalid_parameter \
+      'Unexpected parameter count!' \
+      "Only 1 parameter is expected, got ${#}!"
+  fi
 }
 
 #==============================================================================
 # Invalid parameter error reporting helper function.
 #------------------------------------------------------------------------------
 # Globals:
-#   TOOL_NAME
+#   None
 # Options:
 #   None
 # Arguments:
@@ -164,12 +94,12 @@ _posix_adapter__echo__common() {
 # Status:
 #   98  - The function will terminate the execution.
 #==============================================================================
-_report_invalid_parameter() {
+_posix_adapter__touch__report_invalid_parameter() {
   reason="$1"
   details="$2"
-  >&2 echo "ERROR | ${TOOL_NAME} | reason  | ${reason}"
-  >&2 echo "ERROR | ${TOOL_NAME} | details | ${details}"
-  _print_help
+  >&2 echo "ERROR | posix_adapter__touch | reason  | ${reason}"
+  >&2 echo "ERROR | posix_adapter__touch | details | ${details}"
+  _posix_adapter__touch__print_help
   exit 98
 }
 
@@ -177,7 +107,7 @@ _report_invalid_parameter() {
 # Incompatible call error reporting helper function.
 #------------------------------------------------------------------------------
 # Globals:
-#   TOOL_NAME
+#   None
 # Options:
 #   None
 # Arguments:
@@ -195,12 +125,12 @@ _report_invalid_parameter() {
 # Status:
 #   99  - The function will terminate the execution.
 #==============================================================================
-_report_incompatible_call() {
+_posix_adapter__touch__report_incompatible_call() {
   reason="$1"
   details="$2"
-  >&2 echo "ERROR | ${TOOL_NAME} | reason  | ${reason}"
-  >&2 echo "ERROR | ${TOOL_NAME} | details | ${details}"
-  _print_help
+  >&2 echo "ERROR | posix_adapter__touch | reason  | ${reason}"
+  >&2 echo "ERROR | posix_adapter__touch | details | ${details}"
+  _posix_adapter__touch__print_help
   exit 99
 }
 
@@ -208,4 +138,9 @@ _report_incompatible_call() {
 # ENTRY POINT
 #==============================================================================
 
-_posix_adapter__echo "$@"
+# If the script is called directly, call the internal function.
+case $0 in
+  *posix_adapter__touch)
+    posix_adapter__touch "$@"
+    ;;
+esac
diff --git a/src/posix_adapter__uname b/src/posix_adapter__uname
--- a/src/posix_adapter__uname
+++ b/src/posix_adapter__uname
@@ -1,35 +1,35 @@
 #!/bin/sh
 #==============================================================================
-#             _       _ _
-#   _ __ ___ | | ____| (_)_ __
-#  | '_ ` _ \| |/ / _` | | '__|
-#  | | | | | |   < (_| | | |
-#  |_| |_| |_|_|\_\__,_|_|_|
+#
+#  _   _ _ __   __ _ _ __ ___   ___
+# | | | | '_ \ / _` | '_ ` _ \ / _ \
+# | |_| | | | | (_| | | | | | |  __/
+#  \__,_|_| |_|\__,_|_| |_| |_|\___|
 #==============================================================================
-# TOOL: MKDIR
+# TOOL: UNAME
 #==============================================================================
 
-TOOL_NAME='posix_adapter__mkdir'
-
-_print_help() {
+_posix_adapter__uname__print_help() {
   >&2 echo '=============================================================================='
   >&2 echo ''
-  >&2 echo '  posix_adapter__mkdir --help'
-  >&2 echo '  posix_adapter__mkdir [--parents] <path>'
+  >&2 echo '  posix_adapter__uname --help'
+  >&2 echo '  posix_adapter__uname [--kernel-name] [--kernel-release] [--machine]'
   >&2 echo ''
   >&2 echo '------------------------------------------------------------------------------'
-  >&2 echo ' Execution mapping function for the "mkdir" command line tool with a uniform'
+  >&2 echo ' Execution mapping function for the "uname" command line tool with a uniform'
   >&2 echo ' interface.'
   >&2 echo '------------------------------------------------------------------------------'
   >&2 echo ' Globals:'
   >&2 echo '   None'
   >&2 echo ' Options:'
   >&2 echo '   --help - Prints out the help message and exits.'
-  >&2 echo '   --parents - mkdir compatible alias for the -p flag.'
+  >&2 echo '   --kernel-name - uname compatible kernel name flag.'
+  >&2 echo '   --kernel-release - uname compatible kernel release flag.'
+  >&2 echo '   --machine - uname compatible machine flag.'
   >&2 echo ' Arguments:'
-  >&2 echo '   [1] path - Path that should be created.'
+  >&2 echo '   None'
   >&2 echo ' STDIN:'
-  >&2 echo '   Input passed to the mapped command.'
+  >&2 echo '   None'
   >&2 echo '------------------------------------------------------------------------------'
   >&2 echo ' Output variables:'
   >&2 echo '   None'
@@ -45,67 +45,59 @@ _print_help() {
   >&2 echo '=============================================================================='
 }
 
-_posix_adapter__mkdir() {
-  posix_adapter__flag__parents='0'
-
-  posix_adapter__flag__path='0'
-  posix_adapter__value__path=''
+posix_adapter__uname() {
+  posix_adapter__flag__kernel_name='0'
+  posix_adapter__flag__kernel_release='0'
+  posix_adapter__flag__machine='0'
 
   while [ "$#" -gt '0' ]
   do
     case "$1" in
-      --help)
-        _posix_adapter__mkdir__help
-        exit 0
+      --kernel-name)
+        posix_adapter__flag__kernel_name='1'
+        shift
         ;;
-      --parents)
-        posix_adapter__flag__parents='1'
+      --kernel-release)
+        posix_adapter__flag__kernel_release='1'
+        shift
+        ;;
+      --machine)
+        posix_adapter__flag__machine='1'
         shift
         ;;
       --[!-]*)
-        _report_invalid_parameter \
+        _posix_adapter__uname__report_invalid_parameter \
           "Unexpected option '${1}'!" \
-          'You can only use --parents.'
+          'You can only use the available options.'
         ;;
       -[!-]*)
-        _report_invalid_parameter \
+        _posix_adapter__uname__report_invalid_parameter \
           "Invalid single dashed option '${1}'!" \
           "posix_adapter only uses double dashed options like '--option'."
         ;;
       *)
-        if [ "$posix_adapter__flag__path" -eq '0' ]
-        then
-          posix_adapter__flag__path='1'
-          posix_adapter__value__path="$1"
-          shift
-        else
-          _report_invalid_parameter \
-            'Unexpected parameter!' \
-            "Parameter '${1}' is unexpected!"
-        fi
+        _posix_adapter__uname__report_invalid_parameter \
+          'Unexpected parameter!' \
+          "Parameter '${1}' is unexpected!"
         ;;
     esac
   done
 
-  if [ "$posix_adapter__flag__path" -eq '0' ]
-  then
-    _report_invalid_parameter \
-      'Missing <path> argument!' \
-      'A directory can only be created if you pass a path for it.'
-  fi
-
   # Assembling the decision string.
-  # ,-- parents
-  # 0
-  posix_adapter__decision="${posix_adapter__flag__parents}"
+  # ,------ kernel_name
+  # |,----- kernel_release
+  # ||,---- machine
+  # 000
+  posix_adapter__decision="${posix_adapter__flag__kernel_name}"
+  posix_adapter__decision="${posix_adapter__decision}${posix_adapter__flag__kernel_release}"
+  posix_adapter__decision="${posix_adapter__decision}${posix_adapter__flag__machine}"
 
-  _posix_adapter__mkdir__common \
-    "$posix_adapter__decision" \
-    "$posix_adapter__value__path"
+  _posix_adapter__uname__common \
+    "$posix_adapter__decision"
 }
 
 #==============================================================================
-# Common call mapping function
+# Common call mapping function.
 #------------------------------------------------------------------------------
 # Globals:
 #   None
@@ -113,7 +105,6 @@ _posix_adapter__mkdir() {
 #   None
 # Arguments:
 #   [1] decision_string - String that decodes the optional parameter presence.
-#   [2] value_path - Path for the mkdir command.
 # STDIN:
 #   Input passed to the mapped command.
 #------------------------------------------------------------------------------
@@ -127,29 +118,84 @@ _posix_adapter__mkdir() {
 #   0  - Call succeeded.
 #   .. - Call failed with it's error status
 #==============================================================================
-_posix_adapter__mkdir__common() {
+_posix_adapter__uname__common() {
   posix_adapter__decision_string="$1"
-  posix_adapter__value__path="$2"
 
   case "$posix_adapter__decision_string" in
-  # ,-- parents
-    0)
-      mkdir \
+  # ,------ kernel_name
+  # |,----- kernel_release
+  # ||,---- machine
+    000)
+      uname \
         \
-        "$posix_adapter__value__path" \
+        \
+        \
 
       ;;
-  # ,-- parents
-    1)
-      mkdir \
-        -p \
-        "$posix_adapter__value__path" \
+  # ,------ kernel_name
+  # |,----- kernel_release
+  # ||,---- machine
+    001)
+      uname \
+        \
+        \
+        -m \
+
+      ;;
+  # ,------ kernel_name
+  # |,----- kernel_release
+  # ||,---- machine
+    010)
+      uname \
+        \
+        -r \
+        \
+
+      ;;
+  # ,------ kernel_name
+  # |,----- kernel_release
+  # ||,---- machine
+    011)
+      uname \
+        \
+        -r \
+        -m \
+
+      ;;
+  # ,------ kernel_name
+  # |,----- kernel_release
+  # ||,---- machine
+    100)
+      uname \
+        -s \
+        \
+        \
+
+      ;;
+  # ,------ kernel_name
+  # |,----- kernel_release
+  # ||,---- machine
+    101)
+      uname \
+        -s \
+        \
+        -m \
+
+      ;;
+  # ,------ kernel_name
+  # |,----- kernel_release
+  # ||,---- machine
+    111)
+      uname \
+        -s \
+        -r \
+        -m \
 
       ;;
     *)
-      _report_incompatible_call \
+      _posix_adapter__uname__report_incompatible_call \
         'Unexpected parameter combination!' \
-        'You can only have (--delimiter --fields) or (--characters).'
+        'You can only use the available options.'
       ;;
   esac
 }
@@ -158,7 +204,7 @@ _posix_adapter__mkdir__common() {
 # Invalid parameter error reporting helper function.
 #------------------------------------------------------------------------------
 # Globals:
-#   TOOL_NAME
+#   None
 # Options:
 #   None
 # Arguments:
@@ -176,12 +222,12 @@ _posix_adapter__mkdir__common() {
 # Status:
 #   98  - The function will terminate the execution.
 #==============================================================================
-_report_invalid_parameter() {
+_posix_adapter__uname__report_invalid_parameter() {
   reason="$1"
   details="$2"
-  >&2 echo "ERROR | ${TOOL_NAME} | reason  | ${reason}"
-  >&2 echo "ERROR | ${TOOL_NAME} | details | ${details}"
-  _print_help
+  >&2 echo "ERROR | posix_adapter__uname | reason  | ${reason}"
+  >&2 echo "ERROR | posix_adapter__uname | details | ${details}"
+  _posix_adapter__uname__print_help
   exit 98
 }
 
@@ -189,7 +235,7 @@ _report_invalid_parameter() {
 # Incompatible call error reporting helper function.
 #------------------------------------------------------------------------------
 # Globals:
-#   TOOL_NAME
+#   None
 # Options:
 #   None
 # Arguments:
@@ -207,12 +253,12 @@ _report_invalid_parameter() {
 # Status:
 #   99  - The function will terminate the execution.
 #==============================================================================
-_report_incompatible_call() {
+_posix_adapter__uname__report_incompatible_call() {
   reason="$1"
   details="$2"
-  >&2 echo "ERROR | ${TOOL_NAME} | reason  | ${reason}"
-  >&2 echo "ERROR | ${TOOL_NAME} | details | ${details}"
-  _print_help
+  >&2 echo "ERROR | posix_adapter__uname | reason  | ${reason}"
+  >&2 echo "ERROR | posix_adapter__uname | details | ${details}"
+  _posix_adapter__uname__print_help
   exit 99
 }
 
@@ -220,4 +266,9 @@ _report_incompatible_call() {
 # ENTRY POINT
 #==============================================================================
 
-_posix_adapter__mkdir "$@"
+# If the script is called directly, call the internal function.
+case $0 in
+  *posix_adapter__uname)
+    posix_adapter__uname "$@"
+    ;;
+esac
diff --git a/src/posix_adapter__wc b/src/posix_adapter__wc
--- a/src/posix_adapter__wc
+++ b/src/posix_adapter__wc
@@ -1,35 +1,33 @@
 #!/bin/sh
 #==============================================================================
 #
-#   _ __ _ __ ___
-#  | '__| '_ ` _ \
-#  | |  | | | | | |
-#  |_|  |_| |_| |_|
+# __      _____
+# \ \ /\ / / __|
+#  \ V  V / (__
+#   \_/\_/ \___|
 #==============================================================================
-# TOOL: RM
+# TOOL: WC
 #==============================================================================
 
-TOOL_NAME='posix_adapter__rm'
-
-_print_help() {
+_posix_adapter__wc__print_help() {
   >&2 echo '=============================================================================='
   >&2 echo ''
-  >&2 echo '  posix_adapter__rm --help'
-  >&2 echo '  posix_adapter__rm [--recursive] [--force] <path>'
+  >&2 echo '  posix_adapter__wc --help'
+  >&2 echo '  posix_adapter__wc [--chars] [--lines] [--words] [<path>]'
   >&2 echo ''
   >&2 echo '------------------------------------------------------------------------------'
-  >&2 echo ' Execution mapping function for the "rm" command line tool with a uniform'
-  >&2 echo ' interface.'
+  >&2 echo ' Execution mapping function for the "wc" command line tool with a'
+  >&2 echo ' uniform interface.'
   >&2 echo '------------------------------------------------------------------------------'
   >&2 echo ' Globals:'
   >&2 echo '   None'
   >&2 echo ' Options:'
   >&2 echo '   --help - Prints out the help message and exits.'
-  >&2 echo '   --recursive - rm compatible flag for the -r flag.'
-  >&2 echo '   --force - rm compatible flag for the -f flag.'
-  >&2 echo '   --verbose - rm compatible flag for the -v flag.'
+  >&2 echo '   --chars - Use the wc compatible -c flag.'
+  >&2 echo '   --lines - Use the wc compatible -l flag.'
+  >&2 echo '   --words - Use the wc compatible -w flag.'
   >&2 echo ' Arguments:'
-  >&2 echo '   [1] path - Path that should be removed.'
+  >&2 echo '   [1] [path] - Optional file path.'
   >&2 echo ' STDIN:'
   >&2 echo '   Input passed to the mapped command.'
   >&2 echo '------------------------------------------------------------------------------'
@@ -47,10 +45,10 @@ _print_help() {
   >&2 echo '=============================================================================='
 }
 
-_posix_adapter__rm() {
-  posix_adapter__flag__recursive='0'
-  posix_adapter__flag__force='0'
-  posix_adapter__flag__verbose='0'
+posix_adapter__wc() {
+  posix_adapter__flag__chars='0'
+  posix_adapter__flag__lines='0'
+  posix_adapter__flag__words='0'
 
   posix_adapter__flag__path='0'
   posix_adapter__value__path=''
@@ -58,25 +56,25 @@ _posix_adapter__rm() {
   while [ "$#" -gt '0' ]
   do
     case "$1" in
-      --recursive)
-        posix_adapter__flag__recursive='1'
+      --chars)
+        posix_adapter__flag__chars='1'
         shift
         ;;
-      --force)
-        posix_adapter__flag__force='1'
+      --lines)
+        posix_adapter__flag__lines='1'
         shift
         ;;
-      --verbose)
-        posix_adapter__flag__verbose='1'
+      --words)
+        posix_adapter__flag__words='1'
         shift
         ;;
       --[!-]*)
-        _report_invalid_parameter \
+        _posix_adapter__wc__report_invalid_parameter \
           "Unexpected option '${1}'!" \
           'You can only use the available options.'
         ;;
       -[!-]*)
-        _report_invalid_parameter \
+        _posix_adapter__wc__report_invalid_parameter \
           "Invalid single dashed option '${1}'!" \
           "posix_adapter only uses double dashed options like '--option'."
         ;;
@@ -87,7 +85,7 @@ _posix_adapter__rm() {
           posix_adapter__value__path="$1"
           shift
         else
-          _report_invalid_parameter \
+          _posix_adapter__wc__report_invalid_parameter \
             'Unexpected parameter!' \
             "Parameter '${1}' is unexpected!"
         fi
@@ -95,25 +93,48 @@ _posix_adapter__rm() {
     esac
   done
 
-  if [ "$posix_adapter__flag__path" -eq '0' ]
-  then
-    _report_invalid_parameter \
-      'Missing <path> argument!' \
-      'To be able to use rm, you need to specify a path to work with.'
-  fi
-
   # Assembling the decision string.
-  # ,---- recursive
-  # |,--- force
-  # ||,-- verbose
-  # 000
-  posix_adapter__decision="${posix_adapter__flag__recursive}"
-  posix_adapter__decision="${posix_adapter__decision}${posix_adapter__flag__force}"
-  posix_adapter__decision="${posix_adapter__decision}${posix_adapter__flag__verbose}"
+  # ,----- chars
+  # |,---- lines
+  # ||,--- words
+  # |||,-- path
+  # 0000
+  posix_adapter__decision="${posix_adapter__flag__chars}"
+  posix_adapter__decision="${posix_adapter__decision}${posix_adapter__flag__lines}"
+  posix_adapter__decision="${posix_adapter__decision}${posix_adapter__flag__words}"
+  posix_adapter__decision="${posix_adapter__decision}${posix_adapter__flag__path}"
 
-  _posix_adapter__rm__common \
-    "$posix_adapter__decision" \
-    "$posix_adapter__value__path"
+  case "$(uname -s)" in
+    Linux)
+      _posix_adapter__wc__common \
+        "$posix_adapter__decision" \
+        "$posix_adapter__value__path"
+      ;;
+
+    Darwin)
+      # This if else construction is needed because POSIX does not have the
+      # pipefail feature.
+      if posix_adapter__result="$( \
+        _posix_adapter__wc__common \
+          "$posix_adapter__decision" \
+          "$posix_adapter__value__path" \
+      )"
+      then
+        # Some old BSD based wc implementations pads these results with empty
+        # spaces, hence the additional xargs call.
+        echo "$posix_adapter__result" | xargs
+      else
+        posix_adapter__status="$?"
+        exit "$posix_adapter__status"
+      fi
+      ;;
+
+    *)
+      _posix_adapter__wc__report_incompatible_call \
+        "Unsupported platform '$(uname -s)'!" \
+        'The tool is only implemented for Linux and Darwin so far.'
+      ;;
+  esac
 }
 
 #==============================================================================
@@ -125,7 +146,7 @@ _posix_adapter__rm() {
 #   None
 # Arguments:
 #   [1] decision_string - String that decodes the optional parameter presence.
-#   [2] value_path - Path value.
+#   [2] value_path - Value for the positional path argument.
 # STDIN:
 #   Input passed to the mapped command.
 #------------------------------------------------------------------------------
@@ -139,109 +160,109 @@ _posix_adapter__rm() {
 #   0  - Call succeeded.
 #   .. - Call failed with it's error status
 #==============================================================================
-_posix_adapter__rm__common() {
+_posix_adapter__wc__common() {
   posix_adapter__decision_string="$1"
   posix_adapter__value__path="$2"
 
   case "$posix_adapter__decision_string" in
-  # ,---- recursive
-  # |,--- force
-  # ||,-- verbose
-  # 000
-    000)
-      rm \
+  # ,----- chars
+  # |,---- lines
+  # ||,--- words
+  # |||,-- path
+    0000)
+      wc \
+        \
+        \
+        \
+        \
+
+      ;;
+  # ,----- chars
+  # |,---- lines
+  # ||,--- words
+  # |||,-- path
+    0001)
+      wc \
         \
         \
         \
         "$posix_adapter__value__path" \
 
       ;;
-  # ,---- recursive
-  # |,--- force
-  # ||,-- verbose
-  # 000
-    001)
-      rm \
+  # ,----- chars
+  # |,---- lines
+  # ||,--- words
+  # |||,-- path
+    0010)
+      wc \
         \
         \
-        -v \
+        -w \
+        \
+
+      ;;
+  # ,----- chars
+  # |,---- lines
+  # ||,--- words
+  # |||,-- path
+    0011)
+      wc \
+        \
+        \
+        -w \
         "$posix_adapter__value__path" \
 
       ;;
-  # ,---- recursive
-  # |,--- force
-  # ||,-- verbose
-  # 000
-    010)
-      rm \
+  # ,----- chars
+  # |,---- lines
+  # ||,--- words
+  # |||,-- path
+    0100)
+      wc \
         \
-        -f \
+        -l \
         \
-        "$posix_adapter__value__path" \
+        \
 
       ;;
-  # ,---- recursive
-  # |,--- force
-  # ||,-- verbose
-  # 000
-    011)
-      rm \
+  # ,----- chars
+  # |,---- lines
+  # ||,--- words
+  # |||,-- path
+    0101)
+      wc \
         \
-        -f \
-        -v \
-        "$posix_adapter__value__path" \
-
-      ;;
-  # ,---- recursive
-  # |,--- force
-  # ||,-- verbose
-  # 000
-    100)
-      rm \
-        -r \
-        \
-        \
-        "$posix_adapter__value__path" \
-
-      ;;
-  # ,---- recursive
-  # |,--- force
-  # ||,-- verbose
-  # 000
-    101)
-      rm \
-        -r \
-        \
-        -v \
-        "$posix_adapter__value__path" \
-
-      ;;
-  # ,---- recursive
-  # |,--- force
-  # ||,-- verbose
-  # 000
-    110)
-      rm \
-        -r \
-        -f \
+        -l \
         \
         "$posix_adapter__value__path" \
 
       ;;
-  # ,---- recursive
-  # |,--- force
-  # ||,-- verbose
-  # 000
-    111)
-      rm \
-        -r \
-        -f \
-        -v \
+  # ,----- chars
+  # |,---- lines
+  # ||,--- words
+  # |||,-- path
+    1000)
+      wc \
+        -c \
+        \
+        \
+        \
+
+      ;;
+  # ,----- chars
+  # |,---- lines
+  # ||,--- words
+  # |||,-- path
+    1001)
+      wc \
+        -c \
+        \
+        \
         "$posix_adapter__value__path" \
 
       ;;
     *)
-      _report_incompatible_call \
+      _posix_adapter__wc__report_incompatible_call \
         'Unexpected parameter combination!' \
         'You can only use the available options.'
       ;;
@@ -252,7 +273,7 @@ _posix_adapter__rm__common() {
 # Invalid parameter error reporting helper function.
 #------------------------------------------------------------------------------
 # Globals:
-#   TOOL_NAME
+#   None
 # Options:
 #   None
 # Arguments:
@@ -270,12 +291,12 @@ _posix_adapter__rm__common() {
 # Status:
 #   98  - The function will terminate the execution.
 #==============================================================================
-_report_invalid_parameter() {
+_posix_adapter__wc__report_invalid_parameter() {
   reason="$1"
   details="$2"
-  >&2 echo "ERROR | ${TOOL_NAME} | reason  | ${reason}"
-  >&2 echo "ERROR | ${TOOL_NAME} | details | ${details}"
-  _print_help
+  >&2 echo "ERROR | posix_adapter__wc | reason  | ${reason}"
+  >&2 echo "ERROR | posix_adapter__wc | details | ${details}"
+  _posix_adapter__wc__print_help
   exit 98
 }
 
@@ -283,7 +304,7 @@ _report_invalid_parameter() {
 # Incompatible call error reporting helper function.
 #------------------------------------------------------------------------------
 # Globals:
-#   TOOL_NAME
+#   None
 # Options:
 #   None
 # Arguments:
@@ -301,12 +322,12 @@ _report_invalid_parameter() {
 # Status:
 #   99  - The function will terminate the execution.
 #==============================================================================
-_report_incompatible_call() {
+_posix_adapter__wc__report_incompatible_call() {
   reason="$1"
   details="$2"
-  >&2 echo "ERROR | ${TOOL_NAME} | reason  | ${reason}"
-  >&2 echo "ERROR | ${TOOL_NAME} | details | ${details}"
-  _print_help
+  >&2 echo "ERROR | posix_adapter__wc | reason  | ${reason}"
+  >&2 echo "ERROR | posix_adapter__wc | details | ${details}"
+  _posix_adapter__wc__print_help
   exit 99
 }
 
@@ -314,4 +335,9 @@ _report_incompatible_call() {
 # ENTRY POINT
 #==============================================================================
 
-_posix_adapter__rm "$@"
+# If the script is called directly, call the internal function.
+case $0 in
+  *posix_adapter__wc)
+    posix_adapter__wc "$@"
+    ;;
+esac
diff --git a/src/posix_adapter__xxd b/src/posix_adapter__xxd
--- a/src/posix_adapter__xxd
+++ b/src/posix_adapter__xxd
@@ -1,38 +1,34 @@
 #!/bin/sh
 #==============================================================================
-#             _
-#   ___ _   _| |_
-#  / __| | | | __|
-# | (__| |_| | |_
-#  \___|\__,_|\__|
+#                _
+# __  ____  ____| |
+# \ \/ /\ \/ / _` |
+#  >  <  >  < (_| |
+# /_/\_\/_/\_\__,_|
 #==============================================================================
-# TOOL: CUT
+# TOOL: XXD
 #==============================================================================
 
-TOOL_NAME='posix_adapter__cut'
-
-_print_help() {
+_posix_adapter__xxd__print_help() {
   >&2 echo '=============================================================================='
   >&2 echo ''
-  >&2 echo '  posix_adapter__cut --help'
-  >&2 echo '  posix_adapter__cut --delimiter <delimiter_char> --fields <index_def> [file]'
-  >&2 echo '  posix_adapter__cut --characters <index_def> [file]'
+  >&2 echo '  posix_adapter__xxd --help'
+  >&2 echo '  posix_adapter__xxd [--plain] [--revert]'
   >&2 echo ''
   >&2 echo '------------------------------------------------------------------------------'
-  >&2 echo ' Execution mapping function for the "cut" command line tool with a uniform'
+  >&2 echo ' Execution mapping function for the "xxd" command line tool with a uniform'
   >&2 echo ' interface.'
   >&2 echo '------------------------------------------------------------------------------'
   >&2 echo ' Globals:'
   >&2 echo '   None'
   >&2 echo ' Options:'
   >&2 echo '   --help - Prints out the help message and exits.'
-  >&2 echo '   --delimiter <delimiter_char> - cut compatible delimiter definition'
-  >&2 echo '   --fields <index_definition> - cut compatible fields definition'
-  >&2 echo '   --characters <index_definition> - cut compatible characters definition'
+  >&2 echo '   --plain - xxd compatible plain hexdump flag -p.'
+  >&2 echo '   --revert - xxd compatible revert flag -r.'
   >&2 echo ' Arguments:'
-  >&2 echo '   [1] [file] - File that should be processed.'
+  >&2 echo '   None'
   >&2 echo ' STDIN:'
-  >&2 echo '   Input passed to the mapped command.'
+  >&2 echo '   Value is read from the standard input.'
   >&2 echo '------------------------------------------------------------------------------'
   >&2 echo ' Output variables:'
   >&2 echo '   None'
@@ -48,83 +44,48 @@ _print_help() {
   >&2 echo '=============================================================================='
 }
 
-_posix_adapter__cut() {
-  posix_adapter__flag__delimiter='0'
-  posix_adapter__value__delimiter=''
-
-  posix_adapter__flag__fields='0'
-  posix_adapter__value__fields=''
-
-  posix_adapter__flag__characters='0'
-  posix_adapter__value__characters=''
-
-  posix_adapter__flag__file='0'
-  posix_adapter__value__file=''
+posix_adapter__xxd() {
+  posix_adapter__flag__plain='0'
+  posix_adapter__flag__revert='0'
 
   while [ "$#" -gt '0' ]
   do
     case "$1" in
-      --delimiter)
-        posix_adapter__flag__delimiter='1'
-        posix_adapter__value__delimiter="$2"
-        shift
+      --plain)
+        posix_adapter__flag__plain='1'
         shift
         ;;
-      --fields)
-        posix_adapter__flag__fields='1'
-        posix_adapter__value__fields="$2"
-        shift
-        shift
-        ;;
-      --characters)
-        posix_adapter__flag__characters='1'
-        posix_adapter__value__characters="$2"
-        shift
+      --revert)
+        posix_adapter__flag__revert='1'
         shift
         ;;
       --[!-]*)
-        _report_invalid_parameter \
+        _posix_adapter__xxd__report_invalid_parameter \
           "Unexpected option '${1}'!" \
           'You can only use the available options.'
         ;;
       -[!-]*)
-        _report_invalid_parameter \
+        _posix_adapter__xxd__report_invalid_parameter \
           "Invalid single dashed option '${1}'!" \
           "posix_adapter only uses double dashed options like '--option'."
         ;;
       *)
-        # Only one file is needed for now.
-        if [ "$posix_adapter__flag__file" -eq '0' ]
-        then
-          posix_adapter__flag__file='1'
-          posix_adapter__value__file="$1"
-          shift
-        else
-          _report_invalid_parameter \
-            'Unexpected parameter!' \
-            "Parameter '${1}' is unexpected!"
-        fi
+        _posix_adapter__xxd__report_invalid_parameter \
+          'Unexpected parameter!' \
+          "Parameter '${1}' is unexpected!"
         ;;
     esac
   done
 
   # Assembling the decision string.
-  # ,----- delimiter
-  # |,---- fields
-  # ||,--- characters
-  # |||,-- file
-  # 0000
-  posix_adapter__decision="${posix_adapter__flag__delimiter}"
-  posix_adapter__decision="${posix_adapter__decision}${posix_adapter__flag__fields}"
-  posix_adapter__decision="${posix_adapter__decision}${posix_adapter__flag__characters}"
-  posix_adapter__decision="${posix_adapter__decision}${posix_adapter__flag__file}"
+  # ,------ plain
+  # |,----- revert
+  # 00
+  posix_adapter__decision="${posix_adapter__flag__plain}"
+  posix_adapter__decision="${posix_adapter__decision}${posix_adapter__flag__revert}"
 
-  _posix_adapter__cut__common \
-    "$posix_adapter__decision" \
-    "$posix_adapter__value__delimiter" \
-    "$posix_adapter__value__fields" \
-    "$posix_adapter__value__characters" \
-    "$posix_adapter__value__file"
+  _posix_adapter__xxd__common \
+    "$posix_adapter__decision"
 }
 
 #==============================================================================
@@ -136,11 +97,6 @@ _posix_adapter__cut() {
 #   None
 # Arguments:
 #   [1] decision_string - String that decodes the optional parameter presence.
-#   [2] value_delimiter -  Value passed with the delimiter flag.
-#   [3] value_fields - Value passed with the fields flag.
-#   [4] value_characters - Value passed with the characters flag.
-#   [5] value_file - File path input that should be processed, otherwise the
-#       standard input will be read.
 # STDIN:
 #   Input passed to the mapped command.
 #------------------------------------------------------------------------------
@@ -154,64 +110,60 @@ _posix_adapter__cut() {
 #   0  - Call succeeded.
 #   .. - Call failed with it's error status
 #==============================================================================
-_posix_adapter__cut__common() {
+_posix_adapter__xxd__common() {
   posix_adapter__decision_string="$1"
-  posix_adapter__value__delimiter="$2"
-  posix_adapter__value__fields="$3"
-  posix_adapter__value__characters="$4"
-  posix_adapter__value__file="$5"
 
   case "$posix_adapter__decision_string" in
-  # ,----- delimiter
-  # |,---- fields
-  # ||,--- characters
-  # |||,-- file
-    1100)
-      cut \
-        -d "$posix_adapter__value__delimiter" \
-        -f "$posix_adapter__value__fields" \
-        \
-        \
+  # ,------ plain
+  # |,----- revert
+    10)
+      if command -v xxd >/dev/null
+      then
+        xxd -p
+      else
+        # Since xxd is not a common tool and for linux it is mostly shipped
+        # with vim, we are replacing its functionality with python as a last
+        # resort.
+        if command -v python >/dev/null
+        then
+          python -c 'import sys;print("".join([line.encode().hex() for line in sys.stdin]))'
 
+        elif command -v python3 >/dev/null
+        then
+          python3 -c 'import sys;print("".join([line.encode().hex() for line in sys.stdin]))'
+
+        else
+          _posix_adapter__xxd__report_incompatible_call \
+            'No python nor python3 executable was found.' \
+            'Posix adapter is out of options to provide the desired functionality..'
+        fi
+      fi
       ;;
-  # ,----- delimiter
-  # |,---- fields
-  # ||,--- characters
-  # |||,-- file
-    0010)
-      cut \
-        \
-        \
-        -c "$posix_adapter__value__characters" \
-        \
+  # ,------ plain
+  # |,----- revert
+    11)
+      if command -v xxd >/dev/null
+      then
+        xxd -p -r
+      else
+        # See the explanation one case up for the usage of python.
+        if command -v python >/dev/null
+        then
+          python -c 'import sys;print("".join([bytearray.fromhex(line).decode() for line in sys.stdin]).rstrip())'
 
-      ;;
-  # ,----- delimiter
-  # |,---- fields
-  # ||,--- characters
-  # |||,-- file
-    1101)
-      cut \
-        -d "$posix_adapter__value__delimiter" \
-        -f "$posix_adapter__value__fields" \
-        \
-        "$posix_adapter__value__file" \
+        elif command -v python3 >/dev/null
+        then
+          python3 -c 'import sys;print("".join([bytearray.fromhex(line).decode() for line in sys.stdin]).rstrip())'
 
-      ;;
-  # ,----- delimiter
-  # |,---- fields
-  # ||,--- characters
-  # |||,-- file
-    0011)
-      cut \
-        \
-        \
-        -c "$posix_adapter__value__characters" \
-        "$posix_adapter__value__file" \
-
+        else
+          _posix_adapter__xxd__report_incompatible_call \
+            'No python nor python3 executable was found.' \
+            'Posix adapter is out of options to provide the desired functionality..'
+        fi
+      fi
       ;;
     *)
-      _report_incompatible_call \
+      _posix_adapter__xxd__report_incompatible_call \
         'Unexpected parameter combination!' \
         'You can only use the available options.'
       ;;
@@ -222,7 +174,7 @@ _posix_adapter__cut__common() {
 # Invalid parameter error reporting helper function.
 #------------------------------------------------------------------------------
 # Globals:
-#   TOOL_NAME
+#   None
 # Options:
 #   None
 # Arguments:
@@ -240,12 +192,12 @@ _posix_adapter__cut__common() {
 # Status:
 #   98  - The function will terminate the execution.
 #==============================================================================
-_report_invalid_parameter() {
+_posix_adapter__xxd__report_invalid_parameter() {
   reason="$1"
   details="$2"
-  >&2 echo "ERROR | ${TOOL_NAME} | reason  | ${reason}"
-  >&2 echo "ERROR | ${TOOL_NAME} | details | ${details}"
-  _print_help
+  >&2 echo "ERROR | posix_adapter__xxd | reason  | ${reason}"
+  >&2 echo "ERROR | posix_adapter__xxd | details | ${details}"
+  _posix_adapter__xxd__print_help
   exit 98
 }
 
@@ -253,7 +205,7 @@ _report_invalid_parameter() {
 # Incompatible call error reporting helper function.
 #------------------------------------------------------------------------------
 # Globals:
-#   TOOL_NAME
+#   None
 # Options:
 #   None
 # Arguments:
@@ -271,12 +223,12 @@ _report_invalid_parameter() {
 # Status:
 #   99  - The function will terminate the execution.
 #==============================================================================
-_report_incompatible_call() {
+_posix_adapter__xxd__report_incompatible_call() {
   reason="$1"
   details="$2"
-  >&2 echo "ERROR | ${TOOL_NAME} | reason  | ${reason}"
-  >&2 echo "ERROR | ${TOOL_NAME} | details | ${details}"
-  _print_help
+  >&2 echo "ERROR | posix_adapter__xxd | reason  | ${reason}"
+  >&2 echo "ERROR | posix_adapter__xxd | details | ${details}"
+  _posix_adapter__xxd__print_help
   exit 99
 }
 
@@ -284,4 +236,9 @@ _report_incompatible_call() {
 # ENTRY POINT
 #==============================================================================
 
-_posix_adapter__cut "$@"
+# If the script is called directly, call the internal function.
+case $0 in
+  *posix_adapter__xxd)
+    posix_adapter__xxd "$@"
+    ;;
+esac
